defmodule <%= app_module %>.Encrypted.Binary do
  @moduledoc """
  Ecto type for transparently encrypting binary fields via Cloak.

  Used by `UserIdentity` for OAuth access and refresh tokens.

  Generated by `mix sigra.gen.oauth`. Customize freely -- this module
  is owned by your application.
  """

  use Cloak.Ecto.Binary, vault: <%= app_module %>.Vault
end
