defmodule <%= web_module %>.OAuthSettingsLive do
  @moduledoc """
  LiveView for managing connected OAuth accounts.

  Shows linked providers with unlink actions and available
  providers to link. Enforces D-03 (block unlink of last
  provider when no password set).

  Generated by `mix sigra.gen.oauth`. Customize freely -- this module
  is owned by your application.
  """

  use <%= web_module %>, :live_view

  import <%= web_module %>.OAuthHTML

  @impl true
  def mount(_params, _session, socket) do
    user = socket.assigns.current_user
    config = socket.assigns[:sigra_config] || raise "Sigra config not found"

    identities = list_user_identities(config, user)
    all_providers = Sigra.Config.oauth_providers(config)
    linked_provider_names = Enum.map(identities, & &1.provider)

    unlinked_providers =
      Enum.reject(all_providers, fn {name, _} ->
        to_string(name) in linked_provider_names
      end)

    has_password = user.hashed_password != nil and user.hashed_password != ""
    has_other_auth = length(identities) > 1 or has_password

    remaining_methods = build_remaining_methods(identities, has_password)

    {:ok,
     assign(socket,
       identities: identities,
       all_providers: all_providers,
       unlinked_providers: unlinked_providers,
       has_no_password: !has_password,
       can_unlink: has_other_auth,
       remaining_methods_text: remaining_methods,
       page_title: "Connected Accounts"
     )}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div class="mx-auto max-w-2xl">
      <.header>
        Connected Accounts
        <:subtitle>Manage your linked sign-in providers.</:subtitle>
      </.header>

      <div class="mt-8 space-y-4">
        <%= if @identities == [] do %>
          <div class="text-center py-8">
            <p class="text-sm font-semibold text-gray-900">No connected accounts</p>
            <p class="mt-1 text-sm text-gray-500">Link a sign-in provider for faster access.</p>
          </div>
        <% else %>
          <%= for identity <- @identities do %>
            <div class="flex items-start justify-between p-4 bg-gray-50 rounded-lg border border-gray-200">
              <div>
                <div class="flex items-center gap-2">
                  {oauth_provider_icon(safe_provider_atom(identity.provider))}
                  <span class="font-semibold text-sm">{oauth_provider_name(safe_provider_atom(identity.provider))}</span>
                  <span class="text-sm text-gray-500">{identity.provider_email}</span>
                </div>
                <div class="mt-1 text-sm text-gray-500">
                  Linked {relative_time(identity.inserted_at)}
                  <%= if identity.last_used_at do %>
                    &middot; Last used {relative_time(identity.last_used_at)}
                  <% end %>
                </div>
              </div>
              <div>
                <%= if @can_unlink do %>
                  <button
                    phx-click="unlink"
                    phx-value-id={identity.id}
                    data-confirm={"Unlink #{oauth_provider_name(safe_provider_atom(identity.provider))}? You'll still be able to log in with: #{@remaining_methods_text}."}
                    class="text-sm text-red-600 bg-red-50 hover:bg-red-100 rounded-md px-3 py-1.5"
                  >
                    Unlink
                  </button>
                <% else %>
                  <button
                    disabled
                    title="Set a password first to keep access to your account."
                    class="text-sm text-red-600 bg-red-50 rounded-md px-3 py-1.5 opacity-50 cursor-not-allowed"
                  >
                    Unlink
                  </button>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>

        <%= if @has_no_password do %>
          <p class="text-sm text-gray-500 mt-4">
            No password set.
            <.link navigate={~p"<%= password_path %>"} class="text-brand hover:underline">Set a password</.link>
            to enable email login and as a backup.
          </p>
        <% end %>

        <%= if @unlinked_providers != [] do %>
          <div class="mt-8">
            <h3 class="text-sm font-semibold">Add a sign-in method</h3>
            <div class="mt-3 space-y-3">
              <%= for {provider, _config} <- @unlinked_providers do %>
                <a
                  href={~p"<%= auth_path %>/#{provider}"}
                  class="w-full h-10 flex items-center justify-center gap-2 rounded-lg border border-gray-300 bg-white hover:bg-gray-50 text-sm font-medium transition-colors"
                >
                  {oauth_provider_icon(provider)}
                  <span>Continue with {oauth_provider_name(provider)}</span>
                </a>
              <% end %>
            </div>
          </div>
        <% else %>
          <p class="mt-8 text-sm text-gray-500">All available providers are connected.</p>
        <% end %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("unlink", %{"id" => identity_id}, socket) do
    config = socket.assigns[:sigra_config] || raise "Sigra config not found"
    user = socket.assigns.current_user
    identity = config.repo.get!(config.identity_schema, identity_id)

    case Sigra.OAuth.unlink_provider(config, user, identity.provider) do
      {:ok, :unlinked} ->
        provider_name = oauth_provider_name(safe_provider_atom(identity.provider))

        {:noreply,
         socket
         |> put_flash(:info, "#{provider_name} has been removed from your account.")
         |> push_navigate(to: ~p"<%= settings_path %>")}

      {:error, :last_provider} ->
        {:noreply,
         put_flash(socket, :error, "Set a password first to keep access to your account.")}

      {:error, _reason} ->
        {:noreply, put_flash(socket, :error, "Could not unlink provider. Please try again.")}
    end
  end

  defp list_user_identities(config, user) do
    import Ecto.Query

    config.identity_schema
    |> where([i], i.user_id == ^user.id)
    |> order_by([i], asc: i.inserted_at)
    |> config.repo.all()
  end

  defp build_remaining_methods(identities, has_password) do
    provider_names =
      identities
      |> Enum.map(fn i ->
        i.provider |> safe_provider_atom() |> oauth_provider_name()
      end)

    methods = if has_password, do: ["Password" | provider_names], else: provider_names

    # Remove current provider from the list (will have one extra)
    case methods do
      [] -> "none"
      list -> Enum.join(list, ", ")
    end
  end

  defp safe_provider_atom(provider) when is_atom(provider), do: provider

  defp safe_provider_atom(provider) when is_binary(provider) do
    String.to_existing_atom(provider)
  rescue
    ArgumentError -> :unknown
  end
end
