defmodule <%= repo_module %>.DataMigrations.BackfillPersonalOrgs do
  @moduledoc """
  Generated by `mix sigra.upgrade --backfill-personal-orgs` (Phase 18).

  Thin Dashbit-style data-migration shim — all batching, telemetry,
  and SQL logic lives in `Sigra.Upgrade.Backfill.run_personal_orgs/2`
  and ships via `mix deps.update`. Never edit this file; regenerate
  with `mix sigra.upgrade --backfill-personal-orgs` if the shape
  needs to change.
  """

  use Ecto.Migration

  # Concurrent-safety flags (fly-apps/safe-ecto-migrations):
  # a multi-hour backfill must NOT hold pg_advisory_lock or block
  # subsequent deploys.
  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    Sigra.Upgrade.Backfill.run_personal_orgs(repo(),
      batch_size: 1_000,
      users_schema: <%= context_module %>.<%= schema_alias %>,
      orgs_schema: <%= context_module %>.Organization
    )
  end

  def down, do: :ok
end
