defmodule Example.Mailer do
  @moduledoc """
  Swoosh mailer for the example app.

  Created by plan 10-06 because the example app was scaffolded with
  `mix phx.new --no-mailer` but the generated Sigra `Example.Accounts.Mailer`
  wrapper calls `Example.Mailer.deliver/1`. In a real app, this would be
  generated by `phx.new` and users would configure the adapter in
  `config/{dev,test,prod}.exs`.
  """
  use Swoosh.Mailer, otp_app: :example
end
