defmodule ExampleWeb.InvitationAcceptLive do
  @moduledoc """
  Phase 17 D-06 — single unscoped LiveView handling invitation acceptance
  across 7 render branches keyed on `@branch`:

    * `:signup`           — anonymous visitor with a valid, pending token
    * `:accept`           — signed-in user whose email matches the invitation
    * `:mismatch`         — signed-in user whose email does NOT match
    * `:invalid`          — HMAC verify failed / garbage / tampered token
    * `:expired`          — envelope or DB row past its expiration
    * `:revoked`          — DB `revoked_at IS NOT NULL`
    * `:already_accepted` — DB `accepted_at IS NOT NULL` (replay)

  ## Structural Jetstream #907 defense

  The `:mismatch` render branch contains ZERO `phx-click`/`phx-submit`
  accept controls. Even if every server-side guard regressed, there is
  no accept form in the rendered DOM to submit. This is the
  "by construction, not by convention" defense locked in via
  17-UI-SPEC §Structural Invariants and enforced by plan-checker grep.

  The `:invalid`, `:expired`, `:revoked`, and `:already_accepted`
  branches also render zero accept controls (defense in depth).

  ## Route

  Unscoped (`live_session :invitations_public`) at
  `/invitations/:token/accept`. Outside any `:require_authenticated_user`
  pipeline — both anonymous and signed-in visitors hit the same LV.
  Generated by `mix sigra.install --organizations`.
  """
  use ExampleWeb, :live_view

  alias Example.Organizations

  @impl true
  def mount(%{"token" => signed_token}, _session, socket) do
    config = Organizations.__sigra_org_config__()
    current_user = current_user_from_scope(socket.assigns[:current_scope])

    branch = Sigra.Organizations.Invitations.load_for_view(config, signed_token, current_user)
    {:ok, assign_branch(socket, signed_token, branch)}
  end

  defp current_user_from_scope(%{user: %{} = user}), do: user
  defp current_user_from_scope(_), do: nil

  defp assign_branch(socket, token, {:signup, invitation, org, inviter}) do
    socket
    |> assign(:branch, :signup)
    |> assign(:token, token)
    |> assign(:invitation, invitation)
    |> assign(:organization, org)
    |> assign(:inviter, inviter)
    |> assign(
      :signup_form,
      to_form(%{"email" => invitation.email, "password" => ""}, as: :user)
    )
    |> assign(:page_title, "Join #{org.name}")
  end

  defp assign_branch(socket, token, {:accept, invitation, org, inviter, user}) do
    socket
    |> assign(:branch, :accept)
    |> assign(:token, token)
    |> assign(:invitation, invitation)
    |> assign(:organization, org)
    |> assign(:inviter, inviter)
    |> assign(:accepting_user, user)
    |> assign(:page_title, "Join #{org.name}")
  end

  defp assign_branch(socket, _token, {:mismatch, invitation, user}) do
    socket
    |> assign(:branch, :mismatch)
    |> assign(:invitation, invitation)
    |> assign(:mismatched_user, user)
    |> assign(:page_title, "Invitation not for you")
  end

  defp assign_branch(socket, _token, {:invalid, :invalid}) do
    socket
    |> assign(:branch, :invalid)
    |> assign(:page_title, "Invalid invitation")
  end

  defp assign_branch(socket, _token, {:expired, invitation}) do
    socket
    |> assign(:branch, :expired)
    |> assign(:invitation, invitation)
    |> assign(:page_title, "Invitation expired")
  end

  defp assign_branch(socket, _token, {:revoked, invitation}) do
    socket
    |> assign(:branch, :revoked)
    |> assign(:invitation, invitation)
    |> assign(:page_title, "Invitation no longer valid")
  end

  defp assign_branch(socket, _token, {:already_accepted, invitation, _member?}) do
    socket
    |> assign(:branch, :already_accepted)
    |> assign(:invitation, invitation)
    |> assign(:page_title, "Invitation already accepted")
  end

  # ─────────────────────────────────────────────────────────────────────
  # Event handlers — bound ONLY to branches that have accept actions.
  #
  # There are no fallback clauses. Synthesizing an accept_invitation or
  # accept_with_signup event on a :mismatch / :invalid / :expired /
  # :revoked / :already_accepted mount will raise ArgumentError (no
  # handler bound). The Jetstream #907 regression test relies on this
  # for its zero-DB-write assertion.
  # ─────────────────────────────────────────────────────────────────────

  @impl true
  def handle_event(
        "accept_invitation",
        _params,
        %{assigns: %{branch: :accept}} = socket
      ) do
    %{token: token, accepting_user: user, organization: org} = socket.assigns

    case Organizations.accept_invitation(token, user) do
      {:ok, _result} ->
        {:noreply,
         socket
         |> put_flash(:info, "You joined #{org.name}.")
         |> redirect(to: ~p"/organizations/#{org.slug}/members")}

      {:error, :already_accepted} ->
        {:noreply,
         socket
         |> put_flash(:info, "You're already a member of #{org.name}.")
         |> redirect(to: ~p"/organizations/#{org.slug}/members")}

      {:error, reason} ->
        {:noreply, put_flash(socket, :error, accept_error_copy(reason))}
    end
  end

  def handle_event(
        "accept_with_signup",
        %{"user" => user_params},
        %{assigns: %{branch: :signup}} = socket
      ) do
    %{token: token, organization: org, invitation: invitation} = socket.assigns

    # The signup form locks `email` via `disabled + readonly`, which
    # means browsers (and Phoenix.LiveViewTest form/3) do NOT submit the
    # field. Fill in the locked email here for the happy path so the
    # library's `assert_signup_email_matches/2` sees it. If an attacker
    # bypassed the disabled attribute and submitted a different email,
    # it stays in user_params and the server-side guard will reject.
    user_params =
      case Map.get(user_params, "email") do
        nil -> Map.put(user_params, "email", invitation.email)
        "" -> Map.put(user_params, "email", invitation.email)
        _ -> user_params
      end

    case Organizations.accept_invitation_with_signup(token, user_params) do
      {:ok, _result} ->
        {:noreply,
         socket
         |> put_flash(:info, "Welcome to #{org.name}.")
         |> redirect(to: ~p"/users/log_in")}

      {:error, :email_mismatch} ->
        form =
          to_form(
            %{"email" => invitation.email, "password" => ""},
            as: :user,
            errors: [
              email: {"This invitation is locked to #{invitation.email}.", []}
            ]
          )

        {:noreply, assign(socket, :signup_form, form)}

      {:error, %Ecto.Changeset{} = cs} ->
        {:noreply, assign(socket, :signup_form, to_form(cs, as: :user))}

      {:error, reason} ->
        {:noreply, put_flash(socket, :error, accept_error_copy(reason))}
    end
  end

  # ──────────────────────────────────────────────────────────────────────
  # Jetstream #907 structural defense — fallback raising clauses.
  #
  # Only the :accept branch handles "accept_invitation" and only the
  # :signup branch handles "accept_with_signup". For any other branch
  # these clauses raise ArgumentError explicitly. This makes the
  # regression test's `assert_raise ArgumentError` expressible as a
  # Phoenix.LiveViewTest assertion instead of the test needing
  # catch_exit for a FunctionClauseError process crash — but the
  # defense is the same either way: the accept event cannot mutate
  # state on any branch other than :accept / :signup.
  # ──────────────────────────────────────────────────────────────────────

  def handle_event("accept_invitation", _params, %{assigns: %{branch: branch}}) do
    raise ArgumentError,
          "accept_invitation is not bound on branch=#{inspect(branch)} — " <>
            "Jetstream #907 structural defense. This event should not " <>
            "originate from a legitimate client."
  end

  def handle_event("accept_with_signup", _params, %{assigns: %{branch: branch}}) do
    raise ArgumentError,
          "accept_with_signup is not bound on branch=#{inspect(branch)} — " <>
            "Jetstream #907 structural defense. This event should not " <>
            "originate from a legitimate client."
  end

  defp accept_error_copy(:invalid), do: "This invitation link is not valid."
  defp accept_error_copy(:expired), do: "This invitation has expired."
  defp accept_error_copy(:revoked), do: "This invitation is no longer valid."
  defp accept_error_copy(:mismatch), do: "This invitation is not for you."
  defp accept_error_copy(_), do: "Unable to accept invitation."

  # ─────────────────────────────────────────────────────────────────────
  # Render — branch-dispatched via case @branch.
  # ─────────────────────────────────────────────────────────────────────

  @impl true
  def render(assigns) do
    ~H"""
    <div id="invitation-accept-page">
      <.flash kind={:info} flash={@flash} />
      <.flash kind={:error} flash={@flash} />

      <%= case @branch do %>
        <% :signup -> %>
          {render_signup(assigns)}
        <% :accept -> %>
          {render_accept(assigns)}
        <% :mismatch -> %>
          {render_mismatch(assigns)}
        <% :invalid -> %>
          {render_invalid(assigns)}
        <% :expired -> %>
          {render_expired(assigns)}
        <% :revoked -> %>
          {render_revoked(assigns)}
        <% :already_accepted -> %>
          {render_already_accepted(assigns)}
      <% end %>
    </div>
    """
  end

  defp render_signup(assigns) do
    ~H"""
    <section id="invitation-accept-signup" class="max-w-md mx-auto py-16 px-4">
      <div class="text-center mb-8">
        <h1 class="text-2xl font-semibold">Join {@organization.name}</h1>
        <p class="text-base mt-2">
          {@inviter.email} invited you to join <strong>{@organization.name}</strong>
          as <span class="font-semibold">{humanize_role(@invitation.role)}</span>.
          Create your account to accept.
        </p>
      </div>

      <.form
        :let={f}
        for={@signup_form}
        id="invitation-signup-form"
        phx-submit="accept_with_signup"
        class="space-y-4"
      >
        <.input
          field={f[:email]}
          type="email"
          label="Email"
          value={@invitation.email}
          disabled
          readonly
        />
        <p class="text-sm text-base-content/70">
          This invitation is locked to {@invitation.email}.
        </p>

        <.input field={f[:password]} type="password" label="Password" required />

        <div>
          <.button type="submit" class="btn btn-primary btn-block">
            Create account & join {@organization.name}
          </.button>
        </div>
      </.form>
    </section>
    """
  end

  defp render_accept(assigns) do
    ~H"""
    <section id="invitation-accept-accept" class="max-w-md mx-auto py-16 px-4">
      <div class="text-center mb-8">
        <h1 class="text-2xl font-semibold">Join {@organization.name}</h1>
        <p class="text-base mt-2">
          {@inviter.email} invited <strong>{@accepting_user.email}</strong>
          to join <strong>{@organization.name}</strong>
          as <span class="font-semibold">{humanize_role(@invitation.role)}</span>.
        </p>
      </div>

      <.button
        id="accept-invitation-button"
        phx-click="accept_invitation"
        phx-disable-with="Joining..."
        class="btn btn-primary btn-block"
      >
        Accept & join {@organization.name}
      </.button>

      <p class="text-sm text-center mt-6 text-base-content/70">
        Not you?
        <.link href={~p"/users/log_out"} method="delete" class="link link-hover">
          Sign out
        </.link>
      </p>
    </section>
    """
  end

  # STRUCTURAL INVARIANT (Jetstream #907 / CVE-2026-1529):
  # This function MUST NOT contain any phx-click="accept..." or
  # phx-submit="accept..." or form action targeting an accept endpoint.
  # The plan-checker greps this function body and asserts zero matches.
  # DO NOT add an accept button here even "for convenience" — the entire
  # point of this branch is that the accept action does not exist in the
  # rendered DOM for a mismatched visitor.
  defp render_mismatch(assigns) do
    ~H"""
    <section id="invitation-accept-mismatch" class="max-w-md mx-auto py-16 px-4">
      <div role="alert" class="alert alert-warning">
        <div>
          <h3 class="font-semibold">This invitation is not for you</h3>
          <p class="text-sm mt-1">
            This invitation was sent to <strong>{@invitation.email}</strong>.
            You are signed in as <strong>{@mismatched_user.email}</strong>.
          </p>
        </div>
      </div>

      <div class="mt-6 text-center text-sm">
        <p class="text-base-content/70">
          To accept this invitation, sign out and sign in as <strong>{@invitation.email}</strong>, or ask the person who
          invited you to resend it.
        </p>
        <p class="mt-4">
          <.link href={~p"/users/log_out"} method="delete" class="link link-hover">
            Sign out
          </.link>
        </p>
      </div>
    </section>
    """
  end

  defp render_invalid(assigns) do
    ~H"""
    <section id="invitation-accept-invalid" class="max-w-md mx-auto py-16 px-4 text-center">
      <h1 class="text-2xl font-semibold">Invalid invitation</h1>
      <p class="text-base mt-4 text-base-content/70">
        This invitation link is not valid.
      </p>
      <.link navigate={~p"/"} class="btn btn-primary mt-6">Return home</.link>
    </section>
    """
  end

  defp render_expired(assigns) do
    ~H"""
    <section id="invitation-accept-expired" class="max-w-md mx-auto py-16 px-4 text-center">
      <h1 class="text-2xl font-semibold">Invitation expired</h1>
      <p class="text-base mt-4 text-base-content/70">
        This invitation has expired. Ask the person who invited you to send a new one.
      </p>
      <.link navigate={~p"/"} class="btn btn-primary mt-6">Return home</.link>
    </section>
    """
  end

  defp render_revoked(assigns) do
    ~H"""
    <section id="invitation-accept-revoked" class="max-w-md mx-auto py-16 px-4 text-center">
      <h1 class="text-2xl font-semibold">Invitation no longer valid</h1>
      <p class="text-base mt-4 text-base-content/70">
        This invitation is no longer valid.
      </p>
      <.link navigate={~p"/"} class="btn btn-primary mt-6">Return home</.link>
    </section>
    """
  end

  defp render_already_accepted(assigns) do
    ~H"""
    <section id="invitation-accept-already" class="max-w-md mx-auto py-16 px-4 text-center">
      <h1 class="text-2xl font-semibold">Invitation already accepted</h1>
      <p class="text-base mt-4 text-base-content/70">
        This invitation has already been accepted.
      </p>
      <.link navigate={~p"/"} class="btn btn-primary mt-6">Return home</.link>
    </section>
    """
  end

  defp humanize_role(role),
    do: role |> to_string() |> String.capitalize()
end
