defmodule ExampleWeb.MFASettingsLive do
  @moduledoc """
  LiveView for MFA enrollment, settings, and management.

  Handles the full MFA lifecycle:
  - Enrollment: QR code display, manual key, confirmation code entry
  - Backup codes: display, copy, download, acknowledgment
  - Settings: enabled status, backup code count, disable, regenerate
  - Trust management: revoke all trusted browsers

  This component is designed to be embedded in the user settings page.

  Generated by `mix sigra.install --live`. Customize freely -- this module
  is owned by your application.
  """
  use ExampleWeb, :live_view

  alias Example.Accounts, as: Auth
  alias Example.Organizations
  alias ExampleWeb.Layouts

  @doc """
  Mount the MFA settings LiveView.

  Checks current MFA status and sets appropriate initial state.
  """
  def mount(_params, _session, socket) do
    user = socket.assigns.current_scope.user
    mfa_status = Auth.mfa_status(user)
    passkeys = Auth.passkeys_for_user(user)
    passkey_count = Auth.passkey_count_for_user(user)

    {:ok,
     assign(socket,
       user_organizations: Organizations.list_organizations_for_user(user),
       mfa_enabled: mfa_status.enabled,
       passkeys: passkeys,
       passkey_count: passkey_count,
       passkey_status: :idle,
       passkey_notice: nil,
       renaming_passkey_id: nil,
       rename_form: to_form(%{"nickname" => ""}, as: "passkey"),
       deleting_passkey_id: nil,
       enrollment_step: nil,
       svg: nil,
       base32_secret: nil,
       raw_secret: nil,
       backup_codes: [],
       backup_remaining: mfa_status.backup_codes_remaining,
       show_disable: false,
       show_regenerate: false,
       codes_acknowledged: false,
       enroll_form: to_form(%{"code" => ""}, as: "enroll"),
       disable_form: to_form(%{"code" => ""}, as: "disable"),
       regenerate_form: to_form(%{"code" => ""}, as: "regenerate"),
       page_title: "MFA Settings"
     )}
  end

  def render(assigns) do
    ~H"""
    <Layouts.app
      flash={@flash}
      current_scope={@current_scope}
      user_organizations={@user_organizations}
    >
      <section class="vt-page-intro" data-testid="app-mfa-settings">
        <header class="vt-panel__header">
          <div>
            <p class="vt-kicker">Security</p>
            <h1 class="vt-panel__title">Two-factor &amp; passkeys</h1>
          </div>
          <a href={~p"/app"} class="vt-btn vt-btn--ghost">Back to dashboard</a>
        </header>
        <%= if @mfa_enabled do %>
          <% # Surface 3: MFA Settings Card %>
          <div class="vt-panel">
            <div class="vt-panel__header">
              <div>
                <p class="vt-kicker">Two-factor authentication</p>
                <span class="vt-status-pill vt-status-pill--ok">Enabled</span>
              </div>
              <button
                phx-click="show_disable"
                class="vt-btn vt-btn--danger"
              >
                Disable
              </button>
            </div>

            <% # Backup code status (D-15) %>
            <div>
              <%= cond do %>
                <% @backup_remaining == 0 -> %>
                  <div class="vt-alert vt-alert--danger">
                    <.icon name="hero-exclamation-triangle" class="h-4 w-4" />
                    All backup codes used. Generate new ones now.
                  </div>
                <% @backup_remaining <= 2 -> %>
                  <div class="vt-alert vt-alert--warning">
                    <.icon name="hero-exclamation-triangle" class="h-4 w-4" />
                    {@backup_remaining} of 8 backup codes remaining
                  </div>
                <% true -> %>
                  <p class="vt-copy">
                    {@backup_remaining} of 8 backup codes remaining
                  </p>
              <% end %>

              <p>
                <button
                  phx-click="show_regenerate"
                  class="vt-link"
                >
                  Regenerate codes
                </button>
              </p>
            </div>

            <% # Trust section %>
            <div>
              <button
                phx-click="revoke_trust"
                data-confirm="This will require two-factor authentication on all your browsers. Continue?"
                class="vt-link"
              >
                Revoke all trusted browsers
              </button>
            </div>
          </div>

          <% # Surface 4: Disable Confirmation %>
          <div :if={@show_disable} class="vt-alert vt-alert--danger">
            <div>
              <h3 class="vt-panel__title">Disable two-factor authentication</h3>
              <p class="vt-copy">
                This will remove the extra security on your account.
                You'll need to set it up again to re-enable.
              </p>

              <.form
                for={@disable_form}
                id="mfa_disable_form"
                phx-submit="disable_mfa"
                class="vt-form"
              >
                <div>
                  <label for="disable_code" class="label">
                    Enter your current 6-digit code or a backup code to confirm:
                  </label>
                  <input
                    type="text"
                    id="disable_code"
                    name="disable[code]"
                    value={@disable_form[:code].value}
                    inputmode="numeric"
                    class="input"
                    required
                  />
                </div>

                <div class="vt-action-row">
                  <button
                    type="submit"
                    class="vt-btn vt-btn--danger"
                  >
                    Disable two-factor authentication
                  </button>
                  <button
                    type="button"
                    phx-click="cancel_disable"
                    class="vt-btn vt-btn--ghost"
                  >
                    Cancel
                  </button>
                </div>
              </.form>
            </div>
          </div>

          <% # Regenerate codes confirmation %>
          <div :if={@show_regenerate} class="vt-panel">
            <div class="vt-panel__header">
              <div>
                <p class="vt-kicker">Backup codes</p>
                <h3 class="vt-panel__title">Regenerate backup codes</h3>
              </div>
            </div>
            <p class="vt-copy">
              This will replace all existing backup codes. Enter your current TOTP code to confirm.
            </p>

            <.form
              for={@regenerate_form}
              id="mfa_regenerate_form"
              phx-submit="regenerate_codes"
              class="vt-form"
            >
              <div>
                <label for="regenerate_code" class="label">
                  Current authenticator code:
                </label>
                <input
                  type="text"
                  id="regenerate_code"
                  name="regenerate[code]"
                  value={@regenerate_form[:code].value}
                  inputmode="numeric"
                  pattern="[0-9]*"
                  maxlength="6"
                  autocomplete="one-time-code"
                  class="input"
                  required
                />
              </div>

              <div class="vt-action-row">
                <.button class="vt-btn vt-btn--primary">Regenerate codes</.button>
                <button
                  type="button"
                  phx-click="cancel_regenerate"
                  class="vt-btn vt-btn--ghost"
                >
                  Cancel
                </button>
              </div>
            </.form>
          </div>

          <% # Backup codes display (after regeneration) %>
          <div :if={@enrollment_step == :backup_codes} class="mt-6">
            {render_backup_codes(assigns)}
          </div>
        <% else %>
          <% # Surface 2: TOTP Enrollment %>
          <%= case @enrollment_step do %>
            <% nil -> %>
              {render_enrollment_start(assigns)}
            <% :qr -> %>
              {render_enrollment_qr(assigns)}
            <% :backup_codes -> %>
              {render_enrollment_backup_codes(assigns)}
            <% :done -> %>
              <div class="vt-panel">
                <div class="vt-panel__header">
                  <div>
                    <p class="vt-kicker">Complete</p>
                    <h3 class="vt-panel__title">Two-factor authentication enabled</h3>
                  </div>
                  <.icon name="hero-check-circle" class="h-8 w-8" style="color:var(--vt-color-primary)" />
                </div>
                <p class="vt-copy">
                  Your account is now protected with an extra layer of security.
                </p>
              </div>
          <% end %>
        <% end %>

        {render_passkeys_section(assigns)}
      </section>
    </Layouts.app>
    """
  end

  defp render_passkeys_section(assigns) do
    ~H"""
    <section id="passkeys" class="vt-panel">
      <div class="vt-panel__header">
        <div>
          <p class="vt-kicker">Sign-in security</p>
          <h2 class="vt-panel__title">Passkeys</h2>
          <p class="vt-copy">
            Use Face ID, Touch ID, Windows Hello, or your password manager to sign in without typing a code.
          </p>
        </div>

        <button
          type="button"
          id="add-passkey-button"
          phx-click="begin_passkey_enrollment"
          disabled={@passkey_status == :enrolling}
          class="vt-btn vt-btn--primary"
        >
          Add passkey
        </button>
      </div>

      <div
        id="passkey-registration-hook"
        phx-hook="PasskeyRegister"
        class="hidden"
      />

      <form
        id="passkey-registration-form"
        action="/users/settings/mfa/passkeys"
        method="post"
        class="hidden"
      >
        <input type="hidden" name="_csrf_token" value={Phoenix.Controller.get_csrf_token()} />
        <input type="hidden" name="passkey[response]" id="passkey-registration-response" />
      </form>

      <div :if={@passkey_notice} class="vt-alert">
        <div>
          <p class="vt-panel__title">{@passkey_notice.title}</p>
          <p class="vt-copy">{@passkey_notice.body}</p>
        </div>
      </div>

      <div>
        <%= if @passkeys == [] do %>
          <div class="vt-empty-state">
            <p class="vt-empty-state__title">No passkeys added yet</p>
            <p class="vt-copy">
              Add a passkey to sign in faster on this device and keep a backup sign-in method available.
            </p>
          </div>
        <% else %>
          <div>
            <div
              :for={passkey <- @passkeys}
              class="vt-panel"
              style="display:flex;align-items:flex-start;justify-content:space-between"
            >
              <div>
                <div style="display:flex;align-items:center;gap:var(--sg-space-2)">
                  <.icon name="hero-key" class="h-4 w-4" style="color:var(--vt-color-muted)" />
                  <p class="vt-panel__title">{Auth.passkey_label(passkey)}</p>
                </div>

                <p class="vt-copy">
                  Added {relative_time(passkey.inserted_at)} &middot;
                  <%= if passkey.last_used_at do %>
                    Last used {relative_time(passkey.last_used_at)}
                  <% else %>
                    Never used
                  <% end %>
                </p>

                <div :if={@renaming_passkey_id == passkey_param_id(passkey)}>
                  <.form
                    for={@rename_form}
                    phx-submit="save_passkey_name"
                    class="vt-form"
                  >
                    <input type="hidden" name="passkey[id]" value={passkey_param_id(passkey)} />
                    <div>
                      <label
                        for={"passkey-name-#{passkey_param_id(passkey)}"}
                        class="label"
                      >
                        Passkey name
                      </label>
                      <input
                        id={"passkey-name-#{passkey_param_id(passkey)}"}
                        type="text"
                        name="passkey[nickname]"
                        value={@rename_form[:nickname].value}
                        class="input"
                      />
                    </div>
                    <div class="vt-action-row">
                      <button type="submit" class="vt-btn vt-btn--primary">
                        Save name
                      </button>
                      <button
                        type="button"
                        phx-click="cancel_passkey_rename"
                        class="vt-btn vt-btn--ghost"
                      >
                        Cancel
                      </button>
                    </div>
                  </.form>
                </div>

                <div
                  :if={@deleting_passkey_id == passkey_param_id(passkey)}
                  class="vt-alert vt-alert--danger"
                >
                  <div>
                    <p class="vt-panel__title">Delete this passkey?</p>
                    <p class="vt-copy">
                      You'll still need another sign-in method before removing your last recovery option.
                    </p>
                    <p :if={@passkey_count == 1} class="vt-copy">
                      You're removing your last passkey. Make sure you can still sign in with your password, authenticator code, backup code, or magic link.
                    </p>

                    <div class="vt-action-row">
                      <form
                        action={"/users/settings/mfa/passkeys/#{passkey_param_id(passkey)}/delete"}
                        method="post"
                      >
                        <input
                          type="hidden"
                          name="_csrf_token"
                          value={Phoenix.Controller.get_csrf_token()}
                        />
                        <button
                          type="submit"
                          class="vt-btn vt-btn--danger"
                        >
                          Delete
                        </button>
                      </form>
                      <button
                        type="button"
                        phx-click="cancel_passkey_delete"
                        class="vt-btn vt-btn--ghost"
                      >
                        Cancel
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              <div style="display:flex;flex-shrink:0;align-items:center;gap:var(--sg-space-2)">
                <button
                  type="button"
                  phx-click="open_passkey_rename"
                  phx-value-id={passkey_param_id(passkey)}
                  class="vt-link"
                >
                  Rename
                </button>
                <button
                  type="button"
                  phx-click="confirm_passkey_delete"
                  phx-value-id={passkey_param_id(passkey)}
                  class="vt-btn vt-btn--danger"
                >
                  Delete
                </button>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </section>
    """
  end

  defp render_enrollment_start(assigns) do
    ~H"""
    <section class="vt-panel">
      <div class="vt-panel__header">
        <div>
          <p class="vt-kicker">Two-factor</p>
          <h2 class="vt-panel__title">Two-factor authentication</h2>
        </div>
      </div>
      <p class="vt-copy">
        Add an extra layer of security — enter a code from your authenticator app when you sign in.
      </p>
      <button type="button" phx-click="begin_enrollment" class="vt-btn vt-btn--primary">
        Set up two-factor authentication
      </button>
    </section>
    """
  end

  defp render_enrollment_qr(assigns) do
    ~H"""
    <div class="vt-panel">
      <div class="vt-panel__header">
        <div>
          <p class="vt-kicker">Setup</p>
          <h2 class="vt-panel__title">Two-Factor Authentication</h2>
          <p class="vt-copy">Add an extra layer of security to your account.</p>
        </div>
      </div>

      <div>
        <% # QR Code %>
        <div style="text-align:center">
          <p class="vt-copy">Scan this QR code with your authenticator app</p>
          <div
            role="img"
            aria-label="QR code for TOTP setup"
          >
            {raw(@svg)}
          </div>
        </div>

        <% # Manual key %>
        <div>
          <p class="vt-copy">Can't scan? Enter this key manually:</p>
          <div
            class="vt-alert"
            style="justify-content:center;user-select:all"
          >
            <code data-testid="mfa-totp-secret" class="vt-code">
              {@base32_secret}
            </code>
          </div>
        </div>

        <% # Confirmation form %>
        <div>
          <p class="vt-copy">Enter the 6-digit code from your app to verify setup:</p>

          <.form
            for={@enroll_form}
            id="mfa_enroll_form"
            phx-change="validate_enroll"
            phx-submit="confirm_enrollment"
            class="vt-form"
          >
            <div>
              <input
                type="text"
                name="enroll[code]"
                value={@enroll_form[:code].value}
                inputmode="numeric"
                pattern="[0-9]*"
                maxlength="6"
                autocomplete="one-time-code"
                autofocus
                required
                class="input"
                style="font-variant-numeric:tabular-nums;letter-spacing:0.25em;text-align:center"
                aria-label="6-digit verification code"
              />
            </div>

            <.button class="vt-btn vt-btn--primary">
              Enable two-factor authentication
            </.button>
          </.form>
        </div>
      </div>
    </div>
    """
  end

  defp render_enrollment_backup_codes(assigns) do
    ~H"""
    <div>
      {render_backup_codes(assigns)}
    </div>
    """
  end

  defp render_backup_codes(assigns) do
    ~H"""
    <div class="vt-panel">
      <div class="vt-panel__header">
        <div>
          <p class="vt-kicker">Backup codes</p>
          <h2 class="vt-panel__title">Save your backup codes</h2>
          <p class="vt-copy">Store these codes in a safe place. Each code can only be used once.</p>
        </div>
      </div>

      <% # Backup code grid (D-08) %>
      <div class="vt-alert" style="display:block">
        <ol style="display:grid;grid-template-columns:1fr 1fr;gap:var(--sg-space-3)">
          <li :for={code <- @backup_codes} style="text-align:center">
            <code class="vt-code">{code}</code>
          </li>
        </ol>
      </div>

      <% # Action buttons %>
      <div class="vt-action-row">
        <button
          type="button"
          phx-hook="CopyBackupCodes"
          id="copy-backup-codes"
          data-codes={Enum.join(@backup_codes, "\n")}
          class="vt-btn vt-btn--ghost"
        >
          <.icon name="hero-clipboard-document" class="h-4 w-4" />
          <span id="copy-btn-text">Copy all</span>
        </button>
        <button
          type="button"
          phx-hook="DownloadBackupCodes"
          id="download-backup-codes"
          data-codes={Enum.join(@backup_codes, "\n")}
          class="vt-btn vt-btn--ghost"
        >
          <.icon name="hero-arrow-down-tray" class="h-4 w-4" /> Download .txt
        </button>
      </div>

      <% # Acknowledgment checkbox (D-11) %>
      <div>
        <label style="display:flex;align-items:center;gap:var(--sg-space-2);font-size:var(--sg-text-sm)">
          <input
            type="checkbox"
            phx-click="toggle_acknowledge"
            checked={@codes_acknowledged}
          /> I have saved these backup codes in a safe place
        </label>
      </div>

      <% # Done button %>
      <div>
        <.button
          phx-click="complete_enrollment"
          disabled={!@codes_acknowledged}
          class="vt-btn vt-btn--primary"
        >
          Done
        </.button>
      </div>
    </div>
    """
  end

  # -- Event Handlers --

  def handle_event("begin_enrollment", _params, socket) do
    user = socket.assigns.current_scope.user

    case Auth.mfa_enroll(account: user.email) do
      {:ok, enrollment} ->
        {:noreply,
         assign(socket,
           enrollment_step: :qr,
           svg: enrollment.svg,
           base32_secret: enrollment.secret,
           raw_secret: enrollment.raw_secret
         )}
    end
  end

  def handle_event("validate_enroll", %{"enroll" => %{"code" => code}}, socket) do
    form = to_form(%{"code" => code}, as: "enroll")
    socket = assign(socket, enroll_form: form)

    # Auto-submit when 6 digits entered (D-36). 10.1 IN-06 follow-up:
    # call the confirm path directly instead of dispatching via
    # `send(self(), …)`. The mailbox round-trip allowed a stale 6-digit
    # prefix to fire after the user typed a 7th character, wasting an
    # attempt against the MFA lockout counter.
    if String.length(code) == 6 and Regex.match?(~r/^\d{6}$/, code) do
      do_confirm_enrollment(socket, code)
    else
      {:noreply, socket}
    end
  end

  def handle_event("confirm_enrollment", %{"enroll" => %{"code" => code}}, socket) do
    do_confirm_enrollment(socket, code)
  end

  def handle_event("toggle_acknowledge", _params, socket) do
    {:noreply, assign(socket, codes_acknowledged: !socket.assigns.codes_acknowledged)}
  end

  def handle_event("complete_enrollment", _params, socket) do
    if socket.assigns.codes_acknowledged do
      user = socket.assigns.current_scope.user
      mfa_status = Auth.mfa_status(user)

      {:noreply,
       assign(socket,
         mfa_enabled: true,
         enrollment_step: nil,
         backup_codes: [],
         backup_remaining: mfa_status.backup_codes_remaining,
         codes_acknowledged: false
       )}
    else
      {:noreply, socket}
    end
  end

  def handle_event("begin_passkey_enrollment", _params, socket) do
    {:noreply,
     socket
     |> assign(passkey_status: :enrolling, passkey_notice: nil)
     |> push_event("sigra:passkey-register:start", %{
       optionsUrl: "/users/settings/mfa/passkeys/options",
       completeUrl: "/users/settings/mfa/passkeys"
     })}
  end

  def handle_event("sigra:passkey-register:success", _params, socket) do
    {:noreply,
     assign(socket,
       passkey_status: :idle,
       passkey_notice: %{
         title: "Finishing passkey setup...",
         body: "Keep this page open while we finish saving your passkey."
       }
     )}
  end

  def handle_event("sigra:passkey-register:aborted", _params, socket) do
    {:noreply,
     assign(socket,
       passkey_status: :idle,
       passkey_notice: %{
         title: "Passkey sign-in was canceled.",
         body: "Nothing changed. Try again or choose another way to continue."
       }
     )}
  end

  def handle_event("sigra:passkey-register:error", payload, socket) do
    notice =
      case passkey_error_bucket(payload) do
        :timeout ->
          %{
            title: "That passkey request timed out.",
            body: "Try again when you're ready, or use another sign-in method."
          }

        :unsupported ->
          %{
            title: "Passkeys aren't available in this browser.",
            body:
              "Use your password or a magic link here, or switch to a device that supports passkeys."
          }

        :generic ->
          %{
            title: "We couldn't finish passkey sign-in.",
            body: "Try again or use another way to continue."
          }
      end

    {:noreply, assign(socket, passkey_status: :idle, passkey_notice: notice)}
  end

  def handle_event("open_passkey_rename", %{"id" => credential_id}, socket) do
    nickname =
      socket
      |> find_passkey(credential_id)
      |> case do
        nil -> ""
        passkey -> passkey.nickname || ""
      end

    {:noreply,
     assign(socket,
       renaming_passkey_id: credential_id,
       rename_form: to_form(%{"nickname" => nickname}, as: "passkey"),
       deleting_passkey_id: nil
     )}
  end

  def handle_event("cancel_passkey_rename", _params, socket) do
    {:noreply,
     assign(socket,
       renaming_passkey_id: nil,
       rename_form: to_form(%{"nickname" => ""}, as: "passkey")
     )}
  end

  def handle_event("save_passkey_name", %{"passkey" => params}, socket) do
    user = socket.assigns.current_scope.user
    credential_id = Map.get(params, "id")
    nickname = Map.get(params, "nickname", "")

    if impersonating?(socket) do
      {:noreply,
       put_flash(
         socket,
         :error,
         "You can't change account security settings while impersonating."
       )}
    else
      case Auth.rename_passkey(user, credential_id, nickname || "",
             scope: socket.assigns.current_scope
           ) do
        {:ok, _passkey} ->
          {:noreply,
           socket
           |> put_flash(:info, "Passkey name saved.")
           |> refresh_passkey_assigns()
           |> assign(
             renaming_passkey_id: nil,
             rename_form: to_form(%{"nickname" => ""}, as: "passkey")
           )}

        {:error, :impersonation_forbidden} ->
          {:noreply,
           put_flash(
             socket,
             :error,
             "You can't change account security settings while impersonating."
           )}

        {:error, _reason} ->
          {:noreply, put_flash(socket, :error, "Could not save passkey name. Please try again.")}
      end
    end
  end

  def handle_event("confirm_passkey_delete", %{"id" => credential_id}, socket) do
    {:noreply,
     assign(socket,
       deleting_passkey_id: credential_id,
       renaming_passkey_id: nil,
       rename_form: to_form(%{"nickname" => ""}, as: "passkey")
     )}
  end

  def handle_event("cancel_passkey_delete", _params, socket) do
    {:noreply, assign(socket, deleting_passkey_id: nil)}
  end

  def handle_event("show_disable", _params, socket) do
    {:noreply, assign(socket, show_disable: true)}
  end

  def handle_event("cancel_disable", _params, socket) do
    {:noreply,
     assign(socket, show_disable: false, disable_form: to_form(%{"code" => ""}, as: "disable"))}
  end

  def handle_event("disable_mfa", %{"disable" => %{"code" => code}}, socket) do
    user = socket.assigns.current_scope.user

    if impersonating?(socket) do
      {:noreply,
       put_flash(
         socket,
         :error,
         "You can't change account security settings while impersonating."
       )}
    else
      case Auth.mfa_disable(user, code, scope: socket.assigns.current_scope) do
        {:ok, :disabled} ->
          {:noreply,
           socket
           |> put_flash(:info, "Two-factor authentication has been disabled.")
           |> put_flash(:warning, "Consider changing your password for additional security.")
           |> assign(
             mfa_enabled: false,
             show_disable: false,
             enrollment_step: nil,
             backup_remaining: 0,
             disable_form: to_form(%{"code" => ""}, as: "disable")
           )}

        {:error, :invalid_code, _remaining} ->
          {:noreply,
           socket
           |> put_flash(:error, "Invalid verification code. Please try again.")
           |> assign(disable_form: to_form(%{"code" => ""}, as: "disable"))}

        {:error, :invalid_backup_code, _remaining} ->
          {:noreply,
           socket
           |> put_flash(:error, "Invalid verification code. Please try again.")
           |> assign(disable_form: to_form(%{"code" => ""}, as: "disable"))}

        {:error, :lockout, seconds} ->
          minutes = div(seconds + 59, 60)

          {:noreply,
           socket
           |> put_flash(:error, "Too many failed attempts. Try again in #{minutes} minutes.")}

        {:error, :impersonation_forbidden} ->
          {:noreply,
           put_flash(
             socket,
             :error,
             "You can't change account security settings while impersonating."
           )}

        {:error, _reason} ->
          {:noreply,
           socket
           |> put_flash(:error, "Could not disable two-factor authentication. Please try again.")}
      end
    end
  end

  def handle_event("show_regenerate", _params, socket) do
    {:noreply, assign(socket, show_regenerate: true)}
  end

  def handle_event("cancel_regenerate", _params, socket) do
    {:noreply,
     assign(socket,
       show_regenerate: false,
       regenerate_form: to_form(%{"code" => ""}, as: "regenerate")
     )}
  end

  def handle_event("regenerate_codes", %{"regenerate" => %{"code" => code}}, socket) do
    user = socket.assigns.current_scope.user

    case Auth.mfa_regenerate_backup_codes(user, {:totp, code},
           scope: socket.assigns.current_scope
         ) do
      {:ok, %{backup_codes: codes}} ->
        mfa_status = Auth.mfa_status(user)

        {:noreply,
         socket
         |> put_flash(:info, "Your backup codes were regenerated. Save your new backup codes.")
         |> assign(
           show_regenerate: false,
           backup_codes: codes,
           enrollment_step: :backup_codes,
           codes_acknowledged: false,
           backup_remaining: mfa_status.backup_codes_remaining,
           regenerate_form: to_form(%{"code" => ""}, as: "regenerate")
         )}

      {:error, :invalid_code, _remaining} ->
        {:noreply,
         socket
         |> put_flash(:error, "Invalid verification code. Please try again.")
         |> assign(regenerate_form: to_form(%{"code" => ""}, as: "regenerate"))}

      {:error, :lockout, seconds} ->
        minutes = div(seconds + 59, 60)

        {:noreply,
         socket
         |> put_flash(:error, "Too many failed attempts. Try again in #{minutes} minutes.")}

      {:error, :not_enrolled} ->
        {:noreply,
         socket
         |> put_flash(:error, "Two-factor authentication is not enabled for this account.")
         |> assign(regenerate_form: to_form(%{"code" => ""}, as: "regenerate"))}

      {:error, :impersonation_forbidden} ->
        {:noreply,
         put_flash(
           socket,
           :error,
           "You can't change account security settings while impersonating."
         )}

      {:error, _reason} ->
        {:noreply,
         socket
         |> put_flash(:error, "Could not regenerate backup codes. Please try again.")
         |> assign(regenerate_form: to_form(%{"code" => ""}, as: "regenerate"))}
    end
  end

  def handle_event("revoke_trust", _params, socket) do
    user = socket.assigns.current_scope.user
    config = Auth.sigra_config()
    Sigra.MFA.Trust.revoke_all(config.repo, config.user_schema, user.id)

    {:noreply,
     socket
     |> put_flash(:info, "All trusted browsers have been revoked.")}
  end

  defp do_confirm_enrollment(socket, code) do
    user = socket.assigns.current_scope.user
    raw_secret = socket.assigns.raw_secret

    case Auth.mfa_confirm_enrollment(user, raw_secret, code) do
      {:ok, %{backup_codes: codes}} ->
        {:noreply,
         socket
         |> put_flash(:info, "Two-factor authentication has been enabled.")
         |> assign(
           enrollment_step: :backup_codes,
           backup_codes: codes,
           codes_acknowledged: false,
           raw_secret: nil
         )}

      {:error, :invalid_code} ->
        form = to_form(%{"code" => ""}, as: "enroll")

        {:noreply,
         socket
         |> put_flash(:error, "Invalid verification code. Please try again.")
         |> assign(enroll_form: form)}

      {:error, _reason} ->
        form = to_form(%{"code" => ""}, as: "enroll")

        {:noreply,
         socket
         |> put_flash(:error, "Could not verify your code. Please try again.")
         |> assign(enroll_form: form)}
    end
  end

  defp passkey_error_bucket(payload) when is_map(payload) do
    payload
    |> Map.take(["code", "name", "message"])
    |> Map.values()
    |> Enum.map(&to_string/1)
    |> Enum.join(" ")
    |> String.downcase()
    |> classify_passkey_error()
  end

  defp passkey_error_bucket(_payload), do: :generic

  defp classify_passkey_error(text) do
    cond do
      String.contains?(text, "timeout") ->
        :timeout

      String.contains?(text, "unsupported") or String.contains?(text, "not_supported") or
          String.contains?(text, "notallowed") ->
        :unsupported

      true ->
        :generic
    end
  end

  defp refresh_passkey_assigns(socket) do
    user = socket.assigns.current_scope.user

    assign(socket,
      passkeys: Auth.passkeys_for_user(user),
      passkey_count: Auth.passkey_count_for_user(user)
    )
  end

  defp impersonating?(socket) do
    match?(
      %{impersonating_from: impersonator} when not is_nil(impersonator),
      socket.assigns.current_scope
    )
  end

  defp find_passkey(socket, credential_id) do
    Enum.find(socket.assigns.passkeys, &(passkey_param_id(&1) == to_string(credential_id)))
  end

  defp passkey_param_id(%{credential_id: credential_id}) when is_binary(credential_id) do
    Base.url_encode64(credential_id, padding: false)
  end

  defp relative_time(nil), do: "Never"

  defp relative_time(%DateTime{} = dt) do
    diff = DateTime.diff(DateTime.utc_now(), dt, :second)
    format_relative_seconds(diff)
  end

  defp relative_time(%NaiveDateTime{} = ndt) do
    ndt
    |> DateTime.from_naive!("Etc/UTC")
    |> relative_time()
  end

  defp format_relative_seconds(seconds) when seconds < 60, do: "just now"
  defp format_relative_seconds(seconds) when seconds < 3600, do: "#{div(seconds, 60)}m ago"
  defp format_relative_seconds(seconds) when seconds < 86_400, do: "#{div(seconds, 3600)}h ago"
  defp format_relative_seconds(seconds), do: "#{div(seconds, 86_400)}d ago"
end
