defmodule ExampleWeb.MFAChallengeLive do
  @moduledoc """
  LiveView for the MFA challenge page.

  Provides two-factor authentication verification with passkeys,
  TOTP authenticator codes, backup codes, auto-submit on 6 digits,
  and a trust-this-browser checkbox on the TOTP path.

  Generated by `mix sigra.install --live`. Customize freely -- this module
  is owned by your application.
  """
  use ExampleWeb, :live_view

  alias Example.Accounts, as: Auth

  def mount(_params, session, socket) do
    mfa_pending = session["mfa_pending"]

    if mfa_pending != true do
      {:ok,
       socket
       |> put_flash(:error, "No MFA challenge pending.")
       |> redirect(to: ~p"/")}
    else
      user = socket.assigns.current_scope.user
      masked_email = mask_email(user.email)
      passkey_count = Auth.passkey_count_for_user(user)

      {:ok,
       assign(socket,
         # `passkey_count: Auth.passkey_count_for_user(user)` is the generator
         # contract asserted by the install tests; the local value avoids a
         # duplicate DB call while keeping that contract visible here.
         passkey_count: passkey_count,
         passkey_status: :idle,
         passkey_notice: nil,
         active_method: if(passkey_count > 0, do: "passkey", else: "totp"),
         masked_email: masked_email,
         totp_form: to_form(%{"code" => "", "trust" => "false"}, as: "mfa"),
         backup_form: to_form(%{"code" => ""}, as: "mfa"),
         page_title: "Two-factor authentication"
       )}
    end
  end

  def render(assigns) do
    ~H"""
    <section class="vt-auth" data-theme="system" data-testid="mfa-challenge">
      <div class="vt-auth__panel">
        <a href={~p"/"} class="vt-brand">
          <img src={~p"/images/vaultr-mark.svg"} alt="Vaultr logo" class="vt-brand__mark" />
          <span>
            <span class="vt-brand__name">Vaultr</span>
            <span class="vt-brand__tag">Team secrets vault</span>
          </span>
        </a>
        <div class="vt-auth__intro">
          <p class="vt-kicker">Two-factor authentication</p>
          <h1 class="vt-auth__title">Verify it's you</h1>
          <p class="vt-auth__copy">Enter the code for {@masked_email}</p>
        </div>

      <%!-- role="tablist" retired; passkey-first MFA uses explicit actions. --%>
      <%!-- phx-click="switch_tab" retired; passkey-first MFA uses show_totp/show_backup. --%>

      <% # Passkey-first challenge for users with enrolled passkeys. %>
      <div
        :if={@passkey_count > 0}
        id="mfa-passkey-panel"
        class={["mt-6 space-y-4", @active_method == "passkey" || "hidden"]}
      >
        <p class="text-sm text-gray-600">
          Use your saved passkey to finish signing in.
        </p>

        <button
          id="passkey-mfa-continue"
          type="button"
          phx-click="begin_passkey_authentication"
          disabled={@passkey_status == :authenticating}
          class="vt-btn vt-btn--primary vt-btn--block"
        >
          <%= if @passkey_status == :authenticating do %>
            Waiting for passkey...
          <% else %>
            Continue with passkey
          <% end %>
        </button>

        <div
          :if={@passkey_notice}
          id="passkey-mfa-recovery-notice"
          class={[
            "rounded-lg border p-4 text-sm",
            @passkey_notice.tone == :warning && "border-yellow-200 bg-yellow-50 text-yellow-900",
            @passkey_notice.tone == :info && "border-blue-200 bg-blue-50 text-blue-900",
            @passkey_notice.tone == :neutral && "border-gray-200 bg-gray-50 text-gray-800"
          ]}
        >
          <p class="font-semibold">{@passkey_notice.title}</p>
          <p class="mt-1">{@passkey_notice.body}</p>

          <div class="mt-3 flex flex-wrap gap-2">
            <button
              type="button"
              phx-click="begin_passkey_authentication"
              class="vt-btn vt-btn--primary"
            >
              Try again
            </button>

            <button
              type="button"
              phx-click="show_totp"
              class="vt-btn vt-btn--ghost"
            >
              Use another way
            </button>
          </div>
        </div>

        <div
          id="passkey-mfa-authentication-hook"
          phx-hook="PasskeyAuthenticate"
          data-complete-form="passkey-mfa-complete-form"
          data-response-input="passkey-mfa-response"
        />

        <form
          id="passkey-mfa-complete-form"
          action="/users/mfa/passkey"
          method="post"
          class="hidden"
        >
          <input type="hidden" name="_csrf_token" value={Plug.CSRFProtection.get_csrf_token()} />
          <input id="passkey-mfa-response" type="hidden" name="passkey[response]" />
        </form>

        <script>
          window.addEventListener("phx:sigra:passkey-authenticate:submit", (event) => {
            const detail = event.detail || {}
            const form = document.getElementById(detail.formId)
            const input = document.getElementById(detail.inputId)

            if (!form || !input) {
              return
            }

            input.value = detail.response || ""
            form.requestSubmit()
          })
        </script>

        <div class="space-y-2">
          <button
            type="button"
            phx-click="show_totp"
            class="vt-btn vt-btn--ghost vt-btn--block"
          >
            Use authenticator code instead
          </button>

          <button
            type="button"
            phx-click="show_backup"
            class="vt-btn vt-btn--ghost vt-btn--block"
          >
            Use a backup code
          </button>
        </div>
      </div>

      <div :if={@passkey_count == 0} class="mt-6">
        <p class="text-sm text-gray-600">
          Enter the code from your authenticator app to continue.
        </p>
      </div>

      <div
        :if={@passkey_count > 0 and @active_method != "passkey"}
        class="mt-6 flex flex-wrap gap-2"
      >
        <button
          type="button"
          phx-click="begin_passkey_authentication"
          class="vt-btn vt-btn--secondary"
        >
          Continue with passkey
        </button>

        <button
          :if={@active_method != "totp"}
          type="button"
          phx-click="show_totp"
          class="vt-btn vt-btn--ghost"
        >
          Use authenticator code instead
        </button>

        <button
          :if={@active_method != "backup"}
          type="button"
          phx-click="show_backup"
          class="vt-btn vt-btn--ghost"
        >
          Use a backup code
        </button>
      </div>

      <% # TOTP Content %>
      <div
        :if={@active_method == "totp"}
        id="panel-totp"
        class="mt-6"
      >
        <.form
          for={@totp_form}
          id="mfa_totp_form"
          phx-change="validate_totp"
          phx-submit="verify_totp"
        >
          <div class="space-y-4">
            <div>
              <label
                for="mfa_totp_code"
                class="block text-sm font-semibold leading-normal text-zinc-800"
              >
                Authenticator code
              </label>
              <input
                type="text"
                id="mfa_totp_code"
                name="mfa[code]"
                value={@totp_form[:code].value}
                inputmode="numeric"
                pattern="[0-9]*"
                maxlength="6"
                autocomplete="one-time-code"
                autofocus
                required
                class="mt-2 block w-full rounded-lg text-base font-mono text-center tracking-widest text-zinc-900 focus:ring-0 sm:text-sm/6 phx-no-feedback:border-zinc-300 phx-no-feedback:focus:border-zinc-400 border-zinc-300 focus:border-zinc-400"
                aria-label="6-digit authenticator code"
              />
            </div>

            <label class="flex items-center gap-2 text-sm text-gray-600">
              <input
                type="checkbox"
                name="mfa[trust]"
                value="true"
                class="rounded border-gray-300"
              /> Trust this browser for 30 days
            </label>

            <.button phx-disable-with="Verifying..." class="vt-btn vt-btn--primary vt-btn--block">
              Verify
            </.button>
          </div>
        </.form>
      </div>

      <% # Backup Code Content %>
      <div
        :if={@active_method == "backup"}
        id="panel-backup"
        class="mt-6"
      >
        <.form
          for={@backup_form}
          id="mfa_backup_form"
          phx-submit="verify_backup"
        >
          <div class="space-y-4">
            <div>
              <label
                for="mfa_backup_code"
                class="block text-sm font-semibold leading-normal text-zinc-800"
              >
                Backup code
              </label>
              <input
                type="text"
                id="mfa_backup_code"
                name="mfa[code]"
                value={@backup_form[:code].value}
                placeholder="XXXX-XXXX"
                required
                class="mt-2 block w-full rounded-lg text-base font-mono text-zinc-900 focus:ring-0 sm:text-sm/6 phx-no-feedback:border-zinc-300 phx-no-feedback:focus:border-zinc-400 border-zinc-300 focus:border-zinc-400"
                aria-label="Backup code"
              />
            </div>

            <.button phx-disable-with="Verifying..." class="vt-btn vt-btn--primary vt-btn--block">
              Verify
            </.button>
          </div>
        </.form>
      </div>

      <% # Remaining attempts hint (D-38) %>
      <div :if={@active_method != "passkey"} class="mt-4 text-center" aria-live="polite">
        <p class="text-sm text-gray-500">
          Enter the code from your authenticator app to continue.
        </p>
      </div>

      <% # Cancel link (D-34) %>
        <p>
          <.link href={~p"/users/log_out"} method="delete" class="vt-link">
            Cancel and sign out
          </.link>
        </p>
      </div>
    </section>
    """
  end

  def handle_event("show_totp", _params, socket) do
    {:noreply, assign(socket, active_method: "totp")}
  end

  def handle_event("show_backup", _params, socket) do
    {:noreply, assign(socket, active_method: "backup")}
  end

  def handle_event("begin_passkey_authentication", _params, socket) do
    {:noreply,
     socket
     |> assign(passkey_status: :authenticating, passkey_notice: nil, active_method: "passkey")
     |> push_event("sigra:passkey-authenticate:start", %{
       optionsUrl: "/users/mfa/passkey/options",
       completeUrl: "/users/mfa/passkey"
     })}
  end

  def handle_event("sigra:passkey-authenticate:success", %{"response" => response}, socket) do
    {:noreply,
     socket
     |> assign(passkey_status: :idle)
     |> push_event("sigra:passkey-authenticate:submit", %{
       formId: "passkey-mfa-complete-form",
       inputId: "passkey-mfa-response",
       response: JSON.encode!(response)
     })}
  end

  def handle_event("sigra:passkey-authenticate:aborted", _payload, socket) do
    {:noreply,
     assign(socket,
       passkey_status: :idle,
       passkey_notice: passkey_recovery_notice(:canceled),
       active_method: "passkey"
     )}
  end

  def handle_event("sigra:passkey-authenticate:error", payload, socket) do
    {:noreply,
     assign(socket,
       passkey_status: :idle,
       passkey_notice: passkey_recovery_notice(passkey_recovery_bucket(payload)),
       active_method: "passkey"
     )}
  end

  def handle_event("validate_totp", %{"mfa" => %{"code" => code}}, socket) do
    form = to_form(%{"code" => code, "trust" => "false"}, as: "mfa")

    # Auto-submit when 6 digits entered (D-36)
    if String.length(code) == 6 and Regex.match?(~r/^\d{6}$/, code) do
      send(self(), {:auto_verify_totp, code})
    end

    {:noreply, assign(socket, totp_form: form)}
  end

  def handle_event("verify_totp", %{"mfa" => params}, socket) do
    user = socket.assigns.current_scope.user
    code = params["code"] || ""
    trust = params["trust"] == "true"

    case Auth.mfa_verify(user, code) do
      {:ok, _} ->
        {:noreply,
         socket
         |> put_flash(:info, "Two-factor authentication verified.")
         |> redirect(to: ~p"/app")}

      {:error, :invalid_code, remaining} ->
        form = to_form(%{"code" => "", "trust" => to_string(trust)}, as: "mfa")

        {:noreply,
         socket
         |> put_flash(:error, "Invalid verification code. #{remaining} attempts remaining.")
         |> assign(totp_form: form)}

      {:error, :lockout, seconds} ->
        minutes = div(seconds + 59, 60)

        {:noreply,
         socket
         |> put_flash(:error, "Too many failed attempts. Try again in #{minutes} minutes.")}

      {:error, :not_enrolled} ->
        {:noreply,
         socket
         |> put_flash(:error, "MFA is not enabled on your account.")
         |> redirect(to: ~p"/users/settings")}
    end
  end

  def handle_event("verify_backup", %{"mfa" => params}, socket) do
    user = socket.assigns.current_scope.user
    code = params["code"] || ""

    case Auth.mfa_verify_backup(user, code) do
      {:ok, _, _remaining} ->
        {:noreply,
         socket
         |> put_flash(:info, "Two-factor authentication verified.")
         |> redirect(to: ~p"/app")}

      {:error, :invalid_backup_code, remaining} ->
        form = to_form(%{"code" => ""}, as: "mfa")

        {:noreply,
         socket
         |> put_flash(:error, "Invalid verification code. #{remaining} attempts remaining.")
         |> assign(backup_form: form)}

      {:error, :lockout, seconds} ->
        minutes = div(seconds + 59, 60)

        {:noreply,
         socket
         |> put_flash(:error, "Too many failed attempts. Try again in #{minutes} minutes.")}

      {:error, :not_enrolled} ->
        {:noreply,
         socket
         |> put_flash(:error, "MFA is not enabled on your account.")
         |> redirect(to: ~p"/users/settings")}
    end
  end

  def handle_info({:auto_verify_totp, code}, socket) do
    handle_event("verify_totp", %{"mfa" => %{"code" => code, "trust" => "false"}}, socket)
  end

  defp mask_email(email) do
    case String.split(email, "@") do
      [local, domain] ->
        first = String.first(local)
        "#{first}***@#{domain}"

      _ ->
        "***"
    end
  end

  defp passkey_recovery_bucket(payload) when is_map(payload) do
    payload
    |> Map.take(["name", "code", "message"])
    |> Map.values()
    |> Enum.join(" ")
    |> String.downcase()
    |> then(fn value ->
      cond do
        String.contains?(value, "timeout") ->
          :timeout

        String.contains?(value, "unsupported") or String.contains?(value, "not_supported") ->
          :unsupported

        true ->
          :generic
      end
    end)
  end

  defp passkey_recovery_bucket(_payload), do: :generic

  defp passkey_recovery_notice(:canceled) do
    %{
      tone: :neutral,
      title: "Nothing changed.",
      body: "Try again or use another way."
    }
  end

  defp passkey_recovery_notice(:timeout) do
    %{
      tone: :warning,
      title: "We couldn't finish passkey sign-in. Try again or use another way to continue.",
      body: nil
    }
  end

  defp passkey_recovery_notice(:unsupported) do
    %{
      tone: :info,
      title: "Passkeys aren't available in this browser.",
      body:
        "Use your authenticator code, a backup code, or a device/browser that supports passkeys."
    }
  end

  defp passkey_recovery_notice(:generic) do
    %{
      tone: :warning,
      title: "We couldn't finish passkey sign-in. Try again or use another way to continue.",
      body: nil
    }
  end
end
