defmodule ExampleWeb.OrganizationMembersLive do
  @moduledoc """
  Members list + per-row role-change + remove flows for the active organization.

  Route: `GET /organizations/:org/members` (owner/admin only — enforced by the
  `:org_scoped` pipeline + `Sigra.Plug.RequireMembership role: [:owner, :admin]`).

  Phase 16 Plan 05 — implements ORG-UX-06 / ORG-UX-07 / ORG-UX-08 and decisions
  D-14, D-15, D-16, D-17, D-18, D-19, D-20, D-22, D-23. Generated by
  `mix sigra.install --live`; this file is host-owned, customize freely.

  ## Architecture

    * Two LiveView streams: `@streams.members` (populated on mount) and the
      Phase 17 seam `pending-invitations-section` (currently an empty-state
      card with a HEEx comment marker).
    * Row mutations (role change, remove) funnel through native `<dialog
      class="modal">` confirmation modals. The modal stays open when the
      server returns `{:error, :last_owner}` and renders an inline error above
      the form (D-20).
    * Removal relies on the Plan 01 `remove_member/2` library Multi, which
      purges `user_sessions` rows scoped to the removed user + this org inside
      the same transaction (D-21 / SC-4 force-logout).
    * Pagination is `LIMIT 100` + "Load more" via `stream_insert(..., at: -1)`
      (D-22). Flop / sortable columns are a v1.2 concern.

  ## Phase 17 seam

  The `pending-invitations-section` `<section>` below the members table
  currently renders an empty-state card. Phase 17 will replace the card body
  with a populated `@streams.pending_invitations` and add an "Invite member"
  action above the table. Look for the `Phase 17 fills this section` HEEx
  comment to find the fill-in point.
  """
  use ExampleWeb, :live_view

  alias Example.Organizations

  @page_size 100

  @impl true
  def mount(_params, _session, socket) do
    scope = socket.assigns.current_scope

    # Phase 92 / B2B-02 (WR-2-05 fix): read the host's role taxonomy from
    # `Organizations.__sigra_org_config__()` so the LV stays in lockstep
    # with `use Sigra.Organizations, roles: [...]` instead of hardcoding
    # `[:owner, :admin, :member]` in helpers and select options.
    config = Organizations.__sigra_org_config__()
    available_roles = config.roles
    invitation_admin_roles = config.invitation_admin_roles
    default_invite_role = List.last(available_roles) |> to_string()

    rows = Organizations.list_members_with_activity(scope, limit: @page_size, offset: 0)
    total = Organizations.count_members(scope)
    decorated = decorate_rows(rows)

    pending = Organizations.list_pending_invitations(scope.active_organization)

    {:ok,
     socket
     |> stream(:members, decorated)
     |> assign(:total_count, total)
     |> assign(:offset, length(decorated))
     |> assign(:has_more, length(decorated) < total)
     |> assign(:pending_action, nil)
     |> assign(:role_modal_error, nil)
     |> assign(:remove_modal_error, nil)
     |> assign(:available_roles, available_roles)
     |> assign(:invitation_admin_roles, invitation_admin_roles)
     |> assign(
       :invite_form,
       to_form(%{"email" => "", "role" => default_invite_role}, as: :invitation)
     )
     |> assign(:revoking_invitation, nil)
     |> stream(:pending_invitations, pending)
     |> assign(:pending_count, length(pending))}
  end

  # ──────────────────────────────────────────────────────────────────────────
  # Event handlers
  # ──────────────────────────────────────────────────────────────────────────

  @impl true
  def handle_event("load_more", _params, socket) do
    scope = socket.assigns.current_scope

    next =
      Organizations.list_members_with_activity(scope,
        limit: @page_size,
        offset: socket.assigns.offset
      )

    decorated = decorate_rows(next)

    new_offset = socket.assigns.offset + length(decorated)

    socket =
      Enum.reduce(decorated, socket, fn member, acc ->
        stream_insert(acc, :members, member, at: -1)
      end)

    {:noreply,
     socket
     |> assign(:offset, new_offset)
     |> assign(:has_more, new_offset < socket.assigns.total_count)}
  end

  def handle_event("open_role_modal", %{"id" => id}, socket) do
    case find_streamed_member(socket, id) do
      nil ->
        {:noreply, socket}

      member ->
        {:noreply,
         socket
         |> assign(:pending_action, {:role, member})
         |> assign(:role_modal_error, nil)
         |> push_event("open-modal", %{id: "confirm-role-modal"})}
    end
  end

  def handle_event("open_remove_modal", %{"id" => id}, socket) do
    case find_streamed_member(socket, id) do
      nil ->
        {:noreply, socket}

      member ->
        {:noreply,
         socket
         |> assign(:pending_action, {:remove, member})
         |> assign(:remove_modal_error, nil)
         |> push_event("open-modal", %{id: "confirm-remove-modal"})}
    end
  end

  def handle_event("cancel_action", _params, socket) do
    {:noreply,
     socket
     |> assign(:pending_action, nil)
     |> assign(:role_modal_error, nil)
     |> assign(:remove_modal_error, nil)
     |> push_event("close-modal", %{id: "confirm-role-modal"})
     |> push_event("close-modal", %{id: "confirm-remove-modal"})}
  end

  def handle_event("change_role", %{"role" => role_str}, socket) do
    {:role, member} = socket.assigns.pending_action
    scope = socket.assigns.current_scope
    available_roles = socket.assigns.available_roles

    with {:ok, new_role} <- safe_role_atom(role_str, available_roles),
         {:ok, updated} <- Organizations.change_member_role(scope, member, new_role) do
      updated_decorated =
        updated
        |> Map.put(:__last_active__, Map.get(member, :__last_active__))

      {:noreply,
       socket
       |> stream_insert(:members, updated_decorated)
       |> assign(:pending_action, nil)
       |> assign(:role_modal_error, nil)
       |> put_flash(:info, "Role updated.")
       |> push_event("close-modal", %{id: "confirm-role-modal"})}
    else
      {:error, :last_owner} ->
        # D-20: modal stays open, inline error with exact UI-SPEC copy.
        {:noreply,
         assign(
           socket,
           :role_modal_error,
           "Cannot demote the last owner. Promote another member to owner first."
         )}

      {:error, :invalid_role} ->
        {:noreply, assign(socket, :role_modal_error, "Invalid role.")}

      {:error, _changeset} ->
        {:noreply,
         assign(
           socket,
           :role_modal_error,
           "Could not update role. Please try again."
         )}
    end
  end

  # ── Phase 17: Invite member flow ────────────────────────────────────────

  def handle_event("open_invite_modal", _params, socket) do
    default_invite_role = List.last(socket.assigns.available_roles) |> to_string()

    {:noreply,
     socket
     |> assign(
       :invite_form,
       to_form(%{"email" => "", "role" => default_invite_role}, as: :invitation)
     )
     |> push_event("open-modal", %{id: "invite-member-modal"})}
  end

  def handle_event("cancel_invite", _params, socket) do
    {:noreply, push_event(socket, "close-modal", %{id: "invite-member-modal"})}
  end

  def handle_event("invite_member", %{"invitation" => params}, socket) do
    scope = socket.assigns.current_scope
    org = scope.active_organization
    available_roles = socket.assigns.available_roles

    attrs = %{
      actor: scope,
      organization_id: org.id,
      email: params["email"],
      role: safe_invite_role(params["role"], available_roles),
      invited_by_id: scope.user.id
    }

    case Organizations.create_invitation(attrs) do
      {:ok, invitation} ->
        default_role = List.last(available_roles) |> to_string()

        {:noreply,
         socket
         |> put_flash(:info, "Invitation sent to #{invitation.email}.")
         |> stream_insert(:pending_invitations, invitation, at: 0)
         |> update(:pending_count, &(&1 + 1))
         |> assign(
           :invite_form,
           to_form(%{"email" => "", "role" => default_role}, as: :invitation)
         )
         |> push_event("close-modal", %{id: "invite-member-modal"})}

      {:error, %Ecto.Changeset{} = cs} ->
        {:noreply, assign(socket, :invite_form, to_form(cs, as: :invitation))}

      {:error, :already_member} ->
        form =
          to_form(
            %{"email" => params["email"], "role" => params["role"]},
            as: :invitation,
            errors: [
              email:
                {"#{params["email"]} is already a member of this organization.", []}
            ]
          )

        {:noreply, assign(socket, :invite_form, form)}

      {:error, :rate_limited_user} ->
        {:noreply,
         socket
         |> put_flash(:error, "You have invited too many people today. Try again tomorrow.")
         |> push_event("close-modal", %{id: "invite-member-modal"})}

      {:error, :rate_limited_org} ->
        {:noreply,
         socket
         |> put_flash(
           :error,
           "This organization has reached its daily invitation limit. Try again tomorrow."
         )
         |> push_event("close-modal", %{id: "invite-member-modal"})}

      {:error, :unauthorized} ->
        {:noreply,
         put_flash(socket, :error, "You do not have permission to invite members.")}
    end
  end

  # ── Phase 17: Revoke invitation flow ────────────────────────────────────

  def handle_event("open_revoke_modal", %{"id" => id}, socket) do
    case find_pending_invitation(socket, id) do
      nil ->
        {:noreply, put_flash(socket, :error, "Invitation not found.")}

      invitation ->
        {:noreply,
         socket
         |> assign(:revoking_invitation, invitation)
         |> push_event("open-modal", %{id: "revoke-invitation-modal"})}
    end
  end

  def handle_event("cancel_revoke", _params, socket) do
    {:noreply,
     socket
     |> assign(:revoking_invitation, nil)
     |> push_event("close-modal", %{id: "revoke-invitation-modal"})}
  end

  def handle_event("confirm_revoke", %{"id" => id}, socket) do
    case Organizations.revoke_invitation(id, socket.assigns.current_scope) do
      {:ok, invitation} ->
        {:noreply,
         socket
         |> put_flash(:info, "Invitation for #{invitation.email} revoked.")
         |> stream_delete(:pending_invitations, invitation)
         |> update(:pending_count, &max(&1 - 1, 0))
         |> assign(:revoking_invitation, nil)
         |> push_event("close-modal", %{id: "revoke-invitation-modal"})}

      {:error, :not_pending} ->
        {:noreply,
         socket
         |> put_flash(
           :error,
           "This invitation has already been accepted and cannot be revoked."
         )
         |> assign(:revoking_invitation, nil)
         |> push_event("close-modal", %{id: "revoke-invitation-modal"})}

      {:error, :unauthorized} ->
        {:noreply,
         put_flash(socket, :error, "You do not have permission to revoke invitations.")}

      {:error, :not_found} ->
        {:noreply, put_flash(socket, :error, "Invitation not found.")}
    end
  end

  def handle_event("remove_member", _params, socket) do
    {:remove, member} = socket.assigns.pending_action
    scope = socket.assigns.current_scope
    org_name = scope.active_organization.name
    email = member.user.email

    case Organizations.remove_member(scope, member) do
      {:ok, _removed} ->
        {:noreply,
         socket
         |> stream_delete(:members, member)
         |> assign(:pending_action, nil)
         |> assign(:remove_modal_error, nil)
         |> assign(:total_count, max(socket.assigns.total_count - 1, 0))
         |> put_flash(:info, "Removed #{email} from #{org_name}.")
         |> push_event("close-modal", %{id: "confirm-remove-modal"})}

      {:error, :last_owner} ->
        # D-20: modal stays open, inline error with exact UI-SPEC copy.
        {:noreply,
         assign(
           socket,
           :remove_modal_error,
           "Cannot remove the last owner. Promote another member to owner first."
         )}
    end
  end

  # ──────────────────────────────────────────────────────────────────────────
  # Render
  # ──────────────────────────────────────────────────────────────────────────

  @impl true
  def render(assigns) do
    ~H"""
    <.header>
      Members ({@total_count})
      <:actions>
        <.button
          :if={can_manage_members?(@current_scope, @invitation_admin_roles)}
          type="button"
          phx-click="open_invite_modal"
          id="invite-member-button"
        >
          Invite member
        </.button>
        <.button
          :if={not can_manage_members?(@current_scope, @invitation_admin_roles)}
          disabled
          aria-disabled="true"
          title="Only owners and admins can invite members"
        >
          Invite member
        </.button>
      </:actions>
    </.header>

    <section id="members-section" class="overflow-x-auto">
      <.table id="members-table" rows={@streams.members}>
        <:col :let={{_dom_id, m}} label="Email">{m.user.email}</:col>
        <:col :let={{_dom_id, m}} label="Role">
          <span class={["badge", role_badge_class(m.role)]}>{humanize_role(m.role)}</span>
        </:col>
        <:col :let={{_dom_id, _m}} label="Status">
          <span class="badge badge-ghost">Active</span>
        </:col>
        <:col :let={{_dom_id, m}} label="Joined">{relative_time(m.inserted_at)}</:col>
        <:col :let={{_dom_id, m}} label="Last active">
          {if m.__last_active__, do: relative_time(m.__last_active__), else: "Never"}
        </:col>
        <:action :let={{_dom_id, m}}>
          <details class="dropdown dropdown-end">
            <summary class="btn btn-ghost btn-xs">
              <.icon name="hero-ellipsis-horizontal" class="size-4" />
              <span class="sr-only">Member actions</span>
            </summary>
            <ul class="menu dropdown-content bg-base-100 rounded-box z-10 w-40 p-1 shadow">
              <li>
                <button type="button" phx-click="open_role_modal" phx-value-id={m.id}>
                  Change role
                </button>
              </li>
              <li>
                <button
                  type="button"
                  class="text-error"
                  phx-click="open_remove_modal"
                  phx-value-id={m.id}
                >
                  Remove
                </button>
              </li>
            </ul>
          </details>
        </:action>
      </.table>

      <.button :if={@has_more} phx-click="load_more" class="mt-4">
        Load more
      </.button>
    </section>

    <section id="pending-invitations-section" class="mt-8">
      <.header>
        Pending invitations ({@pending_count})
      </.header>

      <%= if @pending_count == 0 do %>
        <div class="card bg-base-200 p-6 text-center text-sm text-base-content/70">
          No pending invitations. Click <strong>Invite member</strong>
          above to invite someone.
        </div>
      <% else %>
        <div class="overflow-x-auto">
          <.table id="pending-invitations-table" rows={@streams.pending_invitations}>
            <:col :let={{_dom_id, inv}} label="Email">{inv.email}</:col>
            <:col :let={{_dom_id, inv}} label="Role">
              <span class={["badge badge-sm", role_badge_class(inv.role)]}>
                {humanize_role(inv.role)}
              </span>
            </:col>
            <:col :let={{_dom_id, inv}} label="Invited by">
              {invited_by_email(inv)}
            </:col>
            <:col :let={{_dom_id, inv}} label="Expires">
              <span class="text-sm text-base-content/70">
                {invitation_expires_relative(inv.expires_at)}
              </span>
            </:col>
            <:action :let={{_dom_id, inv}}>
              <button
                :if={can_manage_members?(@current_scope, @invitation_admin_roles)}
                type="button"
                class="btn btn-ghost btn-xs text-error"
                phx-click="open_revoke_modal"
                phx-value-id={inv.id}
                aria-label={"Revoke invitation for #{inv.email}"}
              >
                Revoke
              </button>
            </:action>
          </.table>
        </div>
      <% end %>
    </section>

    <dialog id="invite-member-modal" class="modal" phx-hook="DialogModal">
      <div class="modal-box">
        <h3 class="text-lg font-semibold">Invite a member</h3>
        <p class="text-sm text-base-content/70 mt-2">
          Send an invitation to join {@current_scope.active_organization.name}.
          They will receive an email with a secure accept link.
        </p>

        <.form for={@invite_form} phx-submit="invite_member" class="mt-4 space-y-4">
          <label class="form-control w-full">
            <span class="label-text">Email address</span>
            <input
              type="email"
              name="invitation[email]"
              value={@invite_form[:email].value}
              placeholder="teammate@example.com"
              required
              autocomplete="off"
              phx-debounce="300"
              class="input input-bordered w-full"
            />
          </label>

          <label class="form-control w-full">
            <span class="label-text">Role</span>
            <select
              name="invitation[role]"
              class="select select-bordered w-full"
            >
              <option :for={role <- @available_roles} value={Atom.to_string(role)}>
                {humanize_role(role)}
              </option>
            </select>
          </label>

          <div class="modal-action">
            <button type="button" class="btn btn-ghost" phx-click="cancel_invite">
              Cancel
            </button>
            <button
              type="submit"
              class="btn btn-primary"
              phx-disable-with="Sending..."
            >
              Send invitation
            </button>
          </div>
        </.form>
      </div>
      <form method="dialog" class="modal-backdrop"><button>close</button></form>
    </dialog>

    <dialog id="revoke-invitation-modal" class="modal" phx-hook="DialogModal">
      <div class="modal-box">
        <h3 class="text-lg font-semibold">Revoke invitation?</h3>

        <%= if @revoking_invitation do %>
          <p class="text-sm mt-2">
            Revoke the invitation for
            <strong>{@revoking_invitation.email}</strong>? They will no longer be able to join
            <strong>{@current_scope.active_organization.name}</strong>
            with this link. You can re-invite them later.
          </p>
        <% end %>

        <div class="modal-action">
          <button type="button" class="btn btn-ghost" phx-click="cancel_revoke">
            Cancel
          </button>
          <button
            type="button"
            class="btn btn-error"
            phx-click="confirm_revoke"
            phx-value-id={@revoking_invitation && @revoking_invitation.id}
            phx-disable-with="Revoking..."
          >
            Revoke invitation
          </button>
        </div>
      </div>
      <form method="dialog" class="modal-backdrop"><button>close</button></form>
    </dialog>

    <dialog id="confirm-role-modal" class="modal" phx-hook="DialogModal">
      <%= if match?({:role, _}, @pending_action) do %>
        <% {:role, m} = @pending_action %>
        <div class="modal-box">
          <h3 class="text-lg font-semibold">Change {m.user.email}'s role?</h3>

          <%= if @role_modal_error do %>
            <p class="text-error mt-2 text-sm" role="alert">{@role_modal_error}</p>
          <% end %>

          <form phx-submit="change_role" class="mt-4 space-y-4">
            <label class="form-control w-full">
              <span class="label-text">New role</span>
              <select name="role" class="select select-bordered w-full">
                <option
                  :for={role <- @available_roles}
                  value={Atom.to_string(role)}
                  selected={m.role == role}
                >
                  {humanize_role(role)}
                </option>
              </select>
            </label>

            <div class="modal-action">
              <button type="submit" class="btn btn-primary">Change role</button>
              <button type="button" class="btn btn-ghost" phx-click="cancel_action">
                Cancel
              </button>
            </div>
          </form>
        </div>
        <form method="dialog" class="modal-backdrop"><button>close</button></form>
      <% end %>
    </dialog>

    <dialog id="confirm-remove-modal" class="modal" phx-hook="DialogModal">
      <%= if match?({:remove, _}, @pending_action) do %>
        <% {:remove, m} = @pending_action %>
        <div class="modal-box">
          <h3 class="text-lg font-semibold">
            Remove {m.user.email} from {@current_scope.active_organization.name}?
          </h3>
          <p class="py-2 text-sm">
            {m.user.email} will be signed out of this organization immediately. You can re-invite them later.
          </p>

          <%= if @remove_modal_error do %>
            <p class="text-error mt-2 text-sm" role="alert">{@remove_modal_error}</p>
          <% end %>

          <form phx-submit="remove_member">
            <div class="modal-action">
              <button type="submit" class="btn btn-error">Remove member</button>
              <button type="button" class="btn btn-ghost" phx-click="cancel_action">
                Cancel
              </button>
            </div>
          </form>
        </div>
        <form method="dialog" class="modal-backdrop"><button>close</button></form>
      <% end %>
    </dialog>
    """
  end

  # ──────────────────────────────────────────────────────────────────────────
  # Helpers — customize freely
  # ──────────────────────────────────────────────────────────────────────────

  # Decorates raw `{membership, last_active_at}` tuples from
  # `Organizations.list_members_with_activity/2` into flat structs the stream
  # can key by membership id and the template can render without nested
  # destructuring.
  defp decorate_rows(rows) do
    Enum.map(rows, fn
      {membership, last_active} ->
        Map.put(membership, :__last_active__, last_active)

      %_{} = membership ->
        Map.put(membership, :__last_active__, nil)
    end)
  end

  # Looks up a streamed member by id. Because the stream is seeded from a
  # scope-filtered library query, a stranger membership id would have no
  # corresponding LiveView socket entry and this returns nil (T-16-05-03).
  # The Plan 01 library also scopes mutations by organization_id so a foreign
  # id admitted here could not mutate cross-tenant rows.
  defp find_streamed_member(socket, id) do
    # Streams don't expose their source list directly; we stash the decorated
    # list in `socket.assigns[:_members_by_id]` on first use. For the Phase 16
    # scope we refetch from the library on demand — it's a single indexed
    # lookup and avoids duplicating state with the stream.
    scope = socket.assigns.current_scope

    scope
    |> Organizations.list_members_with_activity(limit: 1_000, offset: 0)
    |> decorate_rows()
    |> Enum.find(fn m -> to_string(m.id) == to_string(id) end)
  end

  # ── Phase 17 / Phase 92 helpers ──────────────────────────────────────────

  # Phase 92 / B2B-02: "can this scope manage members?" reads from the
  # host-configured `:invitation_admin_roles` instead of the legacy
  # `[:owner, :admin]` literal. Stays in lockstep with whatever the host
  # declares in `use Sigra.Organizations`.
  defp can_manage_members?(%{membership: %{role: role}}, invitation_admin_roles)
       when is_list(invitation_admin_roles) do
    role in invitation_admin_roles
  end

  defp can_manage_members?(_scope, _roles), do: false

  # Phase 92 / B2B-02 (WR-2-05 fix): casts a form-submitted role string
  # to an atom, validating it against the host's configured `:roles`
  # universe. Falls back to the last configured role (the lowest-
  # privilege convention in the recipe) when the input is missing or
  # unrecognized — keeps the form forgiving while never producing a
  # role atom outside the host taxonomy.
  defp safe_invite_role(role_str, available_roles) when is_list(available_roles) do
    case safe_role_atom(role_str, available_roles) do
      {:ok, atom} -> atom
      {:error, :invalid_role} -> List.last(available_roles)
    end
  end

  defp find_pending_invitation(socket, id) do
    org = socket.assigns.current_scope.active_organization

    org
    |> Organizations.list_pending_invitations()
    |> Enum.find(fn inv -> to_string(inv.id) == to_string(id) end)
  end

  defp invited_by_email(%{invited_by: %{email: email}}) when is_binary(email), do: email
  defp invited_by_email(_), do: "—"

  defp invitation_expires_relative(%DateTime{} = dt) do
    seconds = DateTime.diff(dt, DateTime.utc_now(), :second)

    cond do
      seconds <= 0 -> "expired"
      seconds < 3600 -> "in #{div(seconds, 60)} minutes"
      seconds < 86_400 -> "in #{div(seconds, 3600)} hours"
      true -> "in #{div(seconds, 86_400)} days"
    end
  end

  defp invitation_expires_relative(_), do: "—"

  # Phase 92 / B2B-02 (WR-2-05 fix): casts a form-submitted role string
  # to an atom and validates it against the host's configured roles.
  # Uses `String.to_existing_atom/1` for safety — host role atoms enter
  # the BEAM at compile time via `use Sigra.Organizations, roles: [...]`,
  # so any legitimate role string maps to an existing atom. Unknown or
  # non-host atoms return `{:error, :invalid_role}`.
  defp safe_role_atom(role_str, available_roles)
       when is_binary(role_str) and is_list(available_roles) do
    atom = String.to_existing_atom(role_str)

    if atom in available_roles do
      {:ok, atom}
    else
      {:error, :invalid_role}
    end
  rescue
    ArgumentError -> {:error, :invalid_role}
  end

  defp safe_role_atom(_other, _available_roles), do: {:error, :invalid_role}

  # UI-SPEC §Color — role badge variants. Phase 92 / B2B-02 (WR-2-05
  # fix): hosts customizing the role taxonomy should also customize
  # this clause list. The fallback `_ -> "badge-ghost"` keeps unknown
  # atoms rendering safely without the LV crashing.
  #
  # Edit these clauses to match your `roles:` taxonomy. The starter is:
  #
  #     :owner  -> badge-primary
  #     :admin  -> badge-neutral
  #     :member -> badge-ghost
  defp role_badge_class(:owner), do: "badge-primary"
  defp role_badge_class(:admin), do: "badge-neutral"
  defp role_badge_class(:member), do: "badge-ghost"
  defp role_badge_class(_other), do: "badge-ghost"

  # Phase 92 / B2B-02: humanize falls through to a generic
  # capitalize-and-replace-underscores formatter so any host role atom
  # (e.g. `:tenant_lead` -> "Tenant Lead") renders without explicit
  # clauses. Edit the explicit clauses to match your taxonomy if you
  # want non-default casing.
  defp humanize_role(role) when is_atom(role) and not is_nil(role) do
    role
    |> Atom.to_string()
    |> String.replace("_", " ")
    |> String.split(" ")
    |> Enum.map_join(" ", &String.capitalize/1)
  end

  defp humanize_role(other), do: other |> to_string() |> String.capitalize()

  # Lightweight relative-time formatter — hosts commonly replace this with
  # their own `Cldr` / `Timex` helper. Kept inline to keep the template
  # self-contained with zero new deps.
  defp relative_time(nil), do: "Never"

  defp relative_time(%DateTime{} = dt) do
    diff = DateTime.diff(DateTime.utc_now(), dt, :second)
    format_relative(diff)
  end

  defp relative_time(%NaiveDateTime{} = ndt) do
    ndt
    |> DateTime.from_naive!("Etc/UTC")
    |> relative_time()
  end

  defp format_relative(diff) when diff < 60, do: "just now"
  defp format_relative(diff) when diff < 3_600, do: "#{div(diff, 60)} minutes ago"
  defp format_relative(diff) when diff < 86_400, do: "#{div(diff, 3_600)} hours ago"
  defp format_relative(diff) when diff < 2_592_000, do: "#{div(diff, 86_400)} days ago"
  defp format_relative(diff), do: "#{div(diff, 2_592_000)} months ago"
end
