defmodule ExampleWeb.OrganizationServiceAccountsLive do
  @moduledoc """
  Service-account management LiveView — index list and detail surfaces on a
  single module with `:index` and `:show` live_actions.

  Route: `GET /organizations/:org/service-accounts` (owner/admin only)
         `GET /organizations/:org/service-accounts/:id` (owner/admin only)

  Generated by `mix sigra.install --organizations --jwt`. This file is
  host-owned, customize freely.

  ## Architecture

    * `:index` — paginated list of all service accounts in the active org,
      with an empty-state card when none exist yet. A row-action overflow
      menu on each row exposes "View" (detail route) and "Revoke service
      account" (opens revoke-SA modal).

    * `:show` — detail surface for a single SA: metadata section,
      credentials table with per-credential revoke, "Create credential"
      CTA, and a Danger Zone for revoking the entire SA.

    * Five modals (all using the `phx-hook="DialogModal"` pattern):
      1. `create-sa-modal`          — Create service account (sudo)
      2. `create-credential-modal`  — Create credential (sudo)
      3. `credential-disclosure-modal` — One-time secret reveal (auto-opens
         after successful create-credential)
      4. `revoke-sa-modal`          — Revoke SA (sudo + typed-confirm)
      5. `revoke-credential-modal`  — Revoke credential (sudo)

    * All destructive/high-trust actions carry inline `current_password`
      re-verification (D-93-17). Wrong password keeps the modal open and
      renders the verbatim copy "That password is incorrect."

    * The credential disclosure modal clears `@disclosed_credential` on
      explicit "I've saved this credential — close" click — the secret is
      never re-shown from DB (T-93-01 mitigation lock).

    * Copy buttons in the disclosure modal use `phx-hook="CopyToClipboard"`.
      NO bare HTML `onclick` fallback (navigator.clipboard.writeText) is used
      (UI-SPEC revision 1 §Component Inventory lock).
  """

  use ExampleWeb, :live_view

  import Ecto.Query, warn: false

  alias Example.Organizations

  @page_size 50

  @impl true
  def mount(_params, _session, socket) do
    {:ok,
     socket
     |> assign(:page_title, "Service accounts")
     |> assign(:total_count, 0)
     |> assign(:has_more, false)
     |> assign(:service_accounts, [])
     |> assign(:offset, 0)
     # Detail page assigns
     |> assign(:service_account, nil)
     |> assign(:credentials, [])
     |> assign(:credentials_count, 0)
     # Modal open/close state
     |> assign(:create_sa_modal_open?, false)
     |> assign(:create_credential_modal_open?, false)
     |> assign(:revoking_sa, nil)
     |> assign(:revoking_credential, nil)
     |> assign(:disclosed_credential, nil)
     # Inline form errors per modal
     |> assign(:create_sa_error, nil)
     |> assign(:create_credential_error, nil)
     |> assign(:revoke_sa_error, nil)
     |> assign(:revoke_credential_error, nil)}
  end

  @impl true
  def handle_params(params, _uri, socket) do
    scope = socket.assigns.current_scope
    org = scope && scope.active_organization
    config = Organizations.__sigra_org_config__()
    available_roles = config.roles
    invitation_admin_roles = config.invitation_admin_roles

    socket = assign(socket, :available_roles, available_roles)

    if not is_admin?(scope, invitation_admin_roles) do
      {:noreply,
       socket
       |> put_flash(:error, "You don't have permission to manage service accounts.")
       |> push_navigate(to: ~p"/organizations/#{org.slug}/members")}
    else
      case socket.assigns.live_action do
        :index ->
          sa_list = list_service_accounts(org.id, @page_size, 0)
          total = count_service_accounts(org.id)

          {:noreply,
           socket
           |> assign(:service_accounts, sa_list)
           |> assign(:total_count, total)
           |> assign(:has_more, length(sa_list) < total)
           |> assign(:offset, length(sa_list))
           |> assign(:service_account, nil)
           |> assign(:credentials, [])
           |> assign(:credentials_count, 0)}

        :show ->
          sa = load_service_account(org.id, params["id"])

          if is_nil(sa) do
            {:noreply,
             socket
             |> put_flash(:error, "Service account not found.")
             |> push_navigate(to: ~p"/organizations/#{org.slug}/service-accounts")}
          else
            creds = load_credentials(sa.id)

            {:noreply,
             socket
             |> assign(:service_account, sa)
             |> assign(:credentials, creds)
             |> assign(:credentials_count, length(creds))}
          end
      end
    end
  end

  # ──────────────────────────────────────────────────────────────────────────
  # Event handlers
  # ──────────────────────────────────────────────────────────────────────────

  @impl true
  def handle_event("open_create_sa_modal", _params, socket) do
    {:noreply,
     socket
     |> assign(:create_sa_modal_open?, true)
     |> assign(:create_sa_error, nil)
     |> push_event("open-modal", %{id: "create-sa-modal"})}
  end

  def handle_event("cancel_create_sa", _params, socket) do
    {:noreply,
     socket
     |> assign(:create_sa_modal_open?, false)
     |> assign(:create_sa_error, nil)
     |> push_event("close-modal", %{id: "create-sa-modal"})}
  end

  def handle_event("create_service_account", %{"service_account" => params, "current_password" => pw}, socket) do
    scope = socket.assigns.current_scope
    org = scope.active_organization
    config = sigra_config()

    if not valid_password?(scope.user, pw) do
      {:noreply, assign(socket, :create_sa_error, "That password is incorrect.")}
    else
      scopes = parse_scopes(Map.get(params, "scopes", ""))
      role = nil_if_blank(Map.get(params, "role"))

      attrs = %{
        name: Map.get(params, "name"),
        scopes: scopes,
        role: role,
        organization_id: org.id,
        created_by_user_id: scope.user.id
      }

      case Sigra.ServiceAccounts.create(config, scope, attrs) do
        {:ok, sa} ->
          {:noreply,
           socket
           |> assign(:create_sa_modal_open?, false)
           |> assign(:create_sa_error, nil)
           |> put_flash(:info, "Service account created. Issue a credential to start using it.")
           |> push_navigate(to: ~p"/organizations/#{org.slug}/service-accounts/#{sa.id}")
           |> push_event("close-modal", %{id: "create-sa-modal"})}

        {:error, %Ecto.Changeset{} = changeset} ->
          msg = changeset_error_message(changeset)
          {:noreply, assign(socket, :create_sa_error, msg)}

        {:error, :service_account_aborted} ->
          {:noreply,
           assign(socket, :create_sa_error,
             "Something went wrong. Try again in a moment, or check the server logs if the problem persists."
           )}
      end
    end
  end

  def handle_event("open_create_credential_modal", _params, socket) do
    {:noreply,
     socket
     |> assign(:create_credential_modal_open?, true)
     |> assign(:create_credential_error, nil)
     |> push_event("open-modal", %{id: "create-credential-modal"})}
  end

  def handle_event("cancel_create_credential", _params, socket) do
    {:noreply,
     socket
     |> assign(:create_credential_modal_open?, false)
     |> assign(:create_credential_error, nil)
     |> push_event("close-modal", %{id: "create-credential-modal"})}
  end

  def handle_event("create_credential", %{"credential" => params, "current_password" => pw}, socket) do
    scope = socket.assigns.current_scope
    sa = socket.assigns.service_account
    config = sigra_config()

    if not valid_password?(scope.user, pw) do
      {:noreply, assign(socket, :create_credential_error, "That password is incorrect.")}
    else
      expires_at = parse_expires_at(Map.get(params, "expires_at"))

      if not is_nil(expires_at) and DateTime.compare(expires_at, DateTime.utc_now()) == :lt do
        {:noreply,
         assign(socket, :create_credential_error, "Expiration must be in the future.")}
      else
        attrs = %{expires_at: expires_at}

        case Sigra.ServiceAccounts.create_credential(config, scope, sa, attrs) do
          {:ok, cred, plaintext_secret} ->
            creds = load_credentials(sa.id)

            {:noreply,
             socket
             |> assign(:create_credential_modal_open?, false)
             |> assign(:create_credential_error, nil)
             |> assign(:credentials, creds)
             |> assign(:credentials_count, length(creds))
             |> assign(:disclosed_credential, %{
               credential_id: cred.id,
               client_id: cred.client_id,
               client_secret: plaintext_secret
             })
             |> push_event("close-modal", %{id: "create-credential-modal"})
             |> push_event("open-modal", %{id: "credential-disclosure-modal"})}

          {:error, %Ecto.Changeset{} = changeset} ->
            msg = changeset_error_message(changeset)
            {:noreply, assign(socket, :create_credential_error, msg)}

          {:error, :service_account_credential_aborted} ->
            {:noreply,
             assign(socket, :create_credential_error,
               "Something went wrong. Try again in a moment, or check the server logs if the problem persists."
             )}
        end
      end
    end
  end

  def handle_event("acknowledge_credential", _params, socket) do
    sa = socket.assigns.service_account
    creds = if sa, do: load_credentials(sa.id), else: []

    {:noreply,
     socket
     |> assign(:disclosed_credential, nil)
     |> assign(:credentials, creds)
     |> assign(:credentials_count, length(creds))
     |> push_event("close-modal", %{id: "credential-disclosure-modal"})}
  end

  def handle_event("open_revoke_sa_modal", %{"id" => id}, socket) do
    sa = find_or_load_sa(socket, id)

    if sa do
      {:noreply,
       socket
       |> assign(:revoking_sa, sa)
       |> assign(:revoke_sa_error, nil)
       |> push_event("open-modal", %{id: "revoke-sa-modal"})}
    else
      {:noreply, socket}
    end
  end

  def handle_event("cancel_revoke_sa", _params, socket) do
    {:noreply,
     socket
     |> assign(:revoking_sa, nil)
     |> assign(:revoke_sa_error, nil)
     |> push_event("close-modal", %{id: "revoke-sa-modal"})}
  end

  def handle_event("revoke_service_account", %{"current_password" => pw, "typed_confirm" => typed}, socket) do
    scope = socket.assigns.current_scope
    sa = socket.assigns.revoking_sa
    config = sigra_config()

    cond do
      not valid_password?(scope.user, pw) ->
        {:noreply, assign(socket, :revoke_sa_error, "That password is incorrect.")}

      typed != sa.name ->
        {:noreply,
         assign(socket, :revoke_sa_error, "Type the service-account name exactly to confirm.")}

      true ->
        case Sigra.ServiceAccounts.revoke(config, scope, sa) do
          {:ok, _revoked} ->
            org = scope.active_organization

            {:noreply,
             socket
             |> assign(:revoking_sa, nil)
             |> assign(:revoke_sa_error, nil)
             |> put_flash(:info, "Service account \"#{sa.name}\" revoked. All live tokens are now invalid.")
             |> push_navigate(to: ~p"/organizations/#{org.slug}/service-accounts")
             |> push_event("close-modal", %{id: "revoke-sa-modal"})}

          {:error, :service_account_aborted} ->
            {:noreply,
             assign(socket, :revoke_sa_error,
               "Something went wrong. Try again in a moment, or check the server logs if the problem persists."
             )}
        end
    end
  end

  def handle_event("open_revoke_credential_modal", %{"id" => id}, socket) do
    cred = find_credential(socket, id)

    if cred do
      {:noreply,
       socket
       |> assign(:revoking_credential, cred)
       |> assign(:revoke_credential_error, nil)
       |> push_event("open-modal", %{id: "revoke-credential-modal"})}
    else
      {:noreply, socket}
    end
  end

  def handle_event("cancel_revoke_credential", _params, socket) do
    {:noreply,
     socket
     |> assign(:revoking_credential, nil)
     |> assign(:revoke_credential_error, nil)
     |> push_event("close-modal", %{id: "revoke-credential-modal"})}
  end

  def handle_event("revoke_credential", %{"current_password" => pw}, socket) do
    scope = socket.assigns.current_scope
    cred = socket.assigns.revoking_credential
    config = sigra_config()

    if not valid_password?(scope.user, pw) do
      {:noreply, assign(socket, :revoke_credential_error, "That password is incorrect.")}
    else
      case Sigra.ServiceAccounts.revoke_credential(config, scope, cred) do
        {:ok, _revoked} ->
          sa = socket.assigns.service_account
          creds = if sa, do: load_credentials(sa.id), else: []

          {:noreply,
           socket
           |> assign(:revoking_credential, nil)
           |> assign(:revoke_credential_error, nil)
           |> assign(:credentials, creds)
           |> assign(:credentials_count, length(creds))
           |> put_flash(:info, "Credential revoked.")
           |> push_event("close-modal", %{id: "revoke-credential-modal"})}

        {:error, :service_account_credential_aborted} ->
          {:noreply,
           assign(socket, :revoke_credential_error,
             "Something went wrong. Try again in a moment, or check the server logs if the problem persists."
           )}
      end
    end
  end

  def handle_event("load_more", _params, socket) do
    scope = socket.assigns.current_scope
    org = scope.active_organization
    new_sas = list_service_accounts(org.id, @page_size, socket.assigns.offset)
    combined = socket.assigns.service_accounts ++ new_sas
    new_offset = socket.assigns.offset + length(new_sas)

    {:noreply,
     socket
     |> assign(:service_accounts, combined)
     |> assign(:offset, new_offset)
     |> assign(:has_more, new_offset < socket.assigns.total_count)}
  end

  # ──────────────────────────────────────────────────────────────────────────
  # Render
  # ──────────────────────────────────────────────────────────────────────────

  @impl true
  def render(assigns) do
    ~H"""
    <Layouts.app
      flash={@flash}
      current_scope={@current_scope}
      user_organizations={@user_organizations}
    >
    <%= case @live_action do %>
      <% :index -> %>
        <%= render_index(assigns) %>
      <% :show -> %>
        <%= if @service_account do %>
          <%= render_detail(assigns) %>
        <% end %>
    <% end %>

    <%= # ── Create SA modal ──────────────────────────────────────────────── %>
    <dialog id="create-sa-modal" class="modal" phx-hook="DialogModal">
      <%= if @create_sa_modal_open? do %>
        <div class="modal-box">
          <h3 class="text-lg font-semibold">Create a service account</h3>
          <p class="text-sm text-base-content/70 mt-2">
            Service accounts are owned by {@current_scope.active_organization.name} and authenticate API requests via the client_credentials grant.
          </p>

          <%= if @create_sa_error do %>
            <p class="text-error mt-2 text-sm" role="alert">{@create_sa_error}</p>
          <% end %>

          <form phx-submit="create_service_account" class="mt-4 space-y-4">
            <label class="form-control w-full">
              <span class="label-text">Name</span>
              <input
                type="text"
                name="service_account[name]"
                placeholder="e.g. CI deployer, Stripe webhook receiver"
                required
                autocomplete="off"
                class="input input-bordered w-full"
              />
            </label>

            <%= if length(@available_roles) > 0 do %>
              <label class="form-control w-full">
                <span class="label-text">Role (optional)</span>
                <select name="service_account[role]" class="select select-bordered w-full">
                  <option value="">No role</option>
                  <option :for={role <- @available_roles} value={Atom.to_string(role)}>
                    {humanize_role(role)}
                  </option>
                </select>
              </label>
            <% end %>

            <label class="form-control w-full">
              <span class="label-text">Scopes</span>
              <input
                type="text"
                name="service_account[scopes]"
                placeholder="deploy:write billing:read"
                autocomplete="off"
                class="input input-bordered w-full"
              />
              <span class="text-sm text-base-content/70 mt-1">
                Space-separated. Hosts define the allowed scopes via :custom_scopes config.
              </span>
            </label>

            <label class="form-control w-full">
              <span class="label-text">Current password</span>
              <input
                type="password"
                name="current_password"
                autocomplete="current-password"
                required
                class="input input-bordered w-full"
              />
            </label>

            <div class="modal-action">
              <button type="button" class="btn btn-ghost" phx-click="cancel_create_sa">
                Cancel
              </button>
              <button type="submit" class="btn btn-primary" phx-disable-with="Creating...">
                Create service account
              </button>
            </div>
          </form>
        </div>
        <form method="dialog" class="modal-backdrop"><button>close</button></form>
      <% end %>
    </dialog>

    <%= # ── Create credential modal ──────────────────────────────────────── %>
    <dialog id="create-credential-modal" class="modal" phx-hook="DialogModal">
      <%= if @create_credential_modal_open? && @service_account do %>
        <div class="modal-box">
          <h3 class="text-lg font-semibold">Create a credential for {@service_account.name}</h3>
          <p class="text-sm text-base-content/70 mt-2">
            You'll see the client ID and client secret exactly once. Save them in your secrets manager before closing.
          </p>

          <%= if @create_credential_error do %>
            <p class="text-error mt-2 text-sm" role="alert">{@create_credential_error}</p>
          <% end %>

          <form phx-submit="create_credential" class="mt-4 space-y-4">
            <label class="form-control w-full">
              <span class="label-text">Expires (optional)</span>
              <input
                type="datetime-local"
                name="credential[expires_at]"
                class="input input-bordered w-full"
              />
              <span class="text-sm text-base-content/70 mt-1">
                Leave blank for no expiration. Recommended: 90 days for production, none for short-lived CI tokens.
              </span>
            </label>

            <label class="form-control w-full">
              <span class="label-text">Current password</span>
              <input
                type="password"
                name="current_password"
                autocomplete="current-password"
                required
                class="input input-bordered w-full"
              />
            </label>

            <div class="modal-action">
              <button type="button" class="btn btn-ghost" phx-click="cancel_create_credential">
                Cancel
              </button>
              <button type="submit" class="btn btn-primary" phx-disable-with="Creating...">
                Create credential
              </button>
            </div>
          </form>
        </div>
        <form method="dialog" class="modal-backdrop"><button>close</button></form>
      <% end %>
    </dialog>

    <%= # ── Credential disclosure modal (shown exactly once — T-93-01) ────── %>
    <dialog id="credential-disclosure-modal" class="modal" phx-hook="DialogModal">
      <%= if @disclosed_credential do %>
        <div class="modal-box">
          <h3 class="text-lg font-semibold">Save your credential now</h3>
          <p class="text-sm text-base-content/70 mt-2">
            This is the only time we'll show the client secret. Sigra stores only a hash — once you close this dialog, the secret is unrecoverable.
          </p>

          <div role="alert" class="alert alert-warning alert-soft mt-4">
            <.icon name="hero-exclamation-triangle" class="w-5 h-5" />
            <span>
              Treat the client secret like a password. Anyone with both values can authenticate as {@service_account.name} until the credential is revoked.
            </span>
          </div>

          <div class="mt-4 space-y-4">
            <div>
              <p class="text-sm text-base-content/70">Client ID</p>
              <code class="block w-full font-mono text-base bg-base-200 p-4 rounded-lg select-all mt-1">
                {@disclosed_credential.client_id}
              </code>
              <button
                type="button"
                phx-hook="CopyToClipboard"
                id={"copy-id-btn-" <> @disclosed_credential.credential_id}
                data-copy-text={@disclosed_credential.client_id}
                class="btn btn-ghost btn-sm mt-2"
              >
                <.icon name="hero-clipboard-document" class="w-4 h-4" />
                <span id={"copy-btn-text-" <> @disclosed_credential.credential_id <> "-id"}>Copy client ID</span>
              </button>
            </div>

            <div>
              <p class="text-sm text-base-content/70">Client Secret</p>
              <code class="block w-full font-mono text-base bg-base-200 p-4 rounded-lg select-all break-all mt-1">
                {@disclosed_credential.client_secret}
              </code>
              <button
                type="button"
                phx-hook="CopyToClipboard"
                id={"copy-secret-btn-" <> @disclosed_credential.credential_id}
                data-copy-text={@disclosed_credential.client_secret}
                class="btn btn-ghost btn-sm mt-2"
              >
                <.icon name="hero-clipboard-document" class="w-4 h-4" />
                <span id={"copy-btn-text-" <> @disclosed_credential.credential_id <> "-secret"}>Copy client secret</span>
              </button>
            </div>
          </div>

          <div class="modal-action">
            <button type="button" class="btn btn-primary" phx-click="acknowledge_credential">
              I've saved this credential — close
            </button>
          </div>
        </div>
      <% end %>
    </dialog>

    <%= # ── Revoke SA modal ───────────────────────────────────────────────── %>
    <dialog id="revoke-sa-modal" class="modal" phx-hook="DialogModal">
      <%= if @revoking_sa do %>
        <div class="modal-box">
          <h3 class="text-lg font-semibold">Revoke {@revoking_sa.name}?</h3>
          <p class="text-sm mt-2">
            Revoking this service account immediately invalidates all live access tokens issued from any of its credentials. Anything authenticating as {@revoking_sa.name} will start receiving 401 Unauthorized on the next request. This cannot be undone.
          </p>

          <%= if @revoke_sa_error do %>
            <p class="text-error mt-2 text-sm" role="alert">{@revoke_sa_error}</p>
          <% end %>

          <form phx-submit="revoke_service_account" class="mt-4 space-y-4">
            <label class="form-control w-full">
              <span class="label-text">Current password</span>
              <input
                type="password"
                name="current_password"
                autocomplete="current-password"
                required
                class="input input-bordered w-full"
              />
            </label>

            <label class="form-control w-full">
              <span class="label-text">Type {@revoking_sa.name} to confirm</span>
              <input
                type="text"
                name="typed_confirm"
                required
                autocomplete="off"
                class="input input-bordered w-full"
              />
            </label>

            <div class="modal-action">
              <button type="button" class="btn btn-ghost" phx-click="cancel_revoke_sa">
                Cancel
              </button>
              <button type="submit" class="btn btn-error" phx-disable-with="Revoking...">
                Revoke service account
              </button>
            </div>
          </form>
        </div>
        <form method="dialog" class="modal-backdrop"><button>close</button></form>
      <% end %>
    </dialog>

    <%= # ── Revoke credential modal ──────────────────────────────────────── %>
    <dialog id="revoke-credential-modal" class="modal" phx-hook="DialogModal">
      <%= if @revoking_credential && @service_account do %>
        <div class="modal-box">
          <h3 class="text-lg font-semibold">Revoke this credential?</h3>
          <p class="text-sm mt-2">
            Revoking just this credential lets {@service_account.name} keep working with its other credentials. Tokens already issued from this credential will fail on next verification. Use this for credential rotation; use "Revoke service account" to break the entire class of tokens.
          </p>
          <p class="mt-2 text-sm">
            <code class="font-mono text-sm">{@revoking_credential.client_id}</code>
          </p>

          <%= if @revoke_credential_error do %>
            <p class="text-error mt-2 text-sm" role="alert">{@revoke_credential_error}</p>
          <% end %>

          <form phx-submit="revoke_credential" class="mt-4 space-y-4">
            <label class="form-control w-full">
              <span class="label-text">Current password</span>
              <input
                type="password"
                name="current_password"
                autocomplete="current-password"
                required
                class="input input-bordered w-full"
              />
            </label>

            <div class="modal-action">
              <button type="button" class="btn btn-ghost" phx-click="cancel_revoke_credential">
                Cancel
              </button>
              <button type="submit" class="btn btn-error">
                Revoke credential
              </button>
            </div>
          </form>
        </div>
        <form method="dialog" class="modal-backdrop"><button>close</button></form>
      <% end %>
    </dialog>
    </Layouts.app>
    """
  end

  # ──────────────────────────────────────────────────────────────────────────
  # Render helpers — index and detail surfaces
  # ──────────────────────────────────────────────────────────────────────────

  defp render_index(assigns) do
    ~H"""
    <.header>
      Service accounts ({@total_count})
      <:subtitle>Issue and revoke org-scoped credentials for API integrations and scheduled jobs.</:subtitle>
      <:actions>
        <.button type="button" phx-click="open_create_sa_modal">
          Create service account
        </.button>
      </:actions>
    </.header>

    <%= if @total_count == 0 do %>
      <div class="card bg-base-200 py-12 px-6 text-center">
        <h2 class="text-lg font-semibold">No service accounts yet</h2>
        <p class="mt-2 text-sm text-base-content/70">
          Service accounts let your CI, internal services, and scheduled jobs authenticate as the organization without using a member's password. Create one to get started.
        </p>
        <div class="mt-4">
          <.button type="button" phx-click="open_create_sa_modal">
            Create service account
          </.button>
        </div>
      </div>
    <% else %>
      <section id="service-accounts-section" class="overflow-x-auto mt-6">
        <.table id="service-accounts-table" rows={@service_accounts}>
          <:col :let={sa} label="Name">
            <.link navigate={~p"/organizations/#{@current_scope.active_organization.slug}/service-accounts/#{sa.id}"}>
              {sa.name}
            </.link>
          </:col>
          <:col :let={sa} label="Status">
            <%= if sa.revoked_at do %>
              <span class="badge badge-error">Revoked</span>
            <% else %>
              <span class="badge badge-success">Active</span>
            <% end %>
          </:col>
          <:col :let={sa} label="Created by">
            {created_by_email(sa)}
          </:col>
          <:col :let={sa} label="Last used">
            {relative_time(sa.last_used_at) |> then(fn t -> if t == "Never", do: "Never", else: t end)}
          </:col>
          <:col :let={sa} label="Created">
            {relative_time(sa.inserted_at)}
          </:col>
          <:action :let={sa}>
            <details class="dropdown dropdown-end">
              <summary
                class="btn btn-ghost btn-xs"
                aria-label="Open service account actions"
              >
                <.icon name="hero-ellipsis-horizontal" class="size-4" />
                <span class="sr-only">Open service account actions</span>
              </summary>
              <ul class="menu dropdown-content bg-base-100 rounded-box z-10 w-48 p-1 shadow">
                <li>
                  <.link navigate={~p"/organizations/#{@current_scope.active_organization.slug}/service-accounts/#{sa.id}"}>
                    View
                  </.link>
                </li>
                <%= unless sa.revoked_at do %>
                  <li>
                    <button
                      type="button"
                      class="text-error"
                      phx-click="open_revoke_sa_modal"
                      phx-value-id={sa.id}
                    >
                      Revoke service account
                    </button>
                  </li>
                <% end %>
              </ul>
            </details>
          </:action>
        </.table>

        <.button :if={@has_more} phx-click="load_more" class="mt-4">
          Load more
        </.button>
      </section>
    <% end %>
    """
  end

  defp render_detail(assigns) do
    ~H"""
    <.header>
      {@service_account.name}
      <:subtitle>
        <.link navigate={~p"/organizations/#{@current_scope.active_organization.slug}/service-accounts"} class="inline-flex items-center gap-1 text-sm">
          <.icon name="hero-arrow-left" class="w-4 h-4" />
          Back to service accounts
        </.link>
      </:subtitle>
      <:actions>
        <%= if @service_account.revoked_at do %>
          <span class="badge badge-error">Revoked</span>
        <% else %>
          <span class="badge badge-success">Active</span>
        <% end %>
      </:actions>
    </.header>

    <%= # ── Metadata section ────────────────────────────────────────────── %>
    <section class="bg-base-200 p-6 rounded-lg mt-6">
      <h2 class="text-lg font-semibold">Details</h2>
      <dl class="mt-4 space-y-2 text-sm">
        <div class="flex gap-4">
          <dt class="text-base-content/70 w-32">Created</dt>
          <dd>{relative_time(@service_account.inserted_at)} by {created_by_email(@service_account)}</dd>
        </div>
        <%= if @service_account.role do %>
          <div class="flex gap-4">
            <dt class="text-base-content/70 w-32">Role</dt>
            <dd>{humanize_role(@service_account.role)}</dd>
          </div>
        <% end %>
        <%= if length(@service_account.scopes) > 0 do %>
          <div class="flex gap-4">
            <dt class="text-base-content/70 w-32">Scopes</dt>
            <dd><code class="font-mono text-sm">{Enum.join(@service_account.scopes, " ")}</code></dd>
          </div>
        <% end %>
        <%= if @service_account.last_used_at do %>
          <div class="flex gap-4">
            <dt class="text-base-content/70 w-32">Last used</dt>
            <dd>{relative_time(@service_account.last_used_at)}</dd>
          </div>
        <% end %>
      </dl>
    </section>

    <%= # ── Credentials section ─────────────────────────────────────────── %>
    <section class="mt-8">
      <.header>
        Credentials ({@credentials_count})
        <:subtitle>Rotate credentials by creating a new one alongside the old, deploying it, then revoking the previous credential.</:subtitle>
        <:actions>
          <%= unless @service_account.revoked_at do %>
            <.button type="button" phx-click="open_create_credential_modal">
              Create credential
            </.button>
          <% end %>
        </:actions>
      </.header>

      <%= if @credentials_count == 0 do %>
        <div class="card bg-base-200 p-6 text-center text-sm text-base-content/70 mt-4">
          No credentials yet. Create one to start authenticating as this service account.
        </div>
      <% else %>
        <div class="overflow-x-auto mt-4">
          <.table id="credentials-table" rows={@credentials}>
            <:col :let={cred} label="Client ID">
              <code class="font-mono text-sm">{cred.client_id}</code>
            </:col>
            <:col :let={cred} label="Status">
              <%= if cred.revoked_at do %>
                <span class="badge badge-ghost text-base-content/60">Revoked</span>
              <% else %>
                <span class="badge badge-ghost">Active</span>
              <% end %>
            </:col>
            <:col :let={cred} label="Expires">
              {expires_relative(cred.expires_at)}
            </:col>
            <:col :let={cred} label="Last used">
              {relative_time(cred.last_used_at)}
            </:col>
            <:col :let={cred} label="Created">
              {relative_time(cred.inserted_at)}
            </:col>
            <:action :let={cred}>
              <%= unless cred.revoked_at do %>
                <details class="dropdown dropdown-end">
                  <summary
                    class="btn btn-ghost btn-xs"
                    aria-label="Open credential actions"
                  >
                    <.icon name="hero-ellipsis-horizontal" class="size-4" />
                    <span class="sr-only">Open credential actions</span>
                  </summary>
                  <ul class="menu dropdown-content bg-base-100 rounded-box z-10 w-44 p-1 shadow">
                    <li>
                      <button
                        type="button"
                        class="text-error"
                        phx-click="open_revoke_credential_modal"
                        phx-value-id={cred.id}
                      >
                        Revoke credential
                      </button>
                    </li>
                  </ul>
                </details>
              <% end %>
            </:action>
          </.table>
        </div>
      <% end %>
    </section>

    <%= # ── Danger zone ─────────────────────────────────────────────────── %>
    <%= unless @service_account.revoked_at do %>
      <section class="mt-8 rounded-lg border border-error/40 border-l-4 border-l-error bg-base-100 p-6">
        <h2 class="text-lg font-semibold text-error">Danger zone</h2>
        <p class="text-sm mt-1">
          Revoke this service account. All live tokens issued from any of its credentials are immediately invalidated.
        </p>
        <div class="mt-4">
          <.button
            type="button"
            class="btn btn-error btn-soft"
            phx-click="open_revoke_sa_modal"
            phx-value-id={@service_account.id}
          >
            Revoke service account
          </.button>
        </div>
      </section>
    <% end %>
    """
  end

  # ──────────────────────────────────────────────────────────────────────────
  # Helpers
  # ──────────────────────────────────────────────────────────────────────────

  defp list_service_accounts(org_id, limit, offset) do
    from(sa in Example.Accounts.ServiceAccount,
      where: sa.organization_id == ^org_id,
      order_by: [asc: sa.name],
      limit: ^limit,
      offset: ^offset,
      preload: [:created_by]
    )
    |> Example.Repo.all()
  end

  defp count_service_accounts(org_id) do
    from(sa in Example.Accounts.ServiceAccount,
      where: sa.organization_id == ^org_id,
      select: count(sa.id)
    )
    |> Example.Repo.one()
  end

  defp load_service_account(org_id, id) do
    from(sa in Example.Accounts.ServiceAccount,
      where: sa.id == ^id and sa.organization_id == ^org_id,
      preload: [:created_by]
    )
    |> Example.Repo.one()
  end

  defp load_credentials(sa_id) do
    from(c in Example.Accounts.ServiceAccountCredential,
      where: c.service_account_id == ^sa_id,
      order_by: [desc: c.inserted_at]
    )
    |> Example.Repo.all()
  end

  defp find_or_load_sa(socket, id) do
    case Enum.find(socket.assigns.service_accounts, fn sa -> to_string(sa.id) == to_string(id) end) do
      nil ->
        case socket.assigns.service_account do
          %{id: sa_id} = sa ->
            if to_string(sa_id) == to_string(id), do: sa, else: nil

          nil ->
            nil
        end

      sa ->
        sa
    end
  end

  defp find_credential(socket, id) do
    Enum.find(socket.assigns.credentials, fn c -> to_string(c.id) == to_string(id) end)
  end

  defp is_admin?(%{membership: %{role: role}}, invitation_admin_roles)
       when is_list(invitation_admin_roles) do
    role in invitation_admin_roles
  end

  defp is_admin?(_scope, _roles), do: false

  defp valid_password?(user, password) do
    Sigra.Crypto.verify_password(password, user.hashed_password)
  end

  defp sigra_config do
    Example.Accounts.sigra_config()
  end

  defp parse_scopes(""), do: []
  defp parse_scopes(nil), do: []

  defp parse_scopes(scopes_str) when is_binary(scopes_str) do
    scopes_str
    |> String.split(~r/\s+/, trim: true)
    |> Enum.reject(&(&1 == ""))
  end

  defp nil_if_blank(nil), do: nil
  defp nil_if_blank(""), do: nil
  defp nil_if_blank(v), do: v

  defp parse_expires_at(nil), do: nil
  defp parse_expires_at(""), do: nil

  defp parse_expires_at(dt_str) when is_binary(dt_str) do
    case NaiveDateTime.from_iso8601(dt_str <> ":00") do
      {:ok, ndt} ->
        DateTime.from_naive!(ndt, "Etc/UTC")

      {:error, _} ->
        case NaiveDateTime.from_iso8601(dt_str) do
          {:ok, ndt} -> DateTime.from_naive!(ndt, "Etc/UTC")
          {:error, _} -> nil
        end
    end
  end

  defp changeset_error_message(%Ecto.Changeset{errors: [{_field, {msg, _opts}} | _]}), do: msg
  defp changeset_error_message(%Ecto.Changeset{}), do: "Something went wrong. Try again in a moment, or check the server logs if the problem persists."

  defp created_by_email(%{created_by: %{email: email}}) when is_binary(email), do: email
  defp created_by_email(_), do: "—"

  defp humanize_role(nil), do: ""

  defp humanize_role(role) when is_atom(role) do
    role
    |> Atom.to_string()
    |> String.replace("_", " ")
    |> String.split(" ")
    |> Enum.map_join(" ", &String.capitalize/1)
  end

  defp humanize_role(role) when is_binary(role) do
    role
    |> String.replace("_", " ")
    |> String.split(" ")
    |> Enum.map_join(" ", &String.capitalize/1)
  end

  defp expires_relative(nil), do: "—"

  defp expires_relative(%DateTime{} = dt) do
    seconds = DateTime.diff(dt, DateTime.utc_now(), :second)

    cond do
      seconds <= 0 -> "<span class=\"text-error\">Expired</span>"
      seconds < 3600 -> "in #{div(seconds, 60)} minutes"
      seconds < 86_400 -> "in #{div(seconds, 3600)} hours"
      true -> "in #{div(seconds, 86_400)} days"
    end
  end

  defp expires_relative(%NaiveDateTime{} = ndt) do
    ndt |> DateTime.from_naive!("Etc/UTC") |> expires_relative()
  end

  defp relative_time(nil), do: "Never"

  defp relative_time(%DateTime{} = dt) do
    diff = DateTime.diff(DateTime.utc_now(), dt, :second)
    format_relative(diff)
  end

  defp relative_time(%NaiveDateTime{} = ndt) do
    ndt
    |> DateTime.from_naive!("Etc/UTC")
    |> relative_time()
  end

  defp format_relative(diff) when diff < 60, do: "just now"
  defp format_relative(diff) when diff < 3_600, do: "#{div(diff, 60)} minutes ago"
  defp format_relative(diff) when diff < 86_400, do: "#{div(diff, 3_600)} hours ago"
  defp format_relative(diff) when diff < 2_592_000, do: "#{div(diff, 86_400)} days ago"
  defp format_relative(diff), do: "#{div(diff, 2_592_000)} months ago"
end
