defmodule ExampleWeb.OrganizationMembersLive do
  @moduledoc """
  Members list + per-row role-change + remove flows for the active organization.

  Route: `GET /organizations/:org/members` (owner/admin only — enforced by the
  `:org_scoped` pipeline + `Sigra.Plug.RequireMembership role: [:owner, :admin]`).

  Phase 16 Plan 05 — implements ORG-UX-06 / ORG-UX-07 / ORG-UX-08 and decisions
  D-14, D-15, D-16, D-17, D-18, D-19, D-20, D-22, D-23. Generated by
  `mix sigra.install --live`; this file is host-owned, customize freely.

  ## Architecture

    * Two LiveView streams: `@streams.members` (populated on mount) and the
      Phase 17 seam `pending-invitations-section` (currently an empty-state
      card with a HEEx comment marker).
    * Row mutations (role change, remove) funnel through native `<dialog
      class="modal">` confirmation modals. The modal stays open when the
      server returns `{:error, :last_owner}` and renders an inline error above
      the form (D-20).
    * Removal relies on the Plan 01 `remove_member/2` library Multi, which
      purges `user_sessions` rows scoped to the removed user + this org inside
      the same transaction (D-21 / SC-4 force-logout).
    * Pagination is `LIMIT 100` + "Load more" via `stream_insert(..., at: -1)`
      (D-22). Flop / sortable columns are a v1.2 concern.

  ## Phase 17 seam

  The `pending-invitations-section` `<section>` below the members table
  currently renders an empty-state card. Phase 17 will replace the card body
  with a populated `@streams.pending_invitations` and add an "Invite member"
  action above the table. Look for the `Phase 17 fills this section` HEEx
  comment to find the fill-in point.
  """
  use ExampleWeb, :live_view

  alias Example.Organizations

  @page_size 100

  @impl true
  def mount(_params, _session, socket) do
    scope = socket.assigns.current_scope

    rows = Organizations.list_members_with_activity(scope, limit: @page_size, offset: 0)
    total = Organizations.count_members(scope)
    decorated = decorate_rows(rows)

    {:ok,
     socket
     |> stream(:members, decorated)
     |> assign(:total_count, total)
     |> assign(:offset, length(decorated))
     |> assign(:has_more, length(decorated) < total)
     |> assign(:pending_action, nil)
     |> assign(:role_modal_error, nil)
     |> assign(:remove_modal_error, nil)}
  end

  # ──────────────────────────────────────────────────────────────────────────
  # Event handlers
  # ──────────────────────────────────────────────────────────────────────────

  @impl true
  def handle_event("load_more", _params, socket) do
    scope = socket.assigns.current_scope

    next =
      Organizations.list_members_with_activity(scope,
        limit: @page_size,
        offset: socket.assigns.offset
      )

    decorated = decorate_rows(next)

    new_offset = socket.assigns.offset + length(decorated)

    socket =
      Enum.reduce(decorated, socket, fn member, acc ->
        stream_insert(acc, :members, member, at: -1)
      end)

    {:noreply,
     socket
     |> assign(:offset, new_offset)
     |> assign(:has_more, new_offset < socket.assigns.total_count)}
  end

  def handle_event("open_role_modal", %{"id" => id}, socket) do
    case find_streamed_member(socket, id) do
      nil ->
        {:noreply, socket}

      member ->
        {:noreply,
         socket
         |> assign(:pending_action, {:role, member})
         |> assign(:role_modal_error, nil)
         |> push_event("open-modal", %{id: "confirm-role-modal"})}
    end
  end

  def handle_event("open_remove_modal", %{"id" => id}, socket) do
    case find_streamed_member(socket, id) do
      nil ->
        {:noreply, socket}

      member ->
        {:noreply,
         socket
         |> assign(:pending_action, {:remove, member})
         |> assign(:remove_modal_error, nil)
         |> push_event("open-modal", %{id: "confirm-remove-modal"})}
    end
  end

  def handle_event("cancel_action", _params, socket) do
    {:noreply,
     socket
     |> assign(:pending_action, nil)
     |> assign(:role_modal_error, nil)
     |> assign(:remove_modal_error, nil)
     |> push_event("close-modal", %{id: "confirm-role-modal"})
     |> push_event("close-modal", %{id: "confirm-remove-modal"})}
  end

  def handle_event("change_role", %{"role" => role_str}, socket) do
    {:role, member} = socket.assigns.pending_action
    scope = socket.assigns.current_scope

    with {:ok, new_role} <- safe_role_atom(role_str),
         {:ok, updated} <- Organizations.change_member_role(scope, member, new_role) do
      updated_decorated =
        updated
        |> Map.put(:__last_active__, Map.get(member, :__last_active__))

      {:noreply,
       socket
       |> stream_insert(:members, updated_decorated)
       |> assign(:pending_action, nil)
       |> assign(:role_modal_error, nil)
       |> put_flash(:info, "Role updated.")
       |> push_event("close-modal", %{id: "confirm-role-modal"})}
    else
      {:error, :last_owner} ->
        # D-20: modal stays open, inline error with exact UI-SPEC copy.
        {:noreply,
         assign(
           socket,
           :role_modal_error,
           "Cannot demote the last owner. Promote another member to owner first."
         )}

      {:error, :invalid_role} ->
        {:noreply, assign(socket, :role_modal_error, "Invalid role.")}

      {:error, _changeset} ->
        {:noreply,
         assign(
           socket,
           :role_modal_error,
           "Could not update role. Please try again."
         )}
    end
  end

  def handle_event("remove_member", _params, socket) do
    {:remove, member} = socket.assigns.pending_action
    scope = socket.assigns.current_scope
    org_name = scope.active_organization.name
    email = member.user.email

    case Organizations.remove_member(scope, member) do
      {:ok, _removed} ->
        {:noreply,
         socket
         |> stream_delete(:members, member)
         |> assign(:pending_action, nil)
         |> assign(:remove_modal_error, nil)
         |> assign(:total_count, max(socket.assigns.total_count - 1, 0))
         |> put_flash(:info, "Removed #{email} from #{org_name}.")
         |> push_event("close-modal", %{id: "confirm-remove-modal"})}

      {:error, :last_owner} ->
        # D-20: modal stays open, inline error with exact UI-SPEC copy.
        {:noreply,
         assign(
           socket,
           :remove_modal_error,
           "Cannot remove the last owner. Promote another member to owner first."
         )}
    end
  end

  # ──────────────────────────────────────────────────────────────────────────
  # Render
  # ──────────────────────────────────────────────────────────────────────────

  @impl true
  def render(assigns) do
    ~H"""
    <Layouts.app
      flash={@flash}
      current_scope={@current_scope}
      user_organizations={@user_organizations}
    >
    <.header>
      Members ({@total_count})
      <:actions>
        <.button disabled aria-disabled="true" title="Available in the next release">
          Invite member
        </.button>
      </:actions>
    </.header>

    <section id="members-section" class="overflow-x-auto">
      <.table id="members-table" rows={@streams.members}>
        <:col :let={{_dom_id, m}} label="Email">{m.user.email}</:col>
        <:col :let={{_dom_id, m}} label="Role">
          <span class={["badge", role_badge_class(m.role)]}>{humanize_role(m.role)}</span>
        </:col>
        <:col :let={{_dom_id, _m}} label="Status">
          <span class="badge badge-ghost">Active</span>
        </:col>
        <:col :let={{_dom_id, m}} label="Joined">{relative_time(m.inserted_at)}</:col>
        <:col :let={{_dom_id, m}} label="Last active">
          {if m.__last_active__, do: relative_time(m.__last_active__), else: "Never"}
        </:col>
        <:action :let={{_dom_id, m}}>
          <details class="dropdown dropdown-end">
            <summary class="btn btn-ghost btn-xs">
              <.icon name="hero-ellipsis-horizontal" class="size-4" />
              <span class="sr-only">Member actions</span>
            </summary>
            <ul class="menu dropdown-content bg-base-100 rounded-box z-10 w-40 p-1 shadow">
              <li>
                <button type="button" phx-click="open_role_modal" phx-value-id={m.id}>
                  Change role
                </button>
              </li>
              <li>
                <button
                  type="button"
                  class="text-error"
                  phx-click="open_remove_modal"
                  phx-value-id={m.id}
                >
                  Remove
                </button>
              </li>
            </ul>
          </details>
        </:action>
      </.table>

      <.button :if={@has_more} phx-click="load_more" class="mt-4">
        Load more
      </.button>
    </section>

    <section id="pending-invitations-section" class="mt-8">
      <h2 class="text-lg font-semibold">Pending invitations</h2>
      
      <div class="card bg-base-200 mt-2 p-6 text-center text-sm text-base-content/70">
        No pending invitations. Inviting members is coming in the next release.
      </div>
    </section>

    <dialog id="confirm-role-modal" class="modal" phx-hook="DialogModal">
      <%= if match?({:role, _}, @pending_action) do %>
        <% {:role, m} = @pending_action %>
        <div class="modal-box">
          <h3 class="text-lg font-semibold">Change {m.user.email}'s role?</h3>

          <%= if @role_modal_error do %>
            <p class="text-error mt-2 text-sm" role="alert">{@role_modal_error}</p>
          <% end %>

          <form phx-submit="change_role" class="mt-4 space-y-4">
            <label class="form-control w-full">
              <span class="label-text">New role</span>
              <select name="role" class="select select-bordered w-full">
                <option value="owner" selected={m.role == :owner}>Owner</option>
                <option value="admin" selected={m.role == :admin}>Admin</option>
                <option value="member" selected={m.role == :member}>Member</option>
              </select>
            </label>

            <div class="modal-action">
              <button type="submit" class="btn btn-primary">Change role</button>
              <button type="button" class="btn btn-ghost" phx-click="cancel_action">
                Cancel
              </button>
            </div>
          </form>
        </div>
        <form method="dialog" class="modal-backdrop"><button>close</button></form>
      <% end %>
    </dialog>

    <dialog id="confirm-remove-modal" class="modal" phx-hook="DialogModal">
      <%= if match?({:remove, _}, @pending_action) do %>
        <% {:remove, m} = @pending_action %>
        <div class="modal-box">
          <h3 class="text-lg font-semibold">
            Remove {m.user.email} from {@current_scope.active_organization.name}?
          </h3>
          <p class="py-2 text-sm">
            {m.user.email} will be signed out of this organization immediately. You can re-invite them later.
          </p>

          <%= if @remove_modal_error do %>
            <p class="text-error mt-2 text-sm" role="alert">{@remove_modal_error}</p>
          <% end %>

          <form phx-submit="remove_member">
            <div class="modal-action">
              <button type="submit" class="btn btn-error">Remove member</button>
              <button type="button" class="btn btn-ghost" phx-click="cancel_action">
                Cancel
              </button>
            </div>
          </form>
        </div>
        <form method="dialog" class="modal-backdrop"><button>close</button></form>
      <% end %>
    </dialog>
    </Layouts.app>
    """
  end

  # ──────────────────────────────────────────────────────────────────────────
  # Helpers — customize freely
  # ──────────────────────────────────────────────────────────────────────────

  # Decorates raw `{membership, last_active_at}` tuples from
  # `Organizations.list_members_with_activity/2` into flat structs the stream
  # can key by membership id and the template can render without nested
  # destructuring.
  defp decorate_rows(rows) do
    Enum.map(rows, fn
      {membership, last_active} ->
        Map.put(membership, :__last_active__, last_active)

      %_{} = membership ->
        Map.put(membership, :__last_active__, nil)
    end)
  end

  # Looks up a streamed member by id. Because the stream is seeded from a
  # scope-filtered library query, a stranger membership id would have no
  # corresponding LiveView socket entry and this returns nil (T-16-05-03).
  # The Plan 01 library also scopes mutations by organization_id so a foreign
  # id admitted here could not mutate cross-tenant rows.
  defp find_streamed_member(socket, id) do
    # Streams don't expose their source list directly; we stash the decorated
    # list in `socket.assigns[:_members_by_id]` on first use. For the Phase 16
    # scope we refetch from the library on demand — it's a single indexed
    # lookup and avoids duplicating state with the stream.
    scope = socket.assigns.current_scope

    scope
    |> Organizations.list_members_with_activity(limit: 1_000, offset: 0)
    |> decorate_rows()
    |> Enum.find(fn m -> to_string(m.id) == to_string(id) end)
  end

  # Accepts only the three known atoms. String.to_existing_atom/1 would also
  # work but would raise on an unknown string; returning an {:error, ...}
  # tuple keeps the LV handler purely case-driven.
  defp safe_role_atom("owner"), do: {:ok, :owner}
  defp safe_role_atom("admin"), do: {:ok, :admin}
  defp safe_role_atom("member"), do: {:ok, :member}
  defp safe_role_atom(_other), do: {:error, :invalid_role}

  # UI-SPEC §Color — role badge variants.
  defp role_badge_class(:owner), do: "badge-primary"
  defp role_badge_class(:admin), do: "badge-neutral"
  defp role_badge_class(:member), do: "badge-ghost"
  defp role_badge_class(_), do: "badge-ghost"

  defp humanize_role(:owner), do: "Owner"
  defp humanize_role(:admin), do: "Admin"
  defp humanize_role(:member), do: "Member"
  defp humanize_role(other), do: other |> to_string() |> String.capitalize()

  # Lightweight relative-time formatter — hosts commonly replace this with
  # their own `Cldr` / `Timex` helper. Kept inline to keep the template
  # self-contained with zero new deps.
  defp relative_time(nil), do: "Never"

  defp relative_time(%DateTime{} = dt) do
    diff = DateTime.diff(DateTime.utc_now(), dt, :second)
    format_relative(diff)
  end

  defp relative_time(%NaiveDateTime{} = ndt) do
    ndt
    |> DateTime.from_naive!("Etc/UTC")
    |> relative_time()
  end

  defp format_relative(diff) when diff < 60, do: "just now"
  defp format_relative(diff) when diff < 3_600, do: "#{div(diff, 60)} minutes ago"
  defp format_relative(diff) when diff < 86_400, do: "#{div(diff, 3_600)} hours ago"
  defp format_relative(diff) when diff < 2_592_000, do: "#{div(diff, 86_400)} days ago"
  defp format_relative(diff), do: "#{div(diff, 2_592_000)} months ago"
end
