defmodule Example.Accounts.Emails.ProviderLinked do
  @moduledoc """
  Email notification sent when an OAuth provider is linked to a user's account.

  Includes a security prompt in case the user did not initiate the action.

  Generated by `mix sigra.gen.oauth`. Customize freely -- this module
  is owned by your application.
  """

  import Swoosh.Email

  @from_address {"Example", "noreply@example.com"}

  @font_family ~s(-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif)

  @doc """
  Builds a provider-linked notification email.

  ## Parameters

    * `user` - The user struct (must have `:email` field)
    * `provider_name` - Display name of the provider (e.g., "Google")
    * `secure_account_url` - URL for the user to secure their account
  """
  def build(user, provider_name, secure_account_url) do
    html_body = """
    <div style="max-width: 560px; margin: 0 auto; padding: 24px;">
      <p style="margin: 0 0 16px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        #{provider_name} was linked to your account.
      </p>
      <p style="margin: 0 0 16px 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family};">
        You can now use #{provider_name} to sign in to your account.
      </p>
      <p style="margin: 0 0 16px 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family};">
        Not you?
        <a href="#{secure_account_url}" style="color: #4f46e5; text-decoration: underline;">Secure your account</a>.
      </p>
    </div>
    """

    text_body = """
    #{provider_name} was linked to your account.

    You can now use #{provider_name} to sign in to your account.

    Not you? Secure your account: #{secure_account_url}
    """

    new()
    |> to({user.email, user.email})
    |> from(@from_address)
    |> subject("#{provider_name} linked to your account")
    |> html_body(html_body)
    |> text_body(text_body)
  end
end
