defmodule <%= context_module %>.Emails do
  @moduledoc """
  Email builders for authentication flows.

  Each function returns a `Swoosh.Email` struct with HTML and plain text
  bodies. The HTML uses inline CSS for email client compatibility.

  Generated by `mix sigra.install`. Customize freely -- this module
  is owned by your application.
  """

  import Swoosh.Email
  use Gettext, backend: <%= web_module %>.Gettext

  @from_address {"<%= app_name %>", "<%= from_email %>"}

  @font_family ~s(-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif)

  # -- Public API --

  @doc "Builds a confirmation email with link and 6-digit code."
  def confirmation_email(user, url, code) do
    code_display = code |> String.graphemes() |> Enum.join(" ")

    html_content = """
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Hi, please confirm your email address by clicking the button below or entering the code.")}
    </p>
    <div style="margin: 24px 0; padding: 16px; background-color: #f4f4f5; border-radius: 8px; text-align: center;">
      <p style="margin: 0 0 4px 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family};">
        #{dgettext("sigra", "Your confirmation code:")}
      </p>
      <p style="margin: 0; font-size: 32px; font-weight: 700; line-height: 1.0; font-family: monospace; color: #18181b; letter-spacing: 0.25em;">
        #{code_display}
      </p>
    </div>
    <p style="margin: 0 0 12px 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "This code expires in 48 hours.")}
    </p>
    #{cta_button(dgettext("sigra", "Confirm email address"), url)}
    <p style="margin: 12px 0 0 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family}; word-break: break-all;">
      #{dgettext("sigra", "Or confirm via this link:")} #{url}
    </p>
    """

    text_body = """
    #{dgettext("sigra", "Hi,")}

    #{dgettext("sigra", "Please confirm your email address.")}

    #{dgettext("sigra", "Your confirmation code:")} #{code}

    #{dgettext("sigra", "Or confirm via this link:")} #{url}

    #{dgettext("sigra", "This link expires in 48 hours.")}

    ---
    #{footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Confirm your email"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a password reset email."
  def reset_password_email(user, url) do
    html_content = """
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Hi, we received a request to reset your password. If you didn't make this request, you can ignore this email.")}
    </p>
    #{cta_button(dgettext("sigra", "Reset password"), url)}
    <p style="margin: 12px 0 0 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family}; word-break: break-all;">
      #{dgettext("sigra", "Or use this link:")} #{url}
    </p>
    """

    text_body = """
    #{dgettext("sigra", "Hi,")}

    #{dgettext("sigra", "We received a request to reset your password. If you didn't make this request, you can ignore this email.")}

    #{dgettext("sigra", "Reset your password:")} #{url}

    ---
    #{footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Reset your password"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a magic link login email."
  def magic_link_email(user, url) do
    html_content = """
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Hi, click the button below to log in to your account. This link expires in 10 minutes.")}
    </p>
    #{cta_button(dgettext("sigra", "Log in to %{app_name}", app_name: "<%= app_name %>"), url)}
    <p style="margin: 12px 0 0 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family}; word-break: break-all;">
      #{dgettext("sigra", "Or use this link:")} #{url}
    </p>
    """

    text_body = """
    #{dgettext("sigra", "Hi,")}

    #{dgettext("sigra", "Click the link below to log in to your account. This link expires in 10 minutes.")}

    #{dgettext("sigra", "Log in:")} #{url}

    ---
    #{footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Log in to %{app_name}", app_name: "<%= app_name %>"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds an OAuth-only password reset guidance email."
  def oauth_reset_email(user, provider) do
    provider_name = provider |> to_string() |> String.capitalize()

    html_content = """
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Hi, it looks like you signed up using %{provider}. You can log in with %{provider} instead, or set a password from your account settings.", provider: provider_name)}
    </p>
    #{cta_button(dgettext("sigra", "Log in with %{provider}", provider: provider_name), "<%= log_in_url %>")}
    """

    text_body = """
    #{dgettext("sigra", "Hi,")}

    #{dgettext("sigra", "It looks like you signed up using %{provider}. You can log in with %{provider} instead, or set a password from your account settings.", provider: provider_name)}

    ---
    #{footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Reset your password"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a suspicious login notification email."
  def suspicious_login_email(user, details) do
    ip = Map.get(details, :ip, "Unknown")
    geo_city = Map.get(details, :geo_city)
    geo_country = Map.get(details, :geo_country_code)
    location = if geo_city, do: "#{geo_city}, #{geo_country}", else: "Unknown"
    device = Map.get(details, :device, "Unknown device")

    time =
      Map.get(details, :time, DateTime.utc_now())
      |> Calendar.strftime("%Y-%m-%d %H:%M:%S UTC")

    reset_url = "<%= reset_password_url %>"

    html_content = """
    <p style="margin: 0 0 16px 0; font-size: 20px; font-weight: 600; color: #18181b; line-height: 1.2; font-family: #{@font_family};">
      #{dgettext("sigra", "New Sign-In Detected")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "We noticed a new sign-in to your account from an unrecognized device or location.")}
    </p>
    <div style="margin: 16px 0; padding: 16px; background-color: #f4f4f5; border-radius: 8px;">
      <p style="margin: 0 0 8px 0; font-size: 14px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        <strong>#{dgettext("sigra", "IP address:")}</strong> #{ip}
      </p>
      <p style="margin: 0 0 8px 0; font-size: 14px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        <strong>#{dgettext("sigra", "Location:")}</strong> #{location}
      </p>
      <p style="margin: 0 0 8px 0; font-size: 14px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        <strong>#{dgettext("sigra", "Device:")}</strong> #{device}
      </p>
      <p style="margin: 0; font-size: 14px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        <strong>#{dgettext("sigra", "Time:")}</strong> #{time}
      </p>
    </div>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "If this was you, you can safely ignore this email.")}
    </p>
    #{cta_button(dgettext("sigra", "Not you? Secure your account"), reset_url)}
    """

    text_body = """
    #{dgettext("sigra", "New Sign-In Detected")}

    #{dgettext("sigra", "We noticed a new sign-in to your account from an unrecognized device or location.")}

    #{dgettext("sigra", "IP address:")} #{ip}
    #{dgettext("sigra", "Location:")} #{location}
    #{dgettext("sigra", "Device:")} #{device}
    #{dgettext("sigra", "Time:")} #{time}

    #{dgettext("sigra", "If this was you, you can safely ignore this email.")}

    #{dgettext("sigra", "Not you? Secure your account:")} #{reset_url}

    ---
    #{security_footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "New sign-in to your account"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a lockout notification email."
  def lockout_notification_email(user, _details) do
    reset_url = "<%= reset_password_url %>"

    html_content = """
    <p style="margin: 0 0 16px 0; font-size: 20px; font-weight: 600; color: #18181b; line-height: 1.2; font-family: #{@font_family};">
      #{dgettext("sigra", "Account Locked")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "We detected multiple failed login attempts on your account. For your security, your account has been temporarily locked for 15 minutes.")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "If this was you, you can try again after the lockout period.")}
    </p>
    #{cta_button(dgettext("sigra", "Change your password"), reset_url)}
    <p style="margin: 12px 0 0 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "If you did not attempt to log in, we recommend changing your password immediately.")}
    </p>
    """

    text_body = """
    #{dgettext("sigra", "Account Locked")}

    #{dgettext("sigra", "We detected multiple failed login attempts on your account. For your security, your account has been temporarily locked for 15 minutes.")}

    #{dgettext("sigra", "If this was you, you can try again after the lockout period.")}

    #{dgettext("sigra", "Change your password:")} #{reset_url}

    #{dgettext("sigra", "If you did not attempt to log in, we recommend changing your password immediately.")}

    ---
    #{security_footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Your account has been temporarily locked"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  # -- Private helpers --

  defp base_email(to) do
    new()
    |> to(to)
    |> from(@from_address)
  end

  defp base_layout(content_html) do
    """
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <title><%= app_name %></title>
    </head>
    <body style="margin: 0; padding: 0; background-color: #f4f4f5; font-family: #{@font_family};">
      <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color: #f4f4f5;">
        <tr>
          <td align="center" style="padding: 24px 16px;">
            <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width: 600px; width: 100%;">
              <!-- Header -->
              <tr>
                <td align="center" style="padding: 24px 16px 12px 16px;">
                  <h1 style="margin: 0; font-size: 24px; font-weight: 700; line-height: 1.2; color: #18181b; font-family: #{@font_family};">
                    <%= app_name %>
                  </h1>
                </td>
              </tr>
              <!-- Content Card -->
              <tr>
                <td>
                  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color: #ffffff; border: 1px solid #e4e4e7; border-radius: 8px;">
                    <tr>
                      <td style="padding: 24px 16px;">
                        #{content_html}
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
              <!-- Footer -->
              <tr>
                <td align="center" style="padding: 24px 16px;">
                  <p style="margin: 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family};">
                    #{footer_text()}
                  </p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </body>
    </html>
    """
  end

  defp cta_button(label, url) do
    """
    <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin: 24px 0;">
      <tr>
        <td align="center">
          <a href="#{url}" style="display: inline-block; padding: 12px 24px; background-color: #2563eb; color: #ffffff; font-size: 16px; font-weight: 700; line-height: 1.0; font-family: #{@font_family}; text-decoration: none; border-radius: 8px;" role="link">
            #{label}
          </a>
        </td>
      </tr>
    </table>
    """
  end

  defp footer_text do
    dgettext(
      "sigra",
      "You're receiving this email because you have an account with %{app_name}. If you didn't request this, you can safely ignore this email.",
      app_name: "<%= app_name %>"
    )
  end

  defp security_footer_text do
    dgettext(
      "sigra",
      "You received this email because your %{app_name} account experienced a security event.",
      app_name: "<%= app_name %>"
    )
  end
end
