defmodule <%= web_module %>.ResetPasswordLive do
  @moduledoc """
  LiveView for password reset flows.

  Handles two states:
  - Request form: user enters email to receive reset instructions
  - Password form: user enters new password with real-time validation
    and strength meter (reuses Phase 2 registration pattern, D-34/D-50)

  Generated by `mix sigra.install --live`.
  """
  use <%= web_module %>, :live_view

  def render(%{live_action: :new} = assigns) do
    ~H"""
    <div class="mx-auto max-w-sm">
      <.header>
        {dgettext("sigra", "Forgot your password?")}
        <:subtitle>
          {dgettext("sigra", "Enter your email and we'll send you a reset link.")}
        </:subtitle>
      </.header>

      <.form
        for={@email_form}
        id="reset_password_request_form"
        phx-submit="send_instructions"
      >
        <.input field={@email_form[:email]} type="email" label={dgettext("sigra", "Email")} autocomplete="username" required />

        <.button phx-disable-with={dgettext("sigra", "Sending...")} class="btn btn-primary w-full">
          {dgettext("sigra", "Send reset instructions")} <span aria-hidden="true">&rarr;</span>
        </.button>
      </.form>

      <p class="mt-4 text-center text-sm">
        <.link navigate={~p"/users/log_in"} class="font-semibold text-brand hover:underline">
          {dgettext("sigra", "Back to log in")}
        </.link>
      </p>
    </div>
    """
  end

  def render(%{live_action: :edit} = assigns) do
    ~H"""
    <div class="mx-auto max-w-sm">
      <.header>
        {dgettext("sigra", "Reset your password")}
        <:subtitle>
          {dgettext("sigra", "Enter your new password below.")}
        </:subtitle>
      </.header>

      <div :if={@token_invalid?} class="mt-4">
        <.header>
          {dgettext("sigra", "Reset link expired")}
          <:subtitle>
            {dgettext("sigra", "This password reset link has expired or was already used.")}
          </:subtitle>
        </.header>

        <div class="mt-6">
          <.link navigate={~p"/users/reset-password"} class="btn btn-primary w-full text-center block">
            {dgettext("sigra", "Request new reset email")}
          </.link>
        </div>
      </div>

      <.form
        :if={!@token_invalid?}
        :let={f}
        for={@form}
        id="reset_password_form"
        phx-submit="reset"
        phx-change="validate"
        phx-trigger-action={@trigger_submit}
        action={~p"/users/log_in?_action=password_reset"}
        method="post"
      >
        <p :if={@check_errors} class="alert alert-danger">
          {dgettext("sigra", "Oops, something went wrong! Please check the errors below.")}
        </p>

        <.input field={f[:password]} type="password" label={dgettext("sigra", "New password")} autocomplete="new-password" required />

        <%% # Password strength indicator (reused from registration, D-34) %>
        <div :if={@password_strength} class="mt-1 mb-4">
          <div class="flex items-center gap-2">
            <div class="flex-1 h-2 rounded-full bg-gray-200">
              <div
                class={[
                  "h-2 rounded-full transition-all duration-300",
                  password_strength_color(@password_strength)
                ]}
                style={"width: #{password_strength_width(@password_strength)}%"}
              />
            </div>
            <span class={"text-xs font-medium #{password_strength_text_color(@password_strength)}"}>
              {password_strength_label(@password_strength)}
            </span>
          </div>
          <ul :if={@password_suggestions != []} class="mt-1 text-xs text-gray-500 list-disc list-inside">
            <li :for={suggestion <- @password_suggestions}>{suggestion}</li>
          </ul>
        </div>

        <.input field={f[:password_confirmation]} type="password" label={dgettext("sigra", "Confirm new password")} autocomplete="new-password" required />

        <.button phx-disable-with={dgettext("sigra", "Resetting...")} class="btn btn-primary w-full">
          {dgettext("sigra", "Reset password")} <span aria-hidden="true">&rarr;</span>
        </.button>
      </.form>
    </div>
    """
  end

  def mount(params, _session, socket) do
    socket =
      socket
      |> assign(trigger_submit: false, check_errors: false)
      |> assign(password_strength: nil, password_suggestions: [])
      |> assign(token_invalid?: false)
      |> assign(email_form: to_form(%{"email" => ""}, as: "user"))

    case socket.assigns.live_action do
      :new ->
        {:ok, socket}

      :edit ->
        token = params["token"]

        case <%= context_module %>.get_user_by_reset_password_token(token) do
          nil ->
            {:ok, assign(socket, token_invalid?: true, form: nil, token: nil, user: nil)}

          user ->
            changeset = <%= context_module %>.change_user_password(user)

            {:ok,
             socket
             |> assign(token: token, user: user)
             |> assign_form(changeset)}
        end
    end
  end

  def handle_event("send_instructions", %{"user" => %{"email" => email}}, socket) do
    if user = <%= context_module %>.get_user_by_email(email) do
      <%= context_module %>.deliver_user_reset_password_instructions(
        user,
        &url(socket, ~p"/users/reset-password/#{&1}")
      )
    end

    {:noreply,
     socket
     |> put_flash(:info, dgettext("sigra", "If your email is in our system, you will receive reset instructions shortly."))
     |> redirect(to: ~p"/users/log_in")}
  end

  def handle_event("validate", %{"user" => user_params}, socket) do
    changeset =
      socket.assigns.user
      |> <%= context_module %>.change_user_password(user_params)
      |> Map.put(:action, :validate)

    # Real-time password strength feedback (D-34)
    {strength, suggestions} =
      case Map.get(user_params, "password", "") do
        "" -> {nil, []}
        password -> Sigra.PasswordPolicy.check_strength(password)
      end

    {:noreply,
     socket
     |> assign(password_strength: strength, password_suggestions: suggestions)
     |> assign_form(changeset)}
  end

  def handle_event("reset", %{"user" => password_params}, socket) do
    case <%= context_module %>.reset_user_password(socket.assigns.user, password_params) do
      {:ok, _user} ->
        {:noreply,
         socket
         |> put_flash(:info, dgettext("sigra", "Your password has been reset."))
         |> assign(trigger_submit: true)}

      {:error, changeset} ->
        {:noreply, socket |> assign(check_errors: true) |> assign_form(changeset)}
    end
  end

  defp assign_form(socket, %Ecto.Changeset{} = changeset) do
    form = to_form(changeset, as: "user")

    if changeset.valid? do
      assign(socket, form: form, check_errors: false)
    else
      assign(socket, form: form)
    end
  end

  defp password_strength_color(:weak), do: "bg-red-500"
  defp password_strength_color(:fair), do: "bg-yellow-500"
  defp password_strength_color(:strong), do: "bg-green-500"
  defp password_strength_color(_), do: "bg-gray-300"

  defp password_strength_width(:weak), do: 33
  defp password_strength_width(:fair), do: 66
  defp password_strength_width(:strong), do: 100
  defp password_strength_width(_), do: 0

  defp password_strength_label(:weak), do: dgettext("sigra", "Weak")
  defp password_strength_label(:fair), do: dgettext("sigra", "Fair")
  defp password_strength_label(:strong), do: dgettext("sigra", "Strong")
  defp password_strength_label(_), do: ""

  defp password_strength_text_color(:weak), do: "text-red-600"
  defp password_strength_text_color(:fair), do: "text-yellow-600"
  defp password_strength_text_color(:strong), do: "text-green-600"
  defp password_strength_text_color(_), do: "text-gray-400"
end
