#!/usr/bin/env bash
set -euo pipefail

TRACKED_PATH="doc/llms.txt"
GENERATED_FILE="doc/llms.txt"

usage() {
  cat <<'EOF'
Usage: check-docs-index.sh [--tracked-path PATH] [--generated-file PATH]

Compare the full generated ExDoc index against its Git-indexed blob.
EOF
}

fail() {
  echo "check-docs-index: FAIL: $*" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tracked-path)
      [[ $# -ge 2 ]] || fail "--tracked-path requires a path"
      TRACKED_PATH="$2"
      shift 2
      ;;
    --generated-file)
      [[ $# -ge 2 ]] || fail "--generated-file requires a path"
      GENERATED_FILE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "unknown argument: $1"
      ;;
  esac
done

[[ "$TRACKED_PATH" != /* && -n "$TRACKED_PATH" ]] \
  || fail "tracked path must be a non-empty repository-relative path"

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" \
  || fail "must run inside a Git worktree"

if [[ "$GENERATED_FILE" != /* ]]; then
  GENERATED_FILE="${REPO_ROOT}/${GENERATED_FILE}"
fi

if [[ ! -f "$GENERATED_FILE" ]]; then
  fail "generated file is missing at ${GENERATED_FILE}; run 'mix docs --warnings-as-errors', then commit the complete ${TRACKED_PATH} output"
fi

INDEXED_FILE="$(mktemp)"
trap 'rm -f "$INDEXED_FILE"' EXIT

if ! git show ":${TRACKED_PATH}" >"$INDEXED_FILE" 2>/dev/null; then
  fail "Git-indexed file ${TRACKED_PATH} is missing; run 'mix docs --warnings-as-errors', then git add ${TRACKED_PATH} and commit the generated output"
fi

if ! cmp -s "$INDEXED_FILE" "$GENERATED_FILE"; then
  fail "generated bytes differ from Git-indexed ${TRACKED_PATH}; run 'mix docs --warnings-as-errors', then git add ${TRACKED_PATH} and commit the complete generated output"
fi

printf 'PASS: generated docs index matches Git-indexed %s\n' "$TRACKED_PATH"
