#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HELPER="${ROOT}/scripts/ci/check-docs-index.sh"
WORKFLOW="${ROOT}/.github/workflows/ci.yml"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

PASS_COUNT=0
FAIL_COUNT=0

pass() {
  PASS_COUNT=$((PASS_COUNT + 1))
  printf 'PASS: %s\n' "$1"
}

fail() {
  FAIL_COUNT=$((FAIL_COUNT + 1))
  printf 'FAIL: %s\n' "$1" >&2
}

FIXTURE="${TMP}/repo"
mkdir -p "${FIXTURE}/doc" "${FIXTURE}/generated"
git -C "$FIXTURE" init -q
git -C "$FIXTURE" config user.name "Sigra fixture"
git -C "$FIXTURE" config user.email "fixture@example.invalid"
cat >"${FIXTURE}/doc/llms.txt" <<'EOF'
# Sigra v1.6.0 - Table of Contents

## Modules

- Sigra
EOF
cp "${FIXTURE}/doc/llms.txt" "${FIXTURE}/generated/llms.txt"
git -C "$FIXTURE" add doc/llms.txt

run_helper() {
  (cd "$FIXTURE" && bash "$HELPER" \
    --tracked-path doc/llms.txt \
    --generated-file generated/llms.txt) 2>&1
}

echo "Test 1: exact indexed and generated bytes pass"
if OUTPUT="$(run_helper)"; then
  pass "exact full-file match passes"
else
  fail "exact match was rejected: ${OUTPUT}"
fi

echo "Test 2: title-only drift fails with a regeneration instruction"
sed 's/Sigra v1\.6\.0/Sigra v1.5.0/' "${FIXTURE}/doc/llms.txt" >"${FIXTURE}/generated/llms.txt"
if OUTPUT="$(run_helper)"; then
  fail "title-only drift passed"
else
  if grep -Fq 'mix docs --warnings-as-errors' <<<"$OUTPUT" \
     && grep -Fq 'doc/llms.txt' <<<"$OUTPUT" \
     && grep -Eiq 'commit|track' <<<"$OUTPUT"; then
    pass "title drift fails with the command, tracked path, and commit guidance"
  else
    fail "title drift diagnostic is incomplete: ${OUTPUT}"
  fi
fi

echo "Test 3: equal-length generated navigation-row drift fails"
cp "${FIXTURE}/doc/llms.txt" "${FIXTURE}/generated/llms.txt"
sed -i.bak 's/- Sigra$/- Sigrb/' "${FIXTURE}/generated/llms.txt"
rm -f "${FIXTURE}/generated/llms.txt.bak"
if OUTPUT="$(run_helper)"; then
  fail "generated row drift passed"
else
  INDEXED_SIZE="$(wc -c <"${FIXTURE}/doc/llms.txt")"
  GENERATED_SIZE="$(wc -c <"${FIXTURE}/generated/llms.txt")"
  if [[ "$INDEXED_SIZE" -eq "$GENERATED_SIZE" ]]; then
    pass "equal-length generated row drift fails"
  else
    fail "generated row fixture did not preserve file length"
  fi
fi

echo "Test 4: missing Git-indexed file fails"
git -C "$FIXTURE" rm --cached -q doc/llms.txt
cp "${FIXTURE}/doc/llms.txt" "${FIXTURE}/generated/llms.txt"
if OUTPUT="$(run_helper)"; then
  fail "missing indexed file passed"
else
  if grep -Fq 'doc/llms.txt' <<<"$OUTPUT"; then
    pass "missing indexed file fails with its path"
  else
    fail "missing indexed file diagnostic omitted the path: ${OUTPUT}"
  fi
fi

echo "Test 5: missing generated file fails"
git -C "$FIXTURE" add doc/llms.txt
rm -f "${FIXTURE}/generated/llms.txt"
if OUTPUT="$(run_helper)"; then
  fail "missing generated file passed"
else
  if grep -Fq 'generated/llms.txt' <<<"$OUTPUT"; then
    pass "missing generated file fails with its path"
  else
    fail "missing generated file diagnostic omitted the path: ${OUTPUT}"
  fi
fi

echo "Test 6: required CI builds, compares, and gates docs-only changes"
JOB="${TMP}/library-tests-dep-off.yml"
awk '
  /^  library_tests_dep_off:[[:space:]]*$/ { in_job=1 }
  in_job && /^  [A-Za-z0-9_.-]+:[[:space:]]*$/ && $0 !~ /^  library_tests_dep_off:/ { exit }
  in_job { print }
' "$WORKFLOW" >"$JOB"
if [[ ! -s "$JOB" ]]; then
  fail "could not extract library_tests_dep_off from ${WORKFLOW}"
else
  if awk '
    /^      - name: Check docs build cleanly$/ {
      if (getline <= 0 || $0 != "        run: mix docs --warnings-as-errors") exit 1
      if (getline <= 0 || $0 != "      - name: Check generated docs index") exit 1
      if (getline <= 0 || $0 != "        run: bash scripts/ci/check-docs-index.sh") exit 1
      found=1
    }
    END { if (!found) exit 1 }
  ' "$JOB" \
     && grep -Eq '^    needs: \[release_ref_guard, changes\]$' "$JOB" \
     && grep -Fq "needs.release_ref_guard.result == 'success'" "$JOB" \
     && grep -Fq '!cancelled()' "$JOB" \
     && ! grep -Fq 'needs.changes.outputs.docs_only' "$JOB" \
     && ! grep -Fq 'continue-on-error:' "$JOB" \
     && ! grep -Eq 'GH_TOKEN|secrets\.' "$JOB" \
     && awk '
       /^  ci-gate:[[:space:]]*$/ { in_job=1; next }
       in_job && /^  [A-Za-z0-9_.-]+:[[:space:]]*$/ { in_job=0 }
       in_job && /^      - library_tests_dep_off[[:space:]]*$/ { found=1 }
       END { if (!found) exit 1 }
     ' "$WORKFLOW" \
     && grep -Fq "run 'mix docs --warnings-as-errors'" "$HELPER" \
     && grep -Fq 'git add ${TRACKED_PATH} and commit' "$HELPER"; then
    pass "required ci-gate job builds before comparing on docs-only changes with actionable repair guidance"
  else
    fail "workflow does not enforce the required build-then-compare contract"
  fi
fi

if [[ "$FAIL_COUNT" -eq 0 ]]; then
  printf '\n%d passed, %d failed\n' "$PASS_COUNT" "$FAIL_COUNT"
else
  printf '\n%d passed, %d failed\n' "$PASS_COUNT" "$FAIL_COUNT" >&2
  exit 1
fi
