#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
# Reuse the routing suite's canonical fixture constructor, then retain its valid files.
python3 - "$ROOT" "$TMP" <<'PY'
import json,subprocess,sys,os
root,tmp=sys.argv[1:]
negative=json.loads(subprocess.check_output([root+"/scripts/ci/verify-library-routing-evidence.sh","--print-negative-runs"]))
sha="c"*40;rate="gh api rate_limit --jq '.resources.core | {remaining,reset}'";fields="databaseId,event,headSha,conclusion,attempt,url,jobs";p=4005;s=4006
pr={"schema_version":"sigra.library-partitions-evidence/v1","repository":"szTheory/sigra","pr":{"number":234},"run":{"id":p,"url":f"https://github.com/szTheory/sigra/actions/runs/{p}","event":"pull_request","attempt":1,"head_sha":sha,"conclusion":"success"},"owner":{"id":501,"name":"Library tests shard","status":"completed","conclusion":"success","skipped":False},"aggregate":{"id":502,"name":"Library tests","status":"completed","conclusion":"success","skipped":False},"artifacts":[{"id":601,"name":f"library-partitions-{p}-1","file":"sigra-library-partitions.json","sha256":"1"*64},{"id":602,"name":f"library-partition-1-timings-{p}-1","file":"sigra-library-1-timings.json","sha256":"2"*64},{"id":603,"name":f"library-partition-2-timings-{p}-1","file":"sigra-library-2-timings.json","sha256":"3"*64}],"partitions":{"execution_mode":"sequential","ordinary_universe_count":20,"manifest_counts":[10,10],"test_counts":[40,42],"durations_ms":[12000,18000],"conclusions":["success","success"],"exit_statuses":[0,0]},"protected_invariants":{"library_tests_aggregate_sha256":"04308ef8fb56acc65c5730630e1fd3e926da6804068db07f6f15636c2a0890cb","sole_pr_owner":"MIX_ENV=test mix ci","fast_01_verifier":"source_complete_offline_attestation_verified","gate_05_verifier":"offline_attestation_verified"},"commands":{"rate_limit":rate,"watch":f"gh run watch {p} --repo szTheory/sigra --compact --interval 60 --exit-status","summary":f"gh run view {p} --repo szTheory/sigra --json {fields}","artifacts":[f"gh run download {p} --repo szTheory/sigra --name library-partitions-{p}-1",f"gh run download {p} --repo szTheory/sigra --name library-partition-1-timings-{p}-1",f"gh run download {p} --repo szTheory/sigra --name library-partition-2-timings-{p}-1"]},"supersession":{"plan04_status":"empirically superseded (failed evidence retained)","forbidden_predicates":["install_not_dominant","ordinary-vs-scaffold comparable"]},"negative_runs":negative}
paths=["test/sigra/install/features/passkeys_js_test.exs","test/sigra/install/generator_passkeys_opt_out_test.exs","test/sigra/install/golden_diff_test.exs","test/sigra/install/idempotency_test.exs","test/sigra/install/vault_promotion_test.exs","test/upgrade_test.exs"]
sc={"schema_version":"sigra.library-install-golden-evidence/v1","repository":"szTheory/sigra","run":{"id":s,"url":f"https://github.com/szTheory/sigra/actions/runs/{s}","event":"workflow_dispatch","attempt":1,"head_sha":sha,"conclusion":"failure"},"job":{"id":503,"name":"Library install golden (non-PR)","status":"completed","conclusion":"success","skipped":False},"artifacts":[{"id":604,"name":f"library-install-golden-{s}-1","file":"sigra-library-install-golden.json","sha256":"4"*64},{"id":605,"name":f"library-install-diagnostics-{s}-1","file":"sigra-install-golden-diagnostics.json","sha256":"5"*64}],"receivers":{"paths":paths,"count":6,"duration_ms":57389,"exit_status":0,"conclusion":"success","prepared_fixture":True,"worker_ceiling":2},"diagnostics":{"schema_version":"sigra.install-fixture-diagnostics/v1","variant_count":6,"worker_count":2,"failed_paths":[],"raw_install_duration_ms":57389},"protected_invariants":{"non_pr_events":["schedule","workflow_dispatch"],"pr_execution":False,"hard_signal":True},"commands":{"rate_limit":rate,"watch":f"gh run watch {s} --repo szTheory/sigra --compact --interval 60 --exit-status","summary":f"gh run view {s} --repo szTheory/sigra --json {fields}","artifacts":[f"gh run download {s} --repo szTheory/sigra --name library-install-golden-{s}-1",f"gh run download {s} --repo szTheory/sigra --name library-install-diagnostics-{s}-1"]},"supersession":{"failed_run_id":34435818106,"ordinary_duration_ms":28671,"install_duration_ms":79614,"safe_optimization_commits":["1fa788fc","488f4fa1"],"bounded_clean_local_range_ms":[56000,78000],"final_hard_stop_ms":57389,"status":"failed evidence retained"},"negative_runs":negative}
for name,obj in [("pr.json",pr),("sc.json",sc)]:json.dump(obj,open(os.path.join(tmp,name),"w"),sort_keys=True,separators=(",",":"))
PY
python3 - "$ROOT" "$TMP" <<'PY'
import copy,hashlib,json,os,subprocess,sys
root,tmp=sys.argv[1:];pr=json.load(open(tmp+"/pr.json"));sc=json.load(open(tmp+"/sc.json"));sha="e"*40;ids=[5001,5002];rate="gh api rate_limit --jq '.resources.core | {remaining,reset}'";fields="databaseId,event,headSha,conclusion,attempt,url,jobs"
canonical=(json.dumps(pr["negative_runs"],sort_keys=True,separators=(",",":"))+"\n").encode()
def run(i,event):return {"id":i,"url":f"https://github.com/szTheory/sigra/actions/runs/{i}","event":event,"attempt":1,"head_sha":sha,"conclusion":"success"}
def job(i,name):return {"id":i,"name":name,"status":"completed","conclusion":"success","skipped":False}
v={"schema_version":"sigra.library-routing-validation/v1","repository":"szTheory/sigra","evidence_commit_sha":sha,"capture_run_ids":[4005,4006],"negative_run_ids":[x["id"] for x in pr["negative_runs"]],"negative_runs_sha256":hashlib.sha256(canonical).hexdigest(),"validations":[{"route":"pr","run":run(5001,"pull_request"),"selected_jobs":[job(7001,"Library tests shard"),job(7002,"Library tests")]},{"route":"dispatch","run":run(5002,"workflow_dispatch"),"selected_jobs":[job(7003,"Library install golden (non-PR)")]}],"commands":{"rate_limit":[rate,rate],"watch":[f"gh run watch {i} --repo szTheory/sigra --compact --interval 60 --exit-status" for i in ids],"summary":[f"gh run view {i} --repo szTheory/sigra --json {fields}" for i in ids]}}
verify=root+"/scripts/ci/verify-library-validation-run.sh"
def check(obj,want):
 p=tmp+"/validation.json";json.dump(obj,open(p,"w"),sort_keys=True,separators=(",",":"));ok=subprocess.run([verify,p,tmp+"/pr.json",tmp+"/sc.json"],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL).returncode==0
 if ok!=want:raise AssertionError("unexpected validation result")
check(v,True)
mut=[]
for fn in [lambda x:x.update(evidence_commit_sha="d"*40),lambda x:x["capture_run_ids"].reverse(),lambda x:x["negative_run_ids"].pop(),lambda x:x.update(negative_runs_sha256="0"*64),lambda x:x["validations"].reverse(),lambda x:x["validations"][0]["run"].update(attempt=2),lambda x:x["validations"][0]["run"].update(id=4005),lambda x:x["validations"][1]["run"].update(head_sha="d"*40),lambda x:x["validations"][0]["selected_jobs"][0].update(conclusion="failure"),lambda x:x["commands"]["watch"].append(x["commands"]["watch"][0]),lambda x:x.update(waiver=True)]:
 x=copy.deepcopy(v);fn(x);check(x,False)
print("verify-library-validation-run.test: PASS")
PY
