defmodule ExampleWeb.Components.OrgSwitcher do
  @moduledoc """
  Organization switcher function component.

  Paste `<.org_switcher current_scope={@current_scope}
  user_organizations={@user_organizations} return_to={@current_path} />`
  into your app layout (typically the `<header>` in
  `lib/example_web/components/layouts.ex`).

  The component renders a daisyUI `<details class="dropdown">` — click to
  open, click-outside to close, Esc closes via native `<details>` behaviour.
  Other organizations are each wrapped in a tiny POST form that submits to
  `/organizations/switch`, preserving the sensitive-mutation-via-POST
  convention (D-05 / ORG-UX-03).

  Generated by `mix sigra.install`. Customize freely -- this module is
  owned by your application.
  """

  use ExampleWeb, :html

  alias Plug.CSRFProtection

  attr :current_scope, :any, required: true
  attr :user_organizations, :list, required: true
  attr :return_to, :string, default: "/"

  def org_switcher(assigns) do
    ~H"""
    <details class="dropdown dropdown-end" id="org-switcher">
      <summary
        aria-label="Organization switcher"
        aria-expanded="false"
        class="btn btn-ghost gap-2 normal-case">
        <span class="avatar placeholder bg-primary/10 text-primary-content rounded w-6 h-6 text-xs">
          {initials(@current_scope.active_organization.name)}
        </span>
        <span class="text-sm font-semibold truncate max-w-[20ch]">
          {@current_scope.active_organization.name}
        </span>
        <span class={["badge badge-xs", role_badge_class(@current_scope.membership.role)]}>
          {humanize_role(@current_scope.membership.role)}
        </span>
        <.icon name="hero-chevron-down" class="w-4 h-4" />
      </summary>

      <ul class="menu menu-sm dropdown-content bg-base-100 rounded-box w-64 p-1 shadow z-50">
        <li class="menu-title text-xs uppercase">Active</li>
        <li class="menu-active">
          <span>
            <.icon name="hero-check" class="w-4 h-4" />
            {@current_scope.active_organization.name}
            <span class={["badge badge-xs", role_badge_class(@current_scope.membership.role)]}>
              {humanize_role(@current_scope.membership.role)}
            </span>
          </span>
        </li>

        <%= if other_orgs(@user_organizations, @current_scope.active_organization) != [] do %>
          <li class="menu-title text-xs uppercase">Switch to</li>
          <%= for {org, role} <- other_orgs(@user_organizations, @current_scope.active_organization) do %>
            <li>
              <form action={~p"/organizations/switch"} method="post" class="w-full">
                <input type="hidden" name="_csrf_token" value={CSRFProtection.get_csrf_token()} />
                <input type="hidden" name="organization_id" value={org.id} />
                <input type="hidden" name="return_to" value={@return_to} />
                <button
                  type="submit"
                  aria-label={"Switch to #{org.name}"}
                  class="flex w-full items-center justify-between">
                  <span>{org.name}</span>
                  <span class={["badge badge-xs", role_badge_class(role)]}>
                    {humanize_role(role)}
                  </span>
                </button>
              </form>
            </li>
          <% end %>
        <% end %>

        <li class="divider my-1"></li>
        <li>
          <.link navigate={~p"/organizations/new"}>
            <.icon name="hero-plus" class="w-4 h-4" /> Create organization
          </.link>
        </li>
        <%= if @current_scope.membership.role in [:owner, :admin] do %>
          <li>
            <.link navigate={~p"/organizations/#{@current_scope.active_organization}/settings"}>
              <.icon name="hero-cog-6-tooth" class="w-4 h-4" /> Organization settings
            </.link>
          </li>
        <% end %>
        <li>
          <.link navigate={~p"/organizations"}>
            <.icon name="hero-users" class="w-4 h-4" /> Manage organizations
          </.link>
        </li>
      </ul>
    </details>
    """
  end

  # First two characters of an org name, uppercased, for the avatar placeholder.
  defp initials(name) when is_binary(name) do
    name
    |> String.trim()
    |> String.slice(0, 2)
    |> String.upcase()
  end

  defp initials(_), do: "?"

  # daisyUI badge variants per UI-SPEC §Color:
  #   owner  -> badge-primary (accent)
  #   admin  -> badge-neutral (neutral)
  #   member -> badge-ghost   (lowest weight)
  defp role_badge_class(:owner), do: "badge-primary"
  defp role_badge_class(:admin), do: "badge-neutral"
  defp role_badge_class(:member), do: "badge-ghost"
  defp role_badge_class(_), do: "badge-ghost"

  defp humanize_role(:owner), do: "Owner"
  defp humanize_role(:admin), do: "Admin"
  defp humanize_role(:member), do: "Member"
  defp humanize_role(role) when is_atom(role), do: role |> Atom.to_string() |> String.capitalize()
  defp humanize_role(_), do: ""

  # Filter the `{org, role}` tuples down to orgs OTHER than the active one.
  # Accepts either `[{org, role}]` (the shape produced by
  # `Sigra.Organizations.list_organizations_for_user/2` in Phase 16) or
  # `[org]` (a plain list, for forward-compat in case the shape changes).
  defp other_orgs(user_organizations, active_org) do
    active_id = active_org && active_org.id

    Enum.flat_map(user_organizations, fn
      {%{id: ^active_id}, _role} -> []
      {%{} = org, role} -> [{org, role}]
      %{id: ^active_id} -> []
      %{} = org -> [{org, :member}]
      _ -> []
    end)
  end
end
