defmodule ExampleWeb.Components.OrgSwitcher do
  @moduledoc """
  Organization switcher function component.

  Paste `<.org_switcher current_scope={@current_scope}
  user_organizations={@user_organizations} return_to={@current_path} />`
  into your app layout (typically the `<header>` in
  `lib/example_web/components/layouts.ex`).

  Renders a native `<details class="vt-menu">` dropdown (click to open,
  click-outside / Esc close via native `<details>` behaviour), styled with the
  Tasklane `vt-*` design system. Other organizations are each wrapped in a tiny
  POST form that submits to `/organizations/switch`, preserving the
  sensitive-mutation-via-POST convention (D-05 / ORG-UX-03).

  Generated by `mix sigra.install`. Customize freely -- this module is
  owned by your application.
  """

  use ExampleWeb, :html

  alias Plug.CSRFProtection

  attr :current_scope, :any, required: true
  attr :user_organizations, :list, required: true
  attr :return_to, :string, default: "/"

  def org_switcher(assigns) do
    ~H"""
    <details class="vt-menu" id="org-switcher">
      <summary aria-label="Organization switcher" aria-expanded="false">
        <span class="vt-avatar">{initials(@current_scope.active_organization.name)}</span>
        <span class="vt-menu__name">{@current_scope.active_organization.name}</span>
        <span class="vt-status-pill vt-status-pill--ok">
          {humanize_role(@current_scope.membership.role)}
        </span>
        <span aria-hidden="true">&#9662;</span>
      </summary>

      <div class="vt-menu__panel">
        <span class="vt-menu__label">Active</span>
        <span class="vt-menu__item is-active">
          <span class="vt-menu__item-row">
            <span>{@current_scope.active_organization.name}</span>
            <span class="vt-status-pill vt-status-pill--ok">
              {humanize_role(@current_scope.membership.role)}
            </span>
          </span>
        </span>

        <%= if other_orgs(@user_organizations, @current_scope.active_organization) != [] do %>
          <span class="vt-menu__label">Switch to</span>
          <%= for {org, role} <- other_orgs(@user_organizations, @current_scope.active_organization) do %>
            <form action={~p"/organizations/switch"} method="post">
              <input type="hidden" name="_csrf_token" value={CSRFProtection.get_csrf_token()} />
              <input type="hidden" name="organization_id" value={org.id} />
              <input type="hidden" name="return_to" value={@return_to} />
              <button type="submit" class="vt-menu__item" aria-label={"Switch to #{org.name}"}>
                <span class="vt-menu__item-row">
                  <span>{org.name}</span>
                  <span class="vt-status-pill">{humanize_role(role)}</span>
                </span>
              </button>
            </form>
          <% end %>
        <% end %>

        <div class="vt-menu__divider"></div>
        <.link navigate={~p"/organizations/new"} class="vt-menu__item">Create organization</.link>
        <.link
          :if={@current_scope.membership.role in [:owner, :admin]}
          navigate={~p"/organizations/#{@current_scope.active_organization}/settings"}
          class="vt-menu__item"
        >
          Organization settings
        </.link>
        <.link navigate={~p"/organizations"} class="vt-menu__item">Manage organizations</.link>
      </div>
    </details>
    """
  end

  # First two characters of an org name, uppercased, for the avatar chip.
  defp initials(name) when is_binary(name) do
    name
    |> String.trim()
    |> String.slice(0, 2)
    |> String.upcase()
  end

  defp initials(_), do: "?"

  defp humanize_role(:owner), do: "Owner"
  defp humanize_role(:admin), do: "Admin"
  defp humanize_role(:member), do: "Member"
  defp humanize_role(role) when is_atom(role), do: role |> Atom.to_string() |> String.capitalize()
  defp humanize_role(_), do: ""

  # Filter the `{org, role}` tuples down to orgs OTHER than the active one.
  # Accepts either `[{org, role}]` (the shape produced by
  # `Sigra.Organizations.list_organizations_for_user/2` in Phase 16) or
  # `[org]` (a plain list, for forward-compat in case the shape changes).
  defp other_orgs(user_organizations, active_org) do
    active_id = active_org && active_org.id

    Enum.flat_map(user_organizations, fn
      {%{id: ^active_id}, _role} -> []
      {%{} = org, role} -> [{org, role}]
      %{id: ^active_id} -> []
      %{} = org -> [{org, :member}]
      _ -> []
    end)
  end
end
