defmodule ExampleWeb.Auth.SessionLive do
  @moduledoc """
  LiveView for session listing and management.

  Displays all active sessions for the current user with device info,
  IP address, location, and last active time. Supports revoking individual
  sessions and logging out of all devices.

  Current session is identified via the session token passed through
  LiveView connect params and tagged with a "This device" badge.

  Generated by `mix sigra.install --live`. Customize freely -- this module
  is owned by your application.
  """
  use ExampleWeb, :live_view

  alias Example.Accounts, as: Auth
  alias Example.Organizations
  alias ExampleWeb.Layouts

  def mount(_params, _session, socket) do
    user = socket.assigns.current_scope.user
    sessions = Auth.list_sessions(user)
    current_token = get_connect_params(socket)["_sigra_token"]

    {:ok,
     assign(socket,
       sessions: sessions,
       current_token: current_token,
       user_organizations: Organizations.list_organizations_for_user(user),
       page_title: "Active sessions"
     )}
  end

  def render(assigns) do
    ~H"""
    <Layouts.app
      flash={@flash}
      current_scope={@current_scope}
      user_organizations={@user_organizations}
    >
      <section class="vt-page-intro" data-testid="app-sessions">
        <header class="vt-panel__header">
          <div>
            <p class="vt-kicker">Security</p>
            <h1 class="vt-panel__title">Active sessions</h1>
            <p class="vt-copy">These devices are currently signed in to your account.</p>
          </div>
          <a href={~p"/app"} class="vt-btn vt-btn--ghost">Back to dashboard</a>
        </header>

        <div class="vt-seed-list">
          <article
            :for={session <- @sessions}
            class="vt-panel"
            style="display:flex;align-items:flex-start;justify-content:space-between;gap:var(--sg-space-3)"
          >
            <div>
              <div style="display:flex;align-items:center;gap:var(--sg-space-2)">
                <strong>{device_name(session)}</strong>
                <span
                  :if={current_session?(session, @current_token)}
                  class="vt-status-pill vt-status-pill--ok"
                >
                  This device
                </span>
              </div>
              <p class="vt-copy">
                {session.ip || "Unknown IP"} &middot; {location(session)}
              </p>
              <p class="vt-copy">{relative_time(session.last_active_at)}</p>
            </div>
            <.button
              :if={current_session?(session, @current_token)}
              phx-click="revoke_current"
              phx-value-token={Base.url_encode64(session.hashed_token)}
              data-confirm="This is your current session. Revoking it will log you out. Continue?"
              class="vt-btn vt-btn--danger"
            >
              Revoke session
            </.button>
            <.button
              :if={!current_session?(session, @current_token)}
              phx-click="revoke"
              phx-value-token={Base.url_encode64(session.hashed_token)}
              class="vt-btn vt-btn--danger"
            >
              Revoke session
            </.button>
          </article>
        </div>

        <div :if={length(@sessions) > 1}>
          <.button
            phx-click="revoke_all"
            data-confirm="This will end all sessions including your current one. You will be logged out."
            class="vt-btn vt-btn--danger-solid"
          >
            Log out of all devices
          </.button>
        </div>
      </section>
    </Layouts.app>
    """
  end

  def handle_event("revoke", %{"token" => encoded_token}, socket) do
    hashed_token = Base.url_decode64!(encoded_token)
    Auth.revoke_session(hashed_token)

    sessions = Auth.list_sessions(socket.assigns.current_scope.user)
    {:noreply, socket |> put_flash(:info, "Session revoked.") |> assign(sessions: sessions)}
  end

  def handle_event("revoke_current", %{"token" => encoded_token}, socket) do
    hashed_token = Base.url_decode64!(encoded_token)
    Auth.revoke_session(hashed_token)

    {:noreply, redirect(socket, to: ~p"/users/log_in")}
  end

  def handle_event("revoke_all", _params, socket) do
    user = socket.assigns.current_scope.user
    Auth.revoke_all_sessions(user)

    {:noreply, redirect(socket, to: ~p"/users/log_in")}
  end

  defp device_name(%{parsed_ua: %{browser: browser, browser_version: version, os: os}})
       when browser != "Unknown" do
    if version, do: "#{browser} #{version} on #{os}", else: "#{browser} on #{os}"
  end

  defp device_name(_), do: "Unknown device"

  defp location(%{geo_city: city, geo_country_code: country}) when is_binary(city),
    do: "#{city}, #{country}"

  defp location(_), do: "Unknown location"

  defp relative_time(nil), do: "Never"

  defp relative_time(datetime) do
    seconds = DateTime.diff(DateTime.utc_now(), datetime, :second)

    cond do
      seconds < 60 -> "Active just now"
      seconds < 3600 -> "Active #{div(seconds, 60)} minutes ago"
      seconds < 86400 -> "Active #{div(seconds, 3600)} hours ago"
      true -> "Active #{div(seconds, 86400)} days ago"
    end
  end

  defp current_session?(%{hashed_token: token}, current_token) when is_binary(current_token) do
    case Base.url_decode64(current_token) do
      {:ok, decoded} -> token == decoded
      :error -> false
    end
  end

  defp current_session?(_, _), do: false
end
