defmodule SigraInstallGoldenTmpWeb.ConfirmationLive do
  @moduledoc """
  LiveView for email confirmation flow.

  Provides code entry with auto-submit on 6 digits, expired token
  handling, and resend functionality.

  Generated by `mix sigra.install --live`. Customize freely -- this module
  is owned by your application.
  """
  use SigraInstallGoldenTmpWeb, :live_view

  use Gettext, backend: SigraInstallGoldenTmpWeb.Gettext

  alias SigraInstallGoldenTmp.Accounts, as: Auth

  def render(assigns) do
    ~H"""
    <div class="mx-auto max-w-sm">
      <%= case @live_action do %>
        <% :new -> %>
          <.header>
            {dgettext("sigra", "Confirm your email")}
            <:subtitle>
              {dgettext("sigra", "Enter the 6-digit code we sent to your email, or check your inbox for a confirmation link.")}
            </:subtitle>
          </.header>

          <.form
            for={@form}
            id="confirmation_form"
            phx-change="validate"
            phx-submit="confirm"
          >
            <.input
              field={@form[:code]}
              type="text"
              label={dgettext("sigra", "Confirmation code")}
              inputmode="numeric"
              autocomplete="one-time-code"
              maxlength="6"
              pattern="[0-9]{6}"
              aria-label={dgettext("sigra", "Confirmation code")}
              required
            />

            <.button phx-disable-with={dgettext("sigra", "Confirming...")} class="btn btn-primary w-full">
              {dgettext("sigra", "Confirm email")} <span aria-hidden="true">&rarr;</span>
            </.button>
          </.form>

          <p class="mt-4 text-center text-sm">
            <.link phx-click="resend" class="font-semibold text-brand hover:underline cursor-pointer">
              {dgettext("sigra", "Didn't receive a code?")}
            </.link>
          </p>

        <% :already_confirmed -> %>
          <.header>
            {dgettext("sigra", "Email already confirmed")}
            <:subtitle>
              {dgettext("sigra", "Your email was already confirmed. You can log in below.")}
            </:subtitle>
          </.header>

          <p class="mt-4 text-center">
            <.link navigate={~p"/users/log_in"} class="font-semibold text-brand hover:underline">
              {dgettext("sigra", "Log in")}
            </.link>
          </p>

        <% :expired -> %>
          <.header>
            {dgettext("sigra", "Confirmation link expired")}
            <:subtitle>
              {dgettext("sigra", "This confirmation link has expired or was already used.")}
            </:subtitle>
          </.header>

          <.button phx-click="resend" phx-disable-with={dgettext("sigra", "Sending...")} class="btn btn-primary w-full">
            {dgettext("sigra", "Send new confirmation email")} <span aria-hidden="true">&rarr;</span>
          </.button>
      <% end %>
    </div>
    """
  end

  def mount(_params, _session, socket) do
    form = to_form(%{"code" => ""}, as: "confirmation")

    {:ok, assign(socket, form: form, live_action: :new)}
  end

  def handle_params(%{"token" => token}, _uri, socket) do
    _user = socket.assigns.current_scope.user

    case Auth.confirm_user(token) do
      {:ok, _user} ->
        {:noreply,
         socket
         |> put_flash(:info, dgettext("sigra", "Your email has been confirmed."))
         |> redirect(to: ~p"/")}

      {:error, :already_confirmed} ->
        {:noreply, assign(socket, live_action: :already_confirmed)}

      {:error, :token_expired} ->
        {:noreply, assign(socket, live_action: :expired)}

      {:error, :token_invalid} ->
        {:noreply,
         socket
         |> put_flash(:error, dgettext("sigra", "This confirmation link is invalid or has expired."))
         |> assign(live_action: :new)}
    end
  end

  def handle_params(_params, _uri, socket) do
    {:noreply, socket}
  end

  def handle_event("validate", %{"confirmation" => %{"code" => code}}, socket) do
    form = to_form(%{"code" => code}, as: "confirmation")
    socket = assign(socket, form: form)

    # 10.1 IN-06: call the confirm path directly when the user has typed a
    # full 6-digit code instead of dispatching via `send(self(), …)`. The
    # mailbox round-trip allowed a stale 6-digit prefix to fire after the
    # user typed a 7th character, wasting an attempt against the rate
    # limiter's max_code_attempts counter.
    if String.length(code) == 6 and Regex.match?(~r/^\d{6}$/, code) do
      do_confirm(socket, code)
    else
      {:noreply, socket}
    end
  end

  def handle_event("confirm", %{"confirmation" => %{"code" => code}}, socket) do
    do_confirm(socket, code)
  end

  def handle_event("resend", _params, socket) do
    user = socket.assigns.current_scope.user

    case Auth.deliver_user_confirmation_instructions(user, &url(socket, ~p"/users/confirm/#{&1}")) do
      {:ok, _} ->
        {:noreply, put_flash(socket, :info, dgettext("sigra", "A new confirmation email has been sent."))}

      {:error, :already_confirmed} ->
        {:noreply,
         socket
         |> put_flash(:info, dgettext("sigra", "Your email is already confirmed."))
         |> redirect(to: ~p"/")}
    end
  end

  defp do_confirm(socket, code) do
    user = socket.assigns.current_scope.user

    case Auth.confirm_user_by_code(user, code) do
      {:ok, _user} ->
        {:noreply,
         socket
         |> put_flash(:info, dgettext("sigra", "Your email has been confirmed."))
         |> redirect(to: ~p"/")}

      {:error, :invalid_code} ->
        form = to_form(%{"code" => ""}, as: "confirmation")

        {:noreply,
         socket
         |> put_flash(:error, dgettext("sigra", "Invalid confirmation code. Please try again."))
         |> assign(form: form)}

      {:error, :rate_limited} ->
        {:noreply,
         socket
         |> put_flash(:error, dgettext("sigra", "Too many attempts. Please wait a few minutes before trying again."))}

      {:error, :already_confirmed} ->
        {:noreply,
         socket
         |> put_flash(:info, dgettext("sigra", "Your email is already confirmed."))
         |> redirect(to: ~p"/")}
    end
  end
end
