defmodule SigraInstallGoldenTmpWeb.OrganizationSettingsLive do
  @moduledoc """
  Organization settings LiveView — three stacked sections on a single page
  (D-10): General (rename), Slug (change with 7-day redirect + inline sudo),
  and Danger Zone (soft-delete with inline sudo + typed-confirm of org name).

  All destructive actions use progressive disclosure (D-12): closed state
  renders a single button; clicking reveals an inline form with current
  password + typed-confirm fields. No modal dialogs, no sub-routes.

  Sudo is collected inline (D-11): the form carries a `current_password`
  field that the library's `update_slug/4` and `soft_delete_organization/4`
  functions verify via `Sigra.Crypto.verify_password/2`. On mismatch the
  library returns `{:error, :invalid_password}` and this LV surfaces the
  exact UI-SPEC copy `"That password is incorrect."` inline, without any
  redirect — form state is preserved.

  Non-admin members are redirected out of the LiveView at mount time. The
  `:org_scoped` pipeline enforces membership presence; this module owns the
  narrower settings-page role gate.

  Generated by `mix sigra.install`. Customize freely — this module is
  owned by your application.
  """
  use SigraInstallGoldenTmpWeb, :live_view

  alias SigraInstallGoldenTmp.Organizations

  @impl true
  def mount(_params, _session, socket) do
    scope = socket.assigns.current_scope
    org = scope.active_organization

    if can_manage_settings?(scope) do
      socket =
        socket
        |> assign(:page_title, "Organization settings")
        |> assign(:org, org)
        |> assign(:rename_form, to_form(%{"name" => org.name}, as: :organization))
        |> assign(:security_form_open?, false)
        |> assign(:pending_value, nil)
        |> assign(:admin_mfa_enabled?, SigraInstallGoldenTmp.Accounts.mfa_enabled?(scope.user))
        |> assign(:unenrolled_count, Organizations.count_members_without_mfa(scope))
        |> assign(:total_count, Organizations.count_members(scope))
        |> assign(:slug_form_open?, false)
        |> assign(:delete_form_open?, false)
        |> assign(:slug_form, blank_slug_form())
        |> assign(:delete_form, blank_delete_form())

      {:ok, socket}
    else
      {:ok,
       socket
       |> put_flash(:error, "You don't have permission to manage organization settings.")
       |> redirect(to: ~p"/organizations/#{org.slug}/members")}
    end
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div class="mx-auto max-w-2xl">
      <.header>
        Organization settings
        <:subtitle>{@org.name}</:subtitle>
      </.header>

      <%= # General (rename) — D-10 %>
      <section class="bg-base-200 p-6 rounded-lg mt-6">
        <h2 class="text-lg font-semibold">General</h2>
        <.form for={@rename_form} phx-submit="rename" class="mt-4">
          <.input field={@rename_form[:name]} label="Organization name" required />
          <.button type="submit" phx-disable-with="Saving...">Save name</.button>
        </.form>
      </section>

      <%= # Security (Phase 91 B2B-01) %>
      <section class="bg-base-200 p-6 rounded-lg mt-8">
        <h2 class="text-lg font-semibold">Security</h2>
        <p class="text-sm text-base-content/70 mt-1">
          Require members to enroll in MFA before they can access this organization.
        </p>

        <label class="mt-4 flex items-center justify-between gap-4">
          <div>
            <p class="font-medium">Require MFA for all members</p>
            <p class="text-sm text-base-content/70">
              <%= if @org.enforce_mfa_for_members do %>
                Members without MFA will be redirected to enroll on their next request.
              <% else %>
                Members can access this organization without MFA.
              <% end %>
            </p>
          </div>

          <input
            type="checkbox"
            class="toggle toggle-primary"
            checked={security_toggle_checked?(@org, @security_form_open?, @pending_value)}
            disabled={!@admin_mfa_enabled?}
            aria-describedby={if !@admin_mfa_enabled?, do: "org-mfa-admin-pre-flight"}
            phx-click="toggle_mfa_policy"
          />
        </label>

        <%= unless @admin_mfa_enabled? do %>
          <p class="text-error text-sm mt-2" id="org-mfa-admin-pre-flight">
            Enable MFA on your account first. You'd be locked out of this organization otherwise.
          </p>
          <.link navigate={~p"/users/settings/mfa"} class="link link-primary text-sm">
            Set up MFA on your account →
          </.link>
        <% end %>

        <%= if @security_form_open? and not is_nil(@pending_value) do %>
          <.form for={%{}} as={:mfa_policy} phx-submit="save_mfa_policy" class="mt-4 space-y-3">
            <%= if @unenrolled_count > 0 do %>
              <div role="alert" class="alert alert-warning alert-soft">
                <.icon name="hero-exclamation-triangle" class="w-5 h-5" />
                <span>
                  {@unenrolled_count} of {@total_count} members are not enrolled in MFA. They will be redirected to enroll on their next request to this organization.
                </span>
              </div>
            <% end %>

            <div class="flex gap-2">
              <.button type="submit" phx-disable-with="Saving...">
                {save_mfa_policy_label(@pending_value)}
              </.button>
              <.button type="button" phx-click="dismiss_mfa_policy" class="btn btn-ghost">
                {dismiss_mfa_policy_label(@pending_value)}
              </.button>
            </div>
          </.form>
        <% end %>
      </section>

      <%= # Slug (progressive disclosure + sudo + typed-confirm + 7-day alias) — D-11, D-12 %>
      <section class="bg-base-200 p-6 rounded-lg mt-8">
        <h2 class="text-lg font-semibold">Slug</h2>
        <p class="text-sm text-base-content/70 mt-1">
          Current: <code>{@org.slug}</code>
        </p>

        <%= if @slug_form_open? do %>
          <.form for={@slug_form} phx-submit="update_slug" class="mt-4 space-y-3">
            <.input field={@slug_form[:slug]} label="New slug" required />
            <.input
              field={@slug_form[:password]}
              type="password"
              label="Current password"
              autocomplete="current-password"
              required
            />
            <.input
              field={@slug_form[:confirm_slug]}
              label={"Type " <> @org.slug <> " to confirm"}
              required
            />

            <div role="alert" class="alert alert-warning alert-soft">
              <.icon name="hero-exclamation-triangle" class="w-5 h-5" />
              <span>
                Your current slug <code>{@org.slug}</code>
                will redirect to the new slug for 7 days, after which it becomes
                available to other organizations. Links and bookmarks using
                <code>{@org.slug}</code>
                will continue to work during that window.
              </span>
            </div>

            <div class="flex gap-2">
              <.button type="submit" class="btn btn-error" phx-disable-with="Updating...">
                Update slug
              </.button>
              <.button type="button" phx-click="close_slug_form" class="btn btn-ghost">
                Cancel
              </.button>
            </div>
          </.form>
        <% else %>
          <.button phx-click="open_slug_form" class="mt-4">Change slug</.button>
        <% end %>
      </section>

      <%= # Danger zone (soft-delete) — D-10 red-zone treatment, D-11 inline sudo %>
      <section class="mt-8 rounded-lg border border-error/40 border-l-4 border-l-error bg-base-100 p-6">
        <h2 class="text-lg font-semibold text-error">Danger zone</h2>
        <p class="text-sm mt-1">
          Soft-delete this organization. Members lose access immediately.
        </p>

        <%= if @delete_form_open? do %>
          <.form for={@delete_form} phx-submit="soft_delete" class="mt-4 space-y-3">
            <.input
              field={@delete_form[:password]}
              type="password"
              label="Current password"
              autocomplete="current-password"
              required
            />
            <.input
              field={@delete_form[:confirm_name]}
              label={"Type " <> @org.name <> " to confirm"}
              required
            />

            <div class="flex gap-2">
              <.button type="submit" class="btn btn-error" phx-disable-with="Deleting...">
                Delete organization permanently
              </.button>
              <.button type="button" phx-click="close_delete_form" class="btn btn-ghost">
                Cancel
              </.button>
            </div>
          </.form>
        <% else %>
          <.button phx-click="open_delete_form" class="btn btn-error btn-soft mt-4">
            Delete organization
          </.button>
        <% end %>
      </section>
    </div>
    """
  end

  # ──────────────────────────────────────────────────────────────────────────
  # Event handlers
  # ──────────────────────────────────────────────────────────────────────────

  @impl true
  def handle_event("rename", %{"organization" => params}, socket) do
    case Organizations.rename_organization(socket.assigns.current_scope, params) do
      {:ok, org} ->
        {:noreply,
         socket
         |> assign_current_org(org)
         |> assign(:rename_form, to_form(%{"name" => org.name}, as: :organization))
         |> put_flash(:info, "Name updated.")}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply,
         socket
         |> assign(:rename_form, to_form(changeset, as: :organization))}
    end
  end

  def handle_event("toggle_mfa_policy", _params, socket) do
    {:noreply,
     socket
     |> assign(:security_form_open?, true)
     |> assign(:pending_value, !socket.assigns.org.enforce_mfa_for_members)}
  end

  def handle_event("dismiss_mfa_policy", _params, socket) do
    {:noreply,
     socket
     |> assign(:security_form_open?, false)
     |> assign(:pending_value, nil)}
  end

  def handle_event("save_mfa_policy", _params, socket) do
    case Organizations.set_mfa_policy(socket.assigns.current_scope, socket.assigns.pending_value) do
      {:ok, org} ->
        {:noreply,
         socket
         |> assign_current_org(org)
         |> assign(:security_form_open?, false)
         |> assign(:pending_value, nil)
         |> assign(:unenrolled_count, Organizations.count_members_without_mfa(socket.assigns.current_scope))
         |> put_flash(:info, mfa_policy_flash(org))}

      {:error, :admin_must_enroll_first} ->
        {:noreply,
         socket
         |> assign(:security_form_open?, false)
         |> assign(:pending_value, nil)
         |> assign(:admin_mfa_enabled?, false)}

      {:error, :mfa_policy_aborted} ->
        {:noreply,
         socket
         |> assign(:security_form_open?, false)
         |> assign(:pending_value, nil)
         |> put_flash(:error, "Could not save the MFA policy. Please try again.")}

      {:error, %Ecto.Changeset{}} ->
        {:noreply,
         socket
         |> assign(:security_form_open?, false)
         |> assign(:pending_value, nil)
         |> put_flash(:error, "Could not save the MFA policy. Please try again.")}
    end
  end

  def handle_event("open_slug_form", _params, socket) do
    {:noreply,
     socket
     |> assign(:slug_form_open?, true)
     |> assign(:slug_form, blank_slug_form())}
  end

  def handle_event("close_slug_form", _params, socket) do
    {:noreply,
     socket
     |> assign(:slug_form_open?, false)
     |> assign(:slug_form, blank_slug_form())}
  end

  def handle_event("update_slug", %{"slug_change" => params}, socket) do
    case Organizations.update_slug(socket.assigns.current_scope, params) do
      {:ok, org} ->
        {:noreply,
         socket
         |> put_flash(:info, "Slug updated. The old slug redirects for 7 days.")
         |> redirect(to: ~p"/organizations/#{org.slug}/settings")}

      {:error, :invalid_password} ->
        {:noreply,
         assign(
           socket,
           :slug_form,
           params
           |> slug_form_with_errors([{:password, "That password is incorrect."}])
         )}

      {:error, %Ecto.Changeset{} = changeset} ->
        errors = remap_slug_errors(changeset, socket.assigns.org.slug)
        {:noreply, assign(socket, :slug_form, slug_form_with_errors(params, errors))}
    end
  end

  def handle_event("open_delete_form", _params, socket) do
    {:noreply,
     socket
     |> assign(:delete_form_open?, true)
     |> assign(:delete_form, blank_delete_form())}
  end

  def handle_event("close_delete_form", _params, socket) do
    {:noreply,
     socket
     |> assign(:delete_form_open?, false)
     |> assign(:delete_form, blank_delete_form())}
  end

  def handle_event("soft_delete", %{"delete_org" => params}, socket) do
    case Organizations.soft_delete_organization(socket.assigns.current_scope, params) do
      {:ok, _org} ->
        {:noreply,
         socket
         |> put_flash(:info, "Organization deleted.")
         |> redirect(to: ~p"/organizations")}

      {:error, :invalid_password} ->
        {:noreply,
         assign(
           socket,
           :delete_form,
           delete_form_with_errors(params, [{:password, "That password is incorrect."}])
         )}

      {:error, %Ecto.Changeset{} = changeset} ->
        errors = remap_delete_errors(changeset, socket.assigns.org.name)
        {:noreply, assign(socket, :delete_form, delete_form_with_errors(params, errors))}
    end
  end

  # ──────────────────────────────────────────────────────────────────────────
  # Form builders + error remapping
  #
  # The library's update_slug/4 and soft_delete_organization/4 functions use
  # a virtual changeset ({%{}, types}) and surface raw validation messages
  # like "is reserved" / "has already been taken" / "does not match current
  # slug". This LV remaps those into the exact UI-SPEC copy shown to users
  # (UI-SPEC §Copywriting Contract Error States).
  # ──────────────────────────────────────────────────────────────────────────

  defp blank_slug_form do
    to_form(%{"slug" => "", "password" => "", "confirm_slug" => ""}, as: :slug_change)
  end

  defp blank_delete_form do
    to_form(%{"password" => "", "confirm_name" => ""}, as: :delete_org)
  end

  defp can_manage_settings?(%{membership: %{role: role}}), do: role in [:owner, :admin]
  defp can_manage_settings?(_scope), do: false

  defp security_toggle_checked?(_org, true, pending_value) when is_boolean(pending_value),
    do: pending_value

  defp security_toggle_checked?(org, _open?, _pending),
    do: Map.get(org, :enforce_mfa_for_members, false)

  defp save_mfa_policy_label(true), do: "Require MFA for all members"
  defp save_mfa_policy_label(false), do: "Stop requiring MFA"

  defp dismiss_mfa_policy_label(true), do: "Don't require MFA"
  defp dismiss_mfa_policy_label(false), do: "Keep MFA required"

  defp mfa_policy_flash(%{enforce_mfa_for_members: true, name: name}),
    do: "MFA is now required for all members of #{name}."

  defp mfa_policy_flash(%{enforce_mfa_for_members: false, name: name}),
    do: "MFA is no longer required for members of #{name}."

  defp assign_current_org(socket, org) do
    scope = %{socket.assigns.current_scope | active_organization: org}

    socket
    |> assign(:org, org)
    |> assign(:current_scope, scope)
  end

  defp slug_form_with_errors(params, errors) do
    types = %{slug: :string, password: :string, confirm_slug: :string}

    changeset =
      {%{}, types}
      |> Ecto.Changeset.cast(normalize(params), Map.keys(types))

    changeset =
      Enum.reduce(errors, changeset, fn {field, msg}, acc ->
        Ecto.Changeset.add_error(acc, field, msg)
      end)

    to_form(%{changeset | action: :validate}, as: :slug_change)
  end

  defp delete_form_with_errors(params, errors) do
    types = %{password: :string, confirm_name: :string}

    changeset =
      {%{}, types}
      |> Ecto.Changeset.cast(normalize(params), Map.keys(types))

    changeset =
      Enum.reduce(errors, changeset, fn {field, msg}, acc ->
        Ecto.Changeset.add_error(acc, field, msg)
      end)

    to_form(%{changeset | action: :validate}, as: :delete_org)
  end

  defp normalize(params) when is_map(params), do: params
  defp normalize(_), do: %{}

  # Remap library-emitted slug error messages to the exact UI-SPEC copy.
  #
  # Library messages we expect:
  #   :slug         → "is reserved" (validate_exclusion)
  #   :slug         → "has invalid format" (validate_format)
  #   :slug         → "has already been taken" (unique_constraint — if surfaced)
  #   :confirm_slug → "does not match current slug" (validate_confirm)
  #   :password     → "can't be blank" (validate_required)
  #   :slug         → "can't be blank" (validate_required)
  defp remap_slug_errors(%Ecto.Changeset{errors: errors}, current_slug) do
    Enum.map(errors, fn {field, {msg, _opts}} ->
      {field, remap_slug_error(field, msg, current_slug)}
    end)
  end

  defp remap_slug_error(:slug, "is reserved", _current_slug),
    do: "That slug is reserved. Try another."

  defp remap_slug_error(:slug, "has already been taken", _current_slug),
    do: "That slug is already in use. Try another."

  defp remap_slug_error(:slug, "has invalid format", _current_slug),
    do: "Slugs can only contain lowercase letters, numbers, and hyphens."

  defp remap_slug_error(:confirm_slug, "does not match current slug", current_slug),
    do: "Type " <> current_slug <> " exactly to confirm."

  defp remap_slug_error(_field, msg, _current_slug), do: msg

  defp remap_delete_errors(%Ecto.Changeset{errors: errors}, org_name) do
    Enum.map(errors, fn {field, {msg, _opts}} ->
      {field, remap_delete_error(field, msg, org_name)}
    end)
  end

  defp remap_delete_error(:confirm_name, "does not match organization name", org_name),
    do: "Type " <> org_name <> " exactly to confirm."

  defp remap_delete_error(_field, msg, _org_name), do: msg
end
