defmodule SigraInstallGoldenTmpWeb.OrganizationSettingsLive do
  @moduledoc """
  Organization settings LiveView — three stacked sections on a single page
  (D-10): General (rename), Slug (change with 7-day redirect + inline sudo),
  and Danger Zone (soft-delete with inline sudo + typed-confirm of org name).

  All destructive actions use progressive disclosure (D-12): closed state
  renders a single button; clicking reveals an inline form with current
  password + typed-confirm fields. No modal dialogs, no sub-routes.

  Sudo is collected inline (D-11): the form carries a `current_password`
  field that the library's `update_slug/4` and `soft_delete_organization/4`
  functions verify via `Sigra.Crypto.verify_password/2`. On mismatch the
  library returns `{:error, :invalid_password}` and this LV surfaces the
  exact UI-SPEC copy `"That password is incorrect."` inline, without any
  redirect — form state is preserved.

  Non-owners are rejected at the plug layer by the `:org_scoped` pipeline
  with `Sigra.Plug.RequireMembership` restricted to `role: [:owner]`; this
  LV never mounts for them. Non-members receive 404 for enumeration safety
  (D-04), not 403.

  Generated by `mix sigra.install`. Customize freely — this module is
  owned by your application.
  """
  use SigraInstallGoldenTmpWeb, :live_view

  alias SigraInstallGoldenTmp.Organizations

  @impl true
  def mount(_params, _session, socket) do
    scope = socket.assigns.current_scope
    org = scope.active_organization

    socket =
      socket
      |> assign(:page_title, "Organization settings")
      |> assign(:org, org)
      |> assign(:enterprise_connection, Organizations.get_enterprise_connection(scope))
      |> assign(:rename_form, to_form(%{"name" => org.name}, as: :organization))
      |> assign(:slug_form_open?, false)
      |> assign(:delete_form_open?, false)
      |> assign(:slug_form, blank_slug_form())
      |> assign(:delete_form, blank_delete_form())
      |> assign_enterprise_form()

    {:ok, socket}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div class="mx-auto max-w-2xl">
      <.header>
        Organization settings
        <:subtitle>{@org.name}</:subtitle>
      </.header>

      <%= # General (rename) — D-10 %>
      <section class="bg-base-200 p-6 rounded-lg mt-6">
        <h2 class="text-lg font-semibold">General</h2>
        <.form for={@rename_form} phx-submit="rename" class="mt-4">
          <.input field={@rename_form[:name]} label="Organization name" required />
          <.button type="submit" phx-disable-with="Saving...">Save name</.button>
        </.form>
      </section>

      <%= # Slug (progressive disclosure + sudo + typed-confirm + 7-day alias) — D-11, D-12 %>
      <section class="bg-base-200 p-6 rounded-lg mt-8">
        <h2 class="text-lg font-semibold">Slug</h2>
        <p class="text-sm text-base-content/70 mt-1">
          Current: <code>{@org.slug}</code>
        </p>

        <%= if @slug_form_open? do %>
          <.form for={@slug_form} phx-submit="update_slug" class="mt-4 space-y-3">
            <.input field={@slug_form[:slug]} label="New slug" required />
            <.input
              field={@slug_form[:password]}
              type="password"
              label="Current password"
              autocomplete="current-password"
              required
            />
            <.input
              field={@slug_form[:confirm_slug]}
              label={"Type " <> @org.slug <> " to confirm"}
              required
            />

            <div role="alert" class="alert alert-warning alert-soft">
              <.icon name="hero-exclamation-triangle" class="w-5 h-5" />
              <span>
                Your current slug <code>{@org.slug}</code>
                will redirect to the new slug for 7 days, after which it becomes
                available to other organizations. Links and bookmarks using
                <code>{@org.slug}</code>
                will continue to work during that window.
              </span>
            </div>

            <div class="flex gap-2">
              <.button type="submit" class="btn btn-error" phx-disable-with="Updating...">
                Update slug
              </.button>
              <.button type="button" phx-click="close_slug_form" class="btn btn-ghost">
                Cancel
              </.button>
            </div>
          </.form>
        <% else %>
          <.button phx-click="open_slug_form" class="mt-4">Change slug</.button>
        <% end %>
      </section>

      <%= # Danger zone (soft-delete) — D-10 red-zone treatment, D-11 inline sudo %>
      <section class="mt-8 rounded-lg border border-error/40 border-l-4 border-l-error bg-base-100 p-6">
        <h2 class="text-lg font-semibold text-error">Danger zone</h2>
        <p class="text-sm mt-1">
          Soft-delete this organization. Members lose access immediately.
        </p>

        <%= if @delete_form_open? do %>
          <.form for={@delete_form} phx-submit="soft_delete" class="mt-4 space-y-3">
            <.input
              field={@delete_form[:password]}
              type="password"
              label="Current password"
              autocomplete="current-password"
              required
            />
            <.input
              field={@delete_form[:confirm_name]}
              label={"Type " <> @org.name <> " to confirm"}
              required
            />

            <div class="flex gap-2">
              <.button type="submit" class="btn btn-error" phx-disable-with="Deleting...">
                Delete organization permanently
              </.button>
              <.button type="button" phx-click="close_delete_form" class="btn btn-ghost">
                Cancel
              </.button>
            </div>
          </.form>
        <% else %>
          <.button phx-click="open_delete_form" class="btn btn-error btn-soft mt-4">
            Delete organization
          </.button>
        <% end %>
      </section>

      <section class="bg-base-200 p-6 rounded-lg mt-8">
        <div class="flex items-start justify-between gap-4">
          <div>
            <h2 class="text-lg font-semibold">Enterprise SSO</h2>
            <p class="text-sm text-base-content/70 mt-1">
              Configure an organization-bound enterprise connection. Saving keeps a draft;
              validate checks OIDC discovery; activate only succeeds when validation passes.
            </p>
          </div>
          <span class="badge badge-outline">
            {enterprise_status(@enterprise_connection)}
          </span>
        </div>

        <%= if @enterprise_connection && @enterprise_connection.last_validation_error do %>
          <div role="alert" class="alert alert-warning alert-soft mt-4">
            <.icon name="hero-exclamation-triangle" class="w-5 h-5" />
            <span>{@enterprise_connection.last_validation_error}</span>
          </div>
        <% end %>

        <.form for={@enterprise_form} phx-submit="submit_enterprise_connection" class="mt-4 space-y-4">
          <.input field={@enterprise_form[:display_name]} label="Display name" required />
          <.input
            field={@enterprise_form[:login_hint_domains]}
            label="Login hint domains"
            value={csv_value(@enterprise_form[:login_hint_domains].value)}
          />

          <.inputs_for :let={oidc_form} field={@enterprise_form[:oidc_settings]}>
            <div class="grid gap-4 md:grid-cols-2">
              <.input field={oidc_form[:issuer]} label="OIDC issuer" required />
              <.input field={oidc_form[:client_id]} label="Client ID" required />
              <.input
                field={oidc_form[:encrypted_client_secret]}
                type="password"
                label="Client secret"
                required
              />
              <.input
                field={oidc_form[:discovery_document_uri]}
                label="Discovery document URI"
              />
              <.input
                field={oidc_form[:client_authentication_method]}
                label="Client authentication method"
                required
              />
              <.input
                field={oidc_form[:scopes]}
                label="Scopes"
                value={csv_value(oidc_form[:scopes].value)}
                required
              />
            </div>
          </.inputs_for>

          <div class="flex flex-wrap gap-2">
            <.button type="submit" name="_action" value="save" phx-disable-with="Saving...">
              Save draft
            </.button>
            <.button type="submit" name="_action" value="validate" phx-disable-with="Validating...">
              Validate
            </.button>
            <.button type="submit" name="_action" value="activate" phx-disable-with="Activating...">
              Activate
            </.button>
            <.button
              :if={@enterprise_connection}
              type="button"
              phx-click="disable_enterprise_connection"
              class="btn btn-ghost"
            >
              Disable
            </.button>
          </div>
        </.form>
      </section>
    </div>
    """
  end

  # ──────────────────────────────────────────────────────────────────────────
  # Event handlers
  # ──────────────────────────────────────────────────────────────────────────

  @impl true
  def handle_event("rename", %{"organization" => params}, socket) do
    case Organizations.rename_organization(socket.assigns.current_scope, params) do
      {:ok, org} ->
        {:noreply,
         socket
         |> assign(:org, org)
         |> assign(:rename_form, to_form(%{"name" => org.name}, as: :organization))
         |> put_flash(:info, "Name updated.")}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply,
         socket
         |> assign(:rename_form, to_form(changeset, as: :organization))}
    end
  end

  def handle_event("open_slug_form", _params, socket) do
    {:noreply,
     socket
     |> assign(:slug_form_open?, true)
     |> assign(:slug_form, blank_slug_form())}
  end

  def handle_event("close_slug_form", _params, socket) do
    {:noreply,
     socket
     |> assign(:slug_form_open?, false)
     |> assign(:slug_form, blank_slug_form())}
  end

  def handle_event("update_slug", %{"slug_change" => params}, socket) do
    case Organizations.update_slug(socket.assigns.current_scope, params) do
      {:ok, org} ->
        {:noreply,
         socket
         |> put_flash(:info, "Slug updated. The old slug redirects for 7 days.")
         |> redirect(to: ~p"/organizations/#{org.slug}/settings")}

      {:error, :invalid_password} ->
        {:noreply,
         assign(
           socket,
           :slug_form,
           params
           |> slug_form_with_errors([{:password, "That password is incorrect."}])
         )}

      {:error, %Ecto.Changeset{} = changeset} ->
        errors = remap_slug_errors(changeset, socket.assigns.org.slug)
        {:noreply, assign(socket, :slug_form, slug_form_with_errors(params, errors))}
    end
  end

  def handle_event("open_delete_form", _params, socket) do
    {:noreply,
     socket
     |> assign(:delete_form_open?, true)
     |> assign(:delete_form, blank_delete_form())}
  end

  def handle_event("close_delete_form", _params, socket) do
    {:noreply,
     socket
     |> assign(:delete_form_open?, false)
     |> assign(:delete_form, blank_delete_form())}
  end

  def handle_event("soft_delete", %{"delete_org" => params}, socket) do
    case Organizations.soft_delete_organization(socket.assigns.current_scope, params) do
      {:ok, _org} ->
        {:noreply,
         socket
         |> put_flash(:info, "Organization deleted.")
         |> redirect(to: ~p"/organizations")}

      {:error, :invalid_password} ->
        {:noreply,
         assign(
           socket,
           :delete_form,
           delete_form_with_errors(params, [{:password, "That password is incorrect."}])
         )}

      {:error, %Ecto.Changeset{} = changeset} ->
        errors = remap_delete_errors(changeset, socket.assigns.org.name)
        {:noreply, assign(socket, :delete_form, delete_form_with_errors(params, errors))}
    end
  end

  def handle_event("submit_enterprise_connection", %{"enterprise_connection" => params, "_action" => action}, socket) do
    scope = socket.assigns.current_scope

    result =
      case action do
        "save" -> Organizations.save_enterprise_connection(scope, params)
        "validate" -> Organizations.validate_enterprise_connection(scope, params)
        "activate" -> Organizations.activate_enterprise_connection(scope, params)
      end

    case result do
      {:ok, connection} ->
        {:noreply,
         socket
         |> assign(:enterprise_connection, connection)
         |> assign_enterprise_form()
         |> put_flash(:info, enterprise_flash(action))}

      {:error, :validation_failed} ->
        {:noreply,
         socket
         |> assign(:enterprise_connection, Organizations.get_enterprise_connection(scope))
         |> assign_enterprise_form()
         |> put_flash(:error, "Enterprise connection stayed non-active because validation failed.")}

      {:error, :validation_failed, connection} ->
        {:noreply,
         socket
         |> assign(:enterprise_connection, connection)
         |> assign_enterprise_form()
         |> put_flash(:error, "Enterprise connection stayed non-active because validation failed.")}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :enterprise_form, to_form(%{changeset | action: :validate}, as: :enterprise_connection))}
    end
  end

  def handle_event("disable_enterprise_connection", _params, socket) do
    case Organizations.disable_enterprise_connection(socket.assigns.current_scope) do
      {:ok, connection} ->
        {:noreply,
         socket
         |> assign(:enterprise_connection, connection)
         |> assign_enterprise_form()
         |> put_flash(:info, "Enterprise connection disabled.")}

      {:error, :not_found} ->
        {:noreply, put_flash(socket, :error, "No enterprise connection is configured yet.")}
    end
  end

  # ──────────────────────────────────────────────────────────────────────────
  # Form builders + error remapping
  #
  # The library's update_slug/4 and soft_delete_organization/4 functions use
  # a virtual changeset ({%{}, types}) and surface raw validation messages
  # like "is reserved" / "has already been taken" / "does not match current
  # slug". This LV remaps those into the exact UI-SPEC copy shown to users
  # (UI-SPEC §Copywriting Contract Error States).
  # ──────────────────────────────────────────────────────────────────────────

  defp blank_slug_form do
    to_form(%{"slug" => "", "password" => "", "confirm_slug" => ""}, as: :slug_change)
  end

  defp blank_delete_form do
    to_form(%{"password" => "", "confirm_name" => ""}, as: :delete_org)
  end

  defp slug_form_with_errors(params, errors) do
    types = %{slug: :string, password: :string, confirm_slug: :string}

    changeset =
      {%{}, types}
      |> Ecto.Changeset.cast(normalize(params), Map.keys(types))

    changeset =
      Enum.reduce(errors, changeset, fn {field, msg}, acc ->
        Ecto.Changeset.add_error(acc, field, msg)
      end)

    to_form(%{changeset | action: :validate}, as: :slug_change)
  end

  defp delete_form_with_errors(params, errors) do
    types = %{password: :string, confirm_name: :string}

    changeset =
      {%{}, types}
      |> Ecto.Changeset.cast(normalize(params), Map.keys(types))

    changeset =
      Enum.reduce(errors, changeset, fn {field, msg}, acc ->
        Ecto.Changeset.add_error(acc, field, msg)
      end)

    to_form(%{changeset | action: :validate}, as: :delete_org)
  end

  defp normalize(params) when is_map(params), do: params
  defp normalize(_), do: %{}

  defp assign_enterprise_form(socket) do
    scope = socket.assigns.current_scope

    changeset =
      Organizations.change_enterprise_connection(
        scope,
        default_enterprise_attrs(socket.assigns[:enterprise_connection])
      )

    assign(socket, :enterprise_form, to_form(changeset, as: :enterprise_connection))
  end

  defp default_enterprise_attrs(nil) do
    %{
      "display_name" => "",
      "login_hint_domains" => "",
      "oidc_settings" => %{
        "issuer" => "",
        "discovery_document_uri" => "",
        "client_id" => "",
        "encrypted_client_secret" => "",
        "client_authentication_method" => "client_secret_basic",
        "scopes" => "openid, profile, email"
      }
    }
  end

  defp default_enterprise_attrs(_connection), do: %{}

  defp enterprise_status(nil), do: "draft"
  defp enterprise_status(connection), do: connection.status

  defp enterprise_flash("save"), do: "Enterprise connection draft saved."
  defp enterprise_flash("validate"), do: "Enterprise connection validated."
  defp enterprise_flash("activate"), do: "Enterprise connection activated."

  defp csv_value(value) when is_list(value), do: Enum.join(value, ", ")
  defp csv_value(value) when is_binary(value), do: value
  defp csv_value(_value), do: ""

  # Remap library-emitted slug error messages to the exact UI-SPEC copy.
  #
  # Library messages we expect:
  #   :slug         → "is reserved" (validate_exclusion)
  #   :slug         → "has invalid format" (validate_format)
  #   :slug         → "has already been taken" (unique_constraint — if surfaced)
  #   :confirm_slug → "does not match current slug" (validate_confirm)
  #   :password     → "can't be blank" (validate_required)
  #   :slug         → "can't be blank" (validate_required)
  defp remap_slug_errors(%Ecto.Changeset{errors: errors}, current_slug) do
    Enum.map(errors, fn {field, {msg, _opts}} ->
      {field, remap_slug_error(field, msg, current_slug)}
    end)
  end

  defp remap_slug_error(:slug, "is reserved", _current_slug),
    do: "That slug is reserved. Try another."

  defp remap_slug_error(:slug, "has already been taken", _current_slug),
    do: "That slug is already in use. Try another."

  defp remap_slug_error(:slug, "has invalid format", _current_slug),
    do: "Slugs can only contain lowercase letters, numbers, and hyphens."

  defp remap_slug_error(:confirm_slug, "does not match current slug", current_slug),
    do: "Type " <> current_slug <> " exactly to confirm."

  defp remap_slug_error(_field, msg, _current_slug), do: msg

  defp remap_delete_errors(%Ecto.Changeset{errors: errors}, org_name) do
    Enum.map(errors, fn {field, {msg, _opts}} ->
      {field, remap_delete_error(field, msg, org_name)}
    end)
  end

  defp remap_delete_error(:confirm_name, "does not match organization name", org_name),
    do: "Type " <> org_name <> " exactly to confirm."

  defp remap_delete_error(_field, msg, _org_name), do: msg
end
