defmodule SigraInstallGoldenTmpWeb.SettingsLive do
  @moduledoc """
  LiveView for account settings management.

  Provides three sections:
  - **Email** — view current email, request change, cancel pending change
  - **Password** — change password (or set password for OAuth-only users)
  - **Delete account** — schedule deletion with grace period, cancel pending deletion

  Adapts for OAuth-only users (no current password field), displays inline
  status indicators for pending email changes and scheduled deletions, and
  shows a force-password-change banner when required.

  Generated by `mix sigra.install --live`. Customize freely -- this module
  is owned by your application.
  """
  use SigraInstallGoldenTmpWeb, :live_view
  import SigraInstallGoldenTmpWeb.SigraAuthComponents

  alias SigraInstallGoldenTmp.Accounts, as: Auth

  def mount(_params, _session, socket) do
    user = socket.assigns.current_scope.user
    deletion_status = Auth.deletion_status(user)

    {:ok,
     assign(socket,
       page_title: "Account Settings",
       pending_email_change?: user.pending_email != nil,
       deletion_status: deletion_status,
       scheduled_deletion_date: scheduled_deletion_date(user),
       has_password?: user.hashed_password != nil,
       force_password_change?: Auth.must_change_password?(user),
       email_form: to_form(%{"email" => ""}, as: "email"),
       password_form: to_form(%{}, as: "password")
     )}
  end

  def handle_params(%{"token" => token}, _uri, %{assigns: %{live_action: :confirm_email}} = socket) do
    case Auth.confirm_email_change(token) do
      {:ok, _user} ->
        {:noreply,
         socket
         |> put_flash(:info, "Your email has been updated.")
         |> push_navigate(to: ~p"/users/settings")}

      :error ->
        {:noreply,
         socket
         |> put_flash(:error, "This confirmation link is invalid or has expired. Request a new email change from your settings.")
         |> push_navigate(to: ~p"/users/settings")}
    end
  end

  def handle_params(_params, _uri, socket), do: {:noreply, socket}

  def render(assigns) do
    ~H"""
    <.sigra_auth_page>
      <div class="mx-auto max-w-2xl">
      <.header>
        Account Settings
        <:subtitle>Manage your email, password, and account.</:subtitle>
      </.header>

      <%= # Force password change banner (D-58) %>
      <div
        :if={@force_password_change?}
        class="mt-4 rounded-lg bg-yellow-50 p-4 border border-yellow-200"
      >
        <p class="text-sm font-semibold text-yellow-700">
          You must change your password before you can continue using your account.
        </p>
      </div>

      <div class="mt-8 space-y-6">
        <%= # Email Section (D-59) %>
        <div id="email" class="bg-gray-50 p-4 rounded-lg border border-gray-200">
          <span class="text-sm font-semibold">Email address</span>
          <p class="mt-2 text-sm text-gray-500">
            Current email: {@current_scope.user.email}
          </p>

          <%= if @pending_email_change? do %>
            <div class="mt-2 text-sm">
              <span class="text-yellow-700">
                Changing to: {@current_scope.user.pending_email} (awaiting confirmation)
              </span>
              <p class="text-gray-500 mt-1">
                We sent a confirmation link to {@current_scope.user.pending_email}. Check your inbox.
              </p>
              <button
                phx-click="cancel_email_change"
                class="mt-2 text-sm text-red-600 hover:underline"
              >
                Cancel email change
              </button>
            </div>
          <% else %>
            <.form for={@email_form} phx-submit="request_email_change" class="mt-4">
              <.input field={@email_form[:email]} type="email" label="New email" required />
              <.button class="mt-2">Update email</.button>
            </.form>
          <% end %>
        </div>

        <%= # Password Section (D-45, D-60) %>
        <div id="password" class="bg-gray-50 p-4 rounded-lg border border-gray-200">
          <span class="text-sm font-semibold">Password</span>
          <%= if @has_password? do %>
            <.form for={@password_form} phx-submit="change_password" class="mt-4">
              <.input
                field={@password_form[:current_password]}
                type="password"
                label="Current password"
                autocomplete="current-password"
                required
              />
              <.input
                field={@password_form[:password]}
                type="password"
                label="New password"
                autocomplete="new-password"
                required
              />
              <.input
                field={@password_form[:password_confirmation]}
                type="password"
                label="Confirm new password"
                autocomplete="new-password"
                required
              />
              <.button class="mt-2">Change password</.button>
            </.form>
          <% else %>
            <p class="mt-2 text-sm text-gray-500">
              You signed in with a social provider. Set a password to enable email login.
            </p>
            <.form for={@password_form} phx-submit="set_password" class="mt-4">
              <.input
                field={@password_form[:password]}
                type="password"
                label="New password"
                autocomplete="new-password"
                required
              />
              <.input
                field={@password_form[:password_confirmation]}
                type="password"
                label="Confirm new password"
                autocomplete="new-password"
                required
              />
              <.button class="mt-2">Set a password</.button>
            </.form>
          <% end %>
        </div>

        <%= # Deletion Section (D-30, D-57) %>
        <div id="delete" class="bg-gray-50 p-4 rounded-lg border border-gray-200 border-l-4 border-red-500">
          <span class="text-sm font-semibold">Delete account</span>
          <%= case @deletion_status do %>
            <% {:scheduled, _days} -> %>
              <p class="mt-2 text-sm text-red-600">
                Your account is scheduled for deletion on {@scheduled_deletion_date}.
              </p>
              <button
                phx-click="cancel_deletion"
                class="mt-2 text-sm bg-white border border-gray-300 rounded px-3 py-1 hover:bg-gray-50"
              >
                Cancel deletion
              </button>
            <% :not_scheduled -> %>
              <p class="mt-2 text-sm text-gray-500">
                Schedule account deletion according to your configured deletion strategy.
                After the grace period expires, Sigra finalizes the account lifecycle according to that strategy.
              </p>
              <button
                phx-click="confirm_delete"
                data-confirm="Are you sure? Your account will be deactivated immediately, all sessions will be signed out, and finalization will follow your configured deletion strategy."
                class="mt-4 bg-red-600 hover:bg-red-700 text-white text-sm font-semibold py-2 px-4 rounded"
              >
                Delete my account
              </button>
            <% _ -> %>
          <% end %>
        </div>
      </div>
      </div>
    </.sigra_auth_page>
    """
  end

  # -- Event Handlers --

  def handle_event("request_email_change", %{"email" => %{"email" => new_email}}, socket) do
    user = socket.assigns.current_scope.user

    case Auth.request_email_change(user, new_email) do
      {:ok, _user, _token} ->
        {:noreply,
         socket
         |> put_flash(:info, "We sent a confirmation link to #{new_email}. Your current email stays active until you confirm.")
         |> assign(pending_email_change?: true)}

      {:error, changeset} ->
        {:noreply,
         socket
         |> assign(email_form: to_form(changeset, as: "email"))}
    end
  end

  def handle_event("cancel_email_change", _params, socket) do
    user = socket.assigns.current_scope.user

    case Auth.cancel_email_change(user) do
      {:ok, _user} ->
        {:noreply,
         socket
         |> put_flash(:info, "Email change cancelled. Your email remains #{user.email}.")
         |> assign(pending_email_change?: false)}

      {:error, _changeset} ->
        {:noreply,
         socket
         |> put_flash(:error, "Something went wrong while processing your request. Please try again.")}
    end
  end

  def handle_event("change_password", %{"password" => params}, socket) do
    user = socket.assigns.current_scope.user
    current_password = params["current_password"]
    attrs = Map.take(params, ["password", "password_confirmation"])

    case Auth.change_password(user, current_password, attrs) do
      {:ok, _user} ->
        {:noreply,
         socket
         |> put_flash(:info, "Your password has been changed. All other sessions have been signed out.")
         |> assign(
           force_password_change?: false,
           password_form: to_form(%{}, as: "password")
         )}

      {:error, changeset} ->
        {:noreply,
         socket
         |> assign(password_form: to_form(changeset, as: "password"))}
    end
  end

  def handle_event("set_password", %{"password" => params}, socket) do
    user = socket.assigns.current_scope.user
    attrs = Map.take(params, ["password", "password_confirmation"])

    case Auth.set_password(user, attrs) do
      {:ok, _user} ->
        {:noreply,
         socket
         |> put_flash(:info, "Password set successfully. You can now sign in with email and password.")
         |> assign(
           has_password?: true,
           password_form: to_form(%{}, as: "password")
         )}

      {:error, changeset} ->
        {:noreply,
         socket
         |> assign(password_form: to_form(changeset, as: "password"))}
    end
  end

  def handle_event("confirm_delete", _params, socket) do
    user = socket.assigns.current_scope.user

    case Auth.schedule_deletion(user) do
      {:ok, updated_user, scheduled_date} ->
        {:noreply,
         socket
         |> put_flash(:info, "Your account is scheduled for deletion on #{scheduled_date}. You can cancel this from your settings.")
         |> assign(
           current_scope: %{socket.assigns.current_scope | user: updated_user},
           deletion_status: Auth.deletion_status(updated_user),
           scheduled_deletion_date: to_string(scheduled_date)
         )}

      {:error, reason} ->
        message =
          case reason do
            :already_scheduled -> "Your account is already scheduled for deletion."
            :cooldown -> "You recently cancelled a deletion request. Please wait before requesting again."
            _ -> "Something went wrong while processing your request. Please try again."
          end

        {:noreply, socket |> put_flash(:error, message)}
    end
  end

  def handle_event("cancel_deletion", _params, socket) do
    user = socket.assigns.current_scope.user

    case Auth.cancel_deletion(user) do
      {:ok, updated_user} ->
        {:noreply,
         socket
         |> put_flash(:info, "Account deletion cancelled. Your account is active again.")
         |> assign(
           current_scope: %{socket.assigns.current_scope | user: updated_user},
           deletion_status: :not_scheduled,
           scheduled_deletion_date: nil
         )}

      {:error, _reason} ->
        {:noreply,
         socket
         |> put_flash(:error, "Something went wrong while processing your request. Please try again.")}
    end
  end

  # -- Private Helpers --

  defp scheduled_deletion_date(%{scheduled_deletion_at: nil}), do: nil

  defp scheduled_deletion_date(%{scheduled_deletion_at: dt}) do
    Calendar.strftime(dt, "%B %d, %Y")
  end

  defp scheduled_deletion_date(_), do: nil
end
