defmodule ExampleWeb.Auth.SudoHTML do
  @moduledoc """
  HTML templates for sudo/re-authentication mode.

  Single-purpose page: password field + confirm button, centered in a
  narrow column matching the login form width. Follows GitHub's sudo
  pattern per D-20 to D-23.

  Generated by `mix sigra.install`. Customize freely -- this module
  is owned by your application.
  """

  use ExampleWeb, :html

  def new(assigns) do
    ~H"""
    <section class="vt-auth" data-theme="system" data-testid="sudo">
      <div class="vt-auth__panel">
        <a href={~p"/"} class="vt-brand">
          <img src={~p"/images/tasklane-mark.svg"} alt="Tasklane logo" class="vt-brand__mark" />
          <span>
            <span class="vt-brand__name">Tasklane</span>
            <span class="vt-brand__tag">Work tracking for teams</span>
          </span>
        </a>

        <div class="vt-auth__intro">
          <p class="vt-kicker">Confirm it's you</p>
          <h1 class="vt-auth__title">Re-enter your password</h1>
          <p class="vt-auth__copy">
            For your security, please re-enter your password to continue.
          </p>
        </div>

        <.form
          :let={f}
          for={@form}
          action={~p"/users/sudo"}
          method="post"
          class="vt-auth__form vt-auth__form--primary"
        >
          <input type="hidden" name="sudo[return_to]" value={@return_to} />
          <.input
            field={f[:password]}
            type="password"
            label="Password"
            autocomplete="current-password"
            autofocus
            required
          />
          <.button class="vt-btn vt-btn--primary vt-btn--block">Confirm password</.button>
        </.form>

        <p>
          <.link navigate={@return_to || ~p"/"} class="vt-link">Go back</.link>
        </p>
      </div>
    </section>
    """
  end
end
