defmodule <%= web_module %>.APITokenController do
  @moduledoc """
  JSON API controller for managing personal access tokens.

  Provides CRUD endpoints for API token management:

    - `GET /api/tokens` -- list active tokens (paginated)
    - `POST /api/tokens` -- create a new token (returns raw key once)
    - `DELETE /api/tokens/:id` -- revoke a specific token
    - `DELETE /api/tokens` -- revoke all tokens for the current user

  All endpoints require bearer authentication with `api_tokens:read` or
  `api_tokens:write` scopes. Token creation requires sudo mode.

  Generated by `mix sigra.install --api`. Customize freely -- this
  module is owned by your application.
  """

  use <%= web_module %>, :controller

  alias <%= context_module %>, as: Auth

  @impersonation_denial_message "You can't manage API tokens while impersonating."

  @doc "Lists active API tokens for the current user (paginated)."
  def index(conn, params) do
    config = Auth.sigra_config()
    scope = conn.assigns.current_scope
    user = scope_user(scope)

    opts = [
      cursor: params["cursor"],
      limit: parse_limit(params["limit"])
    ]

    {tokens, next_cursor} = Auth.list_api_tokens(user.id, opts)

    json(conn, %{
      data: Enum.map(tokens, &token_json/1),
      next_cursor: next_cursor
    })
  end

  @doc "Creates a new API token. Returns the raw key only in this response."
  def create(conn, %{"token" => token_params}) do
    config = Auth.sigra_config()
    scope = conn.assigns.current_scope
    user = scope_user(scope)

    attrs = %{
      name: token_params["name"],
      scopes: token_params["scopes"] || [],
      expires_at: parse_expires_at(token_params["expires_at"])
    }

    case Auth.create_api_token(user, attrs, scope: scope) do
      {:ok, raw_key, token} ->
        conn
        |> put_status(:created)
        |> json(%{data: Map.merge(token_json(token), %{raw_key: raw_key})})

      {:error, :impersonation_forbidden, message} ->
        impersonation_forbidden(conn, message)

      {:error, changeset} when is_struct(changeset, Ecto.Changeset) ->
        conn
        |> put_status(:unprocessable_entity)
        |> json(%{error: "validation_error", details: changeset_errors(changeset)})

      {:error, reason} ->
        conn
        |> put_status(:unprocessable_entity)
        |> json(%{error: to_string(reason)})
    end
  end

  @doc "Revokes a specific API token by ID."
  def delete(conn, %{"id" => id}) do
    case Auth.revoke_api_token(id, scope: conn.assigns.current_scope) do
      {:ok, _token} ->
        json(conn, %{ok: true})

      {:error, :impersonation_forbidden, message} ->
        impersonation_forbidden(conn, message)

      {:error, :not_found} ->
        conn |> put_status(:not_found) |> json(%{error: "not_found"})
    end
  end

  @doc "Revokes all API tokens for the current user."
  def delete_all(conn, _params) do
    scope = conn.assigns.current_scope
    user = scope_user(scope)

    case Auth.revoke_all_api_tokens(user, scope: scope) do
      {:ok, count} ->
        json(conn, %{ok: true, revoked_count: count})

      {:error, :impersonation_forbidden, message} ->
        impersonation_forbidden(conn, message)
    end
  end

  # -- Private helpers --

  defp impersonation_forbidden(conn, message \\ @impersonation_denial_message) do
    conn
    |> put_status(:forbidden)
    |> json(%{error: "impersonation_forbidden", message: message})
  end

  defp scope_user(%{user: user}), do: user
  defp scope_user(user), do: user

  defp token_json(token) do
    %{
      id: token.id,
      name: token.name,
      prefix: token.prefix,
      scopes: token.scopes || [],
      last_used_at: token.last_used_at,
      expires_at: token.expires_at,
      inserted_at: token.inserted_at
    }
  end

  defp parse_limit(nil), do: 25
  defp parse_limit(val) when is_binary(val) do
    case Integer.parse(val) do
      {n, _} when n > 0 and n <= 100 -> n
      _ -> 25
    end
  end
  defp parse_limit(val) when is_integer(val) and val > 0 and val <= 100, do: val
  defp parse_limit(_), do: 25

  defp parse_expires_at(nil), do: nil
  defp parse_expires_at(val) when is_binary(val) do
    case DateTime.from_iso8601(val) do
      {:ok, dt, _offset} -> dt
      _ -> nil
    end
  end
  defp parse_expires_at(_), do: nil

  defp changeset_errors(changeset) do
    Ecto.Changeset.traverse_errors(changeset, fn {msg, opts} ->
      Regex.replace(~r"%{(\w+)}", msg, fn _, key ->
        opts |> Keyword.get(String.to_existing_atom(key), key) |> to_string()
      end)
    end)
  end
end
