defmodule <%= web_module %>.ConfirmationLive do
  @moduledoc """
  LiveView for email confirmation flow.

  Provides explicit link confirmation, code entry, expired token handling,
  and resend functionality.

  Generated by `mix sigra.install --live`. Customize freely -- this module
  is owned by your application.
  """
  use <%= web_module %>, :live_view
  import <%= web_module %>.SigraAuthComponents

  use Gettext, backend: <%= web_module %>.Gettext

  alias <%= context_module %>, as: Auth

  def render(assigns) do
    ~H"""
    <.sigra_auth_page flash={@flash}>
      <div class="sigra-auth-flow sigra-auth-stack sigra-auth-stack--6">
        <%%= case @live_action do %>
        <%% :confirm -> %>
          <.header>
            {dgettext("sigra", "Confirm your email")}
            <:subtitle>
              {dgettext("sigra", "Confirm that you own this email address.")}
            </:subtitle>
          </.header>

          <.form for={@link_form} id="confirmation_link_form" phx-submit="confirm_link">
            <.sigra_auth_button phx-disable-with={dgettext("sigra", "Confirming...")}
              class="sigra-auth-action sigra-auth-action--primary sigra-auth-action--block">
              {dgettext("sigra", "Confirm email")} <span aria-hidden="true">&rarr;</span>
            </.sigra_auth_button>
          </.form>

        <%% :confirmed -> %>
          <.header>
            {dgettext("sigra", "Email confirmed")}
            <:subtitle>
              {dgettext("sigra", "Your email has been confirmed.")}
            </:subtitle>
          </.header>

          <p class="sigra-auth-copy sigra-auth-copy--center">
            <.link navigate={~p"/users/log_in"}>
              {dgettext("sigra", "Log in")}
            </.link>
          </p>

        <%% :new -> %>
          <.header>
            {dgettext("sigra", "Confirm your email")}
            <:subtitle>
              {dgettext("sigra", "Enter the 6-digit code we sent to your email, or check your inbox for a confirmation link.")}
            </:subtitle>
          </.header>

          <.form
            for={@form}
            id="confirmation_form"
            phx-change="validate"
            phx-submit="confirm"
            class="sigra-auth-stack sigra-auth-stack--4"
          >
            <.input
              field={@form[:code]}
              type="text"
              label={dgettext("sigra", "Confirmation code")}
              inputmode="numeric"
              autocomplete="one-time-code"
              maxlength="6"
              pattern="[0-9]{6}"
              aria-label={dgettext("sigra", "Confirmation code")}
              class="sigra-auth-code-input"
              required
            />

            <.sigra_auth_button phx-disable-with={dgettext("sigra", "Confirming...")} class="sigra-auth-action sigra-auth-action--primary sigra-auth-action--block">
              {dgettext("sigra", "Confirm email")} <span aria-hidden="true">&rarr;</span>
            </.sigra_auth_button>
          </.form>

          <p class="sigra-auth-copy sigra-auth-copy--center">
            <button type="button" phx-click="resend" class="sigra-auth-action sigra-auth-action--ghost">
              {dgettext("sigra", "Didn't receive a code?")}
            </button>
          </p>

        <%% :already_confirmed -> %>
          <.header>
            {dgettext("sigra", "Email already confirmed")}
            <:subtitle>
              {dgettext("sigra", "Your email was already confirmed. You can log in below.")}
            </:subtitle>
          </.header>

          <p class="sigra-auth-copy sigra-auth-copy--center">
            <.link navigate={~p"/users/log_in"}>
              {dgettext("sigra", "Log in")}
            </.link>
          </p>

        <%% :sign_in_required -> %>
          <.header>
            {dgettext("sigra", "Sign in required")}
            <:subtitle>
              {dgettext("sigra", "Please sign in to confirm your email.")}
            </:subtitle>
          </.header>

          <p class="sigra-auth-copy sigra-auth-copy--center">
            <.link navigate={~p"/users/log_in"}>
              {dgettext("sigra", "Log in")}
            </.link>
          </p>

        <%% :expired -> %>
          <.header>
            {dgettext("sigra", "Confirmation link expired")}
            <:subtitle>
              {dgettext("sigra", "This confirmation link has expired or was already used.")}
            </:subtitle>
          </.header>

          <.sigra_auth_button phx-click="resend" phx-disable-with={dgettext("sigra", "Sending...")} class="sigra-auth-action sigra-auth-action--primary sigra-auth-action--block">
            {dgettext("sigra", "Send new confirmation email")} <span aria-hidden="true">&rarr;</span>
          </.sigra_auth_button>
        <%% end %>
      </div>
    </.sigra_auth_page>
    """
  end

  def mount(_params, _session, socket) do
    form = to_form(%{"code" => ""}, as: "confirmation")
    link_form = to_form(%{}, as: "confirmation_link")

    {:ok, assign(socket, form: form, link_form: link_form, live_action: :new)}
  end

  def handle_params(%{"token" => token}, _uri, socket) do
    {:noreply, assign(socket, confirmation_token: token, live_action: :confirm)}
  end

  def handle_params(_params, _uri, socket) do
    {:noreply, socket}
  end

  def handle_event("confirm_link", _params, socket) do
    case Auth.confirm_user(socket.assigns.confirmation_token) do
      {:ok, _user} ->
        {:noreply,
         socket
         |> put_flash(:info, dgettext("sigra", "Your email has been confirmed."))
         |> assign(live_action: :confirmed)}

      {:error, :already_confirmed} ->
        {:noreply, assign(socket, live_action: :already_confirmed)}

      {:error, :token_expired} ->
        {:noreply, assign(socket, live_action: :expired)}

      {:error, :token_invalid} ->
        {:noreply,
         socket
         |> put_flash(:error, dgettext("sigra", "This confirmation link is invalid or has expired."))
         |> assign(live_action: :new)}
    end
  end

  def handle_event("validate", %{"confirmation" => %{"code" => code}}, socket) do
    form = to_form(%{"code" => code}, as: "confirmation")
    socket = assign(socket, form: form)

    # Call the confirm path directly when the user has typed a
    # full 6-digit code instead of dispatching via `send(self(), …)`. The
    # mailbox round-trip allowed a stale 6-digit prefix to fire after the
    # user typed a 7th character, wasting an attempt against the rate
    # limiter's max_code_attempts counter.
    if String.length(code) == 6 and Regex.match?(~r/^\d{6}$/, code) do
      do_confirm(socket, code)
    else
      {:noreply, socket}
    end
  end

  def handle_event("confirm", %{"confirmation" => %{"code" => code}}, socket) do
    do_confirm(socket, code)
  end

  def handle_event("resend", _params, socket) do
    with_confirmation_user(socket, fn socket, user ->
      case Auth.deliver_user_confirmation_instructions(user, &url(socket, ~p"/users/confirm/#{&1}")) do
        {:ok, _} ->
          {:noreply, put_flash(socket, :info, dgettext("sigra", "A new confirmation email has been sent."))}

        {:error, :already_confirmed} ->
          {:noreply,
           socket
           |> put_flash(:info, dgettext("sigra", "Your email is already confirmed."))
           |> redirect(to: ~p"/")}
      end
    end)
  end

  defp do_confirm(socket, code) do
    with_confirmation_user(socket, fn socket, user ->
      case Auth.confirm_user_by_code(user, code) do
        {:ok, _user} ->
          {:noreply,
           socket
           |> put_flash(:info, dgettext("sigra", "Your email has been confirmed."))
           |> redirect(to: ~p"/")}

        {:error, :invalid_code} ->
          form = to_form(%{"code" => ""}, as: "confirmation")

          {:noreply,
           socket
           |> put_flash(:error, dgettext("sigra", "Invalid confirmation code. Please try again."))
           |> assign(form: form)}

        {:error, :rate_limited} ->
          {:noreply,
           put_flash(socket, :error, dgettext("sigra", "Too many attempts. Please wait a few minutes before trying again."))}

        {:error, :already_confirmed} ->
          {:noreply,
           socket
           |> put_flash(:info, dgettext("sigra", "Your email is already confirmed."))
           |> redirect(to: ~p"/")}
      end
    end)
  end

  defp with_confirmation_user(socket, callback) do
    case socket.assigns[:current_scope] do
      %{user: user} when not is_nil(user) ->
        callback.(socket, user)

      _ ->
        {:noreply, assign(socket, :live_action, :sign_in_required)}
    end
  end
end
