defmodule <%= web_module %>.MFASettingsLive do
  @moduledoc """
  LiveView for MFA enrollment, settings, and management.

  Handles the full MFA lifecycle:
  - Enrollment: QR code display, manual key, confirmation code entry
  - Backup codes: display, copy, download, acknowledgment
  - Settings: enabled status, backup code count, disable, regenerate
  - Trust management: revoke all trusted browsers

  This component is designed to be embedded in the user settings page.

  Generated by `mix sigra.install --live`. Customize freely -- this module
  is owned by your application.
  """
  use <%= web_module %>, :live_view

  alias <%= context_module %>, as: Auth

  @doc """
  Mount the MFA settings LiveView.

  Checks current MFA status and sets appropriate initial state.
  """
  def mount(_params, _session, socket) do
    user = socket.assigns.current_scope.user
    mfa_status = Auth.mfa_status(user)
<%= if passkeys? do %>
    passkeys = Auth.passkeys_for_user(user)
    passkey_count = Auth.passkey_count_for_user(user)
<% else %>
    passkeys = []
    passkey_count = 0
<% end %>

    {:ok,
     assign(socket,
       mfa_enabled: mfa_status.enabled,
       passkeys: passkeys,
       passkey_count: passkey_count,
       passkey_status: :idle,
       passkey_notice: nil,
       renaming_passkey_id: nil,
       rename_form: to_form(%{"nickname" => ""}, as: "passkey"),
       deleting_passkey_id: nil,
       enrollment_step: nil,
       svg: nil,
       base32_secret: nil,
       raw_secret: nil,
       backup_codes: [],
       backup_remaining: mfa_status.backup_codes_remaining,
       show_disable: false,
       show_regenerate: false,
       codes_acknowledged: false,
       enroll_form: to_form(%{"code" => ""}, as: "enroll"),
       disable_form: to_form(%{"code" => ""}, as: "disable"),
       regenerate_form: to_form(%{"code" => ""}, as: "regenerate"),
       page_title: "MFA Settings"
     )}
  end

  def render(assigns) do
    ~H"""
    <div class="mx-auto max-w-2xl">
      <%%= if @mfa_enabled do %>
        <%% # Surface 3: MFA Settings Card %>
        <div class="bg-gray-50 p-4 rounded-lg border border-gray-200">
          <div class="flex justify-between items-center">
            <div>
              <span class="text-sm font-semibold">Two-factor authentication</span>
              <span class="ml-2 inline-flex items-center text-green-700 bg-green-50 text-xs px-2 py-0.5 rounded-full font-semibold">
                Enabled
              </span>
            </div>
            <button
              phx-click="show_disable"
              class="text-sm text-red-600 bg-red-50 hover:bg-red-100 px-3 py-1.5 rounded-md"
            >
              Disable
            </button>
          </div>

          <%% # Backup code status (D-15) %>
          <div class="mt-3">
            <%%= cond do %>
              <%% @backup_remaining == 0 -> %>
                <div class="text-red-600 bg-red-50 p-2 rounded text-sm">
                  <.icon name="hero-exclamation-triangle" class="h-4 w-4 inline mr-1" />
                  All backup codes used. Generate new ones now.
                </div>
              <%% @backup_remaining <= 2 -> %>
                <div class="text-yellow-700 bg-yellow-50 p-2 rounded text-sm">
                  <.icon name="hero-exclamation-triangle" class="h-4 w-4 inline mr-1" />
                  <%= "{@backup_remaining}" %> of 8 backup codes remaining
                </div>
              <%% true -> %>
                <p class="text-sm text-gray-500">
                  <%= "{@backup_remaining}" %> of 8 backup codes remaining
                </p>
            <%% end %>

            <p class="mt-1">
              <button
                phx-click="show_regenerate"
                class="text-sm text-brand hover:underline"
              >
                Regenerate codes
              </button>
            </p>
          </div>

          <%% # Trust section %>
          <div class="mt-3">
            <button
              phx-click="revoke_trust"
              data-confirm="This will require two-factor authentication on all your browsers. Continue?"
              class="text-sm text-gray-500 hover:underline"
            >
              Revoke all trusted browsers
            </button>
          </div>
        </div>

        <%% # Surface 4: Disable Confirmation %>
        <div :if={@show_disable} class="mt-4 bg-red-50 p-4 rounded-lg border border-red-200">
          <h3 class="text-sm font-semibold text-red-800">Disable two-factor authentication</h3>
          <p class="mt-1 text-sm text-red-700">
            This will remove the extra security on your account.
            You'll need to set it up again to re-enable.
          </p>

          <.form
            for={@disable_form}
            id="mfa_disable_form"
            phx-submit="disable_mfa"
            class="mt-3"
          >
            <div class="space-y-3">
              <div>
                <label for="disable_code" class="block text-sm font-semibold text-red-800">
                  Enter your current 6-digit code or a backup code to confirm:
                </label>
                <input
                  type="text"
                  id="disable_code"
                  name="disable[code]"
                  value={@disable_form[:code].value}
                  inputmode="numeric"
                  class="mt-1 block w-full rounded-lg text-base font-mono text-zinc-900 border-red-300 focus:border-red-400 focus:ring-0"
                  required
                />
              </div>

              <div class="flex items-center gap-3">
                <button
                  type="submit"
                  class="text-sm text-red-600 bg-red-50 border border-red-300 hover:bg-red-100 px-3 py-1.5 rounded-md"
                >
                  Disable two-factor authentication
                </button>
                <button
                  type="button"
                  phx-click="cancel_disable"
                  class="text-sm text-gray-500 hover:underline"
                >
                  Cancel
                </button>
              </div>
            </div>
          </.form>
        </div>

        <%% # Regenerate codes confirmation %>
        <div :if={@show_regenerate} class="mt-4 bg-gray-50 p-4 rounded-lg border border-gray-200">
          <h3 class="text-sm font-semibold">Regenerate backup codes</h3>
          <p class="mt-1 text-sm text-gray-600">
            This will replace all existing backup codes. Enter your current TOTP code to confirm.
          </p>

          <.form
            for={@regenerate_form}
            id="mfa_regenerate_form"
            phx-submit="regenerate_codes"
            class="mt-3"
          >
            <div class="space-y-3">
              <div>
                <label for="regenerate_code" class="block text-sm font-semibold">
                  Current authenticator code:
                </label>
                <input
                  type="text"
                  id="regenerate_code"
                  name="regenerate[code]"
                  value={@regenerate_form[:code].value}
                  inputmode="numeric"
                  pattern="[0-9]*"
                  maxlength="6"
                  autocomplete="one-time-code"
                  class="mt-1 block w-full rounded-lg text-base font-mono text-center tracking-widest text-zinc-900 border-zinc-300 focus:border-zinc-400 focus:ring-0"
                  required
                />
              </div>

              <div class="flex items-center gap-3">
                <.button>Regenerate codes</.button>
                <button
                  type="button"
                  phx-click="cancel_regenerate"
                  class="text-sm text-gray-500 hover:underline"
                >
                  Cancel
                </button>
              </div>
            </div>
          </.form>
        </div>

        <%% # Backup codes display (after regeneration) %>
        <div :if={@enrollment_step == :backup_codes} class="mt-6">
          <%%= render_backup_codes(assigns) %>
        </div>

      <%% else %>
        <%% # Surface 2: TOTP Enrollment %>
        <%%= case @enrollment_step do %>
          <%% nil -> %>
            <%%= render_enrollment_start(assigns) %>

          <%% :qr -> %>
            <%%= render_enrollment_qr(assigns) %>

          <%% :backup_codes -> %>
            <%%= render_enrollment_backup_codes(assigns) %>

          <%% :done -> %>
            <div class="text-center py-8">
              <.icon name="hero-check-circle" class="h-12 w-12 text-green-500 mx-auto" />
              <h3 class="mt-4 text-lg font-semibold">Two-factor authentication enabled</h3>
              <p class="mt-2 text-sm text-gray-500">
                Your account is now protected with an extra layer of security.
              </p>
            </div>
        <%% end %>
      <%% end %>

<%= if passkeys? do %>
      <%%= render_passkeys_section(assigns) %>
<% end %>
    </div>
    """
  end

<%= if passkeys? do %>
  defp render_passkeys_section(assigns) do
    ~H"""
    <section id="passkeys" class="mt-8 bg-gray-50 p-4 rounded-lg border border-gray-200">
      <div class="flex items-start justify-between gap-4">
        <div>
          <h2 class="text-xl font-semibold">Passkeys</h2>
          <p class="mt-1 text-sm text-gray-600">
            Use Face ID, Touch ID, Windows Hello, or your password manager to sign in without typing a code.
          </p>
        </div>

        <button
          type="button"
          id="add-passkey-button"
          phx-click="begin_passkey_enrollment"
          disabled={@passkey_status == :enrolling}
          class="text-sm text-white bg-brand hover:bg-brand/90 px-3 py-1.5 rounded-md disabled:opacity-50"
        >
          Add passkey
        </button>
      </div>

      <div
        id="passkey-registration-hook"
        phx-hook="PasskeyRegister"
        class="hidden"
      />

      <form id="passkey-registration-form" action={~p"/users/settings/mfa/passkeys"} method="post" class="hidden">
        <input type="hidden" name="_csrf_token" value={Phoenix.Controller.get_csrf_token()} />
        <input type="hidden" name="passkey[response]" id="passkey-registration-response" />
      </form>

      <div :if={@passkey_notice} class="mt-4 rounded-lg border border-gray-200 bg-white p-3">
        <p class="text-sm font-semibold text-gray-900">{@passkey_notice.title}</p>
        <p class="mt-1 text-sm text-gray-600">{@passkey_notice.body}</p>
      </div>

      <div class="mt-4">
        <%%= if @passkeys == [] do %>
          <div class="text-center py-8">
            <p class="text-sm font-semibold text-gray-900">No passkeys added yet</p>
            <p class="mt-1 text-sm text-gray-500">
              Add a passkey to sign in faster on this device and keep a backup sign-in method available.
            </p>
          </div>
        <%% else %>
          <div class="space-y-3">
            <div
              :for={passkey <- @passkeys}
              class="flex items-start justify-between p-4 bg-white rounded-lg border border-gray-200"
            >
              <div class="min-w-0 flex-1">
                <div class="flex items-center gap-2">
                  <.icon name="hero-key" class="h-4 w-4 text-gray-400" />
                  <p class="text-sm font-semibold text-gray-900">{Auth.passkey_label(passkey)}</p>
                </div>

                <p class="mt-1 text-sm text-gray-500">
                  Added {relative_time(passkey.inserted_at)}
                  &middot;
                  <%%= if passkey.last_used_at do %>
                    Last used {relative_time(passkey.last_used_at)}
                  <%% else %>
                    Never used
                  <%% end %>
                </p>

                <div :if={@renaming_passkey_id == passkey.credential_id} class="mt-3">
                  <.form
                    for={@rename_form}
                    phx-submit="save_passkey_name"
                    class="flex flex-col gap-2 sm:flex-row sm:items-end"
                  >
                    <input type="hidden" name="passkey[id]" value={passkey.credential_id} />
                    <div class="flex-1">
                      <label for={"passkey-name-#{passkey.credential_id}"} class="block text-sm font-semibold">
                        Passkey name
                      </label>
                      <input
                        id={"passkey-name-#{passkey.credential_id}"}
                        type="text"
                        name="passkey[nickname]"
                        value={@rename_form[:nickname].value}
                        class="mt-1 block w-full rounded-lg text-base text-zinc-900 border-zinc-300 focus:border-zinc-400 focus:ring-0"
                      />
                    </div>
                    <div class="flex gap-2">
                      <button type="submit" class="text-sm text-white bg-brand hover:bg-brand/90 px-3 py-1.5 rounded-md">
                        Save name
                      </button>
                      <button
                        type="button"
                        phx-click="cancel_passkey_rename"
                        class="text-sm text-gray-500 hover:underline"
                      >
                        Cancel
                      </button>
                    </div>
                  </.form>
                </div>

                <div :if={@deleting_passkey_id == passkey.credential_id} class="mt-3 rounded-lg border border-red-200 bg-red-50 p-3">
                  <p class="text-sm font-semibold text-red-800">Delete this passkey?</p>
                  <p class="mt-1 text-sm text-red-700">
                    Delete this passkey? You'll still need another sign-in method before removing your last recovery option.
                  </p>
                  <p :if={@passkey_count == 1} class="mt-2 text-sm text-red-700">
                    You're removing your last passkey. Make sure you can still sign in with your password, authenticator code, backup code, or magic link.
                  </p>

                  <div class="mt-3 flex items-center gap-2">
                    <form action={~p"/users/settings/mfa/passkeys/#{passkey.credential_id}/delete"} method="post">
                      <input type="hidden" name="_csrf_token" value={Phoenix.Controller.get_csrf_token()} />
                      <button type="submit" class="text-sm text-red-600 bg-white border border-red-300 hover:bg-red-100 px-3 py-1.5 rounded-md">
                        Delete
                      </button>
                    </form>
                    <button
                      type="button"
                      phx-click="cancel_passkey_delete"
                      class="text-sm text-gray-500 hover:underline"
                    >
                      Cancel
                    </button>
                  </div>
                </div>
              </div>

              <div class="ml-4 flex shrink-0 items-center gap-2">
                <button
                  type="button"
                  phx-click="open_passkey_rename"
                  phx-value-id={passkey.credential_id}
                  class="text-sm text-brand hover:underline"
                >
                  Rename
                </button>
                <button
                  type="button"
                  phx-click="confirm_passkey_delete"
                  phx-value-id={passkey.credential_id}
                  class="text-sm text-red-600 hover:underline"
                >
                  Delete
                </button>
              </div>
            </div>
          </div>
        <%% end %>
      </div>
    </section>
    """
  end
<% end %>

  defp render_enrollment_start(assigns) do
    ~H"""
    <div>
      <.header>
        Two-Factor Authentication
        <:subtitle>Add an extra layer of security to your account.</:subtitle>
      </.header>

      <div class="mt-6">
        <.button phx-click="begin_enrollment">
          Set up two-factor authentication
        </.button>
      </div>
    </div>
    """
  end

  defp render_enrollment_qr(assigns) do
    ~H"""
    <div>
      <.header>
        Two-Factor Authentication
        <:subtitle>Add an extra layer of security to your account.</:subtitle>
      </.header>

      <div class="mt-6 space-y-6">
        <%% # QR Code %>
        <div class="text-center">
          <p class="text-sm text-gray-600 mb-4">
            Scan this QR code with your authenticator app
          </p>
          <div
            class="inline-block"
            role="img"
            aria-label="QR code for TOTP setup"
          >
            <%= "{raw(@svg)}" %>
          </div>
        </div>

        <%% # Manual key %>
        <div>
          <p class="text-sm text-gray-600">
            Can't scan? Enter this key manually:
          </p>
          <div
            class="mt-2 bg-gray-50 p-3 rounded-lg border border-gray-200 text-center"
            style="user-select: all"
          >
            <code data-testid="mfa-totp-secret" class="text-sm font-mono break-all select-all">
              <%= "{@base32_secret}" %>
            </code>
          </div>
        </div>

        <%% # Confirmation form %>
        <div>
          <p class="text-sm font-semibold">
            Enter the 6-digit code from your app to verify setup:
          </p>

          <.form
            for={@enroll_form}
            id="mfa_enroll_form"
            phx-change="validate_enroll"
            phx-submit="confirm_enrollment"
            class="mt-3"
          >
            <div class="space-y-4">
              <input
                type="text"
                name="enroll[code]"
                value={@enroll_form[:code].value}
                inputmode="numeric"
                pattern="[0-9]*"
                maxlength="6"
                autocomplete="one-time-code"
                autofocus
                required
                class="block w-full rounded-lg text-base font-mono text-center tracking-widest text-zinc-900 focus:ring-0 border-zinc-300 focus:border-zinc-400"
                aria-label="6-digit verification code"
              />

              <.button class="w-full">
                Enable two-factor authentication
              </.button>
            </div>
          </.form>
        </div>
      </div>
    </div>
    """
  end

  defp render_enrollment_backup_codes(assigns) do
    ~H"""
    <div>
      <%%= render_backup_codes(assigns) %>
    </div>
    """
  end

  defp render_backup_codes(assigns) do
    ~H"""
    <div>
      <.header>
        Save your backup codes
        <:subtitle>
          Store these codes in a safe place. Each code can only be used once.
        </:subtitle>
      </.header>

      <%% # Backup code grid (D-08) %>
      <div class="mt-4 bg-gray-50 p-4 rounded-lg">
        <ol class="grid grid-cols-2 gap-3">
          <li :for={code <- @backup_codes} class="text-center">
            <code class="text-base font-mono"><%= "{code}" %></code>
          </li>
        </ol>
      </div>

      <%% # Action buttons %>
      <div class="mt-4 flex gap-2">
        <button
          type="button"
          phx-hook="CopyBackupCodes"
          id="copy-backup-codes"
          data-codes={Enum.join(@backup_codes, "\n")}
          class="inline-flex items-center gap-1 text-sm text-gray-600 bg-white border border-gray-300 hover:bg-gray-50 px-3 py-1.5 rounded-md"
        >
          <.icon name="hero-clipboard-document" class="h-4 w-4" />
          <span id="copy-btn-text">Copy all</span>
        </button>
        <button
          type="button"
          phx-hook="DownloadBackupCodes"
          id="download-backup-codes"
          data-codes={Enum.join(@backup_codes, "\n")}
          class="inline-flex items-center gap-1 text-sm text-gray-600 bg-white border border-gray-300 hover:bg-gray-50 px-3 py-1.5 rounded-md"
        >
          <.icon name="hero-arrow-down-tray" class="h-4 w-4" />
          Download .txt
        </button>
      </div>

      <%% # Acknowledgment checkbox (D-11) %>
      <div class="mt-4">
        <label class="flex items-center gap-2 text-sm">
          <input
            type="checkbox"
            phx-click="toggle_acknowledge"
            checked={@codes_acknowledged}
            class="rounded border-gray-300"
          />
          I have saved these backup codes in a safe place
        </label>
      </div>

      <%% # Done button %>
      <div class="mt-4">
        <.button
          phx-click="complete_enrollment"
          disabled={!@codes_acknowledged}
          class={"w-full #{unless @codes_acknowledged, do: "opacity-50 cursor-not-allowed"}"}
        >
          Done
        </.button>
      </div>
    </div>
    """
  end

  # -- Event Handlers --

  def handle_event("begin_enrollment", _params, socket) do
    user = socket.assigns.current_scope.user

    case Auth.mfa_enroll(account: user.email) do
      {:ok, enrollment} ->
        {:noreply,
         assign(socket,
           enrollment_step: :qr,
           svg: enrollment.svg,
           base32_secret: enrollment.secret,
           raw_secret: enrollment.raw_secret
         )}
    end
  end

  def handle_event("validate_enroll", %{"enroll" => %{"code" => code}}, socket) do
    form = to_form(%{"code" => code}, as: "enroll")
    socket = assign(socket, enroll_form: form)

    # Auto-submit when 6 digits entered (D-36). 10.1 IN-06 follow-up:
    # call the confirm path directly instead of dispatching via
    # `send(self(), …)`. The mailbox round-trip allowed a stale 6-digit
    # prefix to fire after the user typed a 7th character, wasting an
    # attempt against the MFA lockout counter.
    if String.length(code) == 6 and Regex.match?(~r/^\d{6}$/, code) do
      do_confirm_enrollment(socket, code)
    else
      {:noreply, socket}
    end
  end

  def handle_event("confirm_enrollment", %{"enroll" => %{"code" => code}}, socket) do
    do_confirm_enrollment(socket, code)
  end

  def handle_event("toggle_acknowledge", _params, socket) do
    {:noreply, assign(socket, codes_acknowledged: !socket.assigns.codes_acknowledged)}
  end

  def handle_event("complete_enrollment", _params, socket) do
    if socket.assigns.codes_acknowledged do
      user = socket.assigns.current_scope.user
      mfa_status = Auth.mfa_status(user)

      {:noreply,
       assign(socket,
         mfa_enabled: true,
         enrollment_step: nil,
         backup_codes: [],
         backup_remaining: mfa_status.backup_codes_remaining,
         codes_acknowledged: false
       )}
    else
      {:noreply, socket}
    end
  end

  defp do_confirm_enrollment(socket, code) do
    user = socket.assigns.current_scope.user
    raw_secret = socket.assigns.raw_secret

    case Auth.mfa_confirm_enrollment(user, raw_secret, code) do
      {:ok, %{backup_codes: codes}} ->
        {:noreply,
         socket
         |> put_flash(:info, "Two-factor authentication has been enabled.")
         |> assign(
           enrollment_step: :backup_codes,
           backup_codes: codes,
           codes_acknowledged: false,
           raw_secret: nil
         )}

      {:error, :invalid_code} ->
        form = to_form(%{"code" => ""}, as: "enroll")

        {:noreply,
         socket
         |> put_flash(:error, "Invalid verification code. Please try again.")
         |> assign(enroll_form: form)}
    end
  end

<%= if passkeys? do %>
  def handle_event("begin_passkey_enrollment", _params, socket) do
    {:noreply,
     socket
     |> assign(passkey_status: :enrolling, passkey_notice: nil)
     |> push_event("sigra:passkey-register:start", %{
       optionsUrl: ~p"/users/settings/mfa/passkeys/options",
       completeUrl: ~p"/users/settings/mfa/passkeys"
     })}
  end

  def handle_event("sigra:passkey-register:success", _params, socket) do
    {:noreply,
     assign(socket,
       passkey_status: :idle,
       passkey_notice: %{
         title: "Finishing passkey setup...",
         body: "Keep this page open while we finish saving your passkey."
       }
     )}
  end

  def handle_event("sigra:passkey-register:aborted", _params, socket) do
    {:noreply,
     assign(socket,
       passkey_status: :idle,
       passkey_notice: %{
         title: "Passkey sign-in was canceled.",
         body: "Nothing changed. Try again or choose another way to continue."
       }
     )}
  end

  def handle_event("sigra:passkey-register:error", payload, socket) do
    notice =
      case passkey_error_bucket(payload) do
        :timeout ->
          %{
            title: "That passkey request timed out.",
            body: "Try again when you're ready, or use another sign-in method."
          }

        :unsupported ->
          %{
            title: "Passkeys aren't available in this browser.",
            body: "Use your password or a magic link here, or switch to a device that supports passkeys."
          }

        :generic ->
          %{
            title: "We couldn't finish passkey sign-in.",
            body: "Try again or use another way to continue."
          }
      end

    {:noreply, assign(socket, passkey_status: :idle, passkey_notice: notice)}
  end

  def handle_event("open_passkey_rename", %{"id" => credential_id}, socket) do
    nickname =
      socket
      |> find_passkey(credential_id)
      |> case do
        nil -> ""
        passkey -> passkey.nickname || ""
      end

    {:noreply,
     assign(socket,
       renaming_passkey_id: credential_id,
       rename_form: to_form(%{"nickname" => nickname}, as: "passkey"),
       deleting_passkey_id: nil
     )}
  end

  def handle_event("cancel_passkey_rename", _params, socket) do
    {:noreply,
     assign(socket,
       renaming_passkey_id: nil,
       rename_form: to_form(%{"nickname" => ""}, as: "passkey")
     )}
  end

  def handle_event("save_passkey_name", %{"passkey" => params}, socket) do
    user = socket.assigns.current_scope.user
    credential_id = Map.get(params, "id")
    nickname = Map.get(params, "nickname", "")

    if impersonating?(socket) do
      {:noreply, put_flash(socket, :error, "You can't change account security settings while impersonating.")}
    else
      case Auth.rename_passkey(user, credential_id, nickname || "", scope: socket.assigns.current_scope) do
      {:ok, _passkey} ->
        {:noreply,
         socket
         |> put_flash(:info, "Passkey name saved.")
         |> refresh_passkey_assigns()
         |> assign(
           renaming_passkey_id: nil,
           rename_form: to_form(%{"nickname" => ""}, as: "passkey")
         )}

        {:error, :impersonation_forbidden} ->
          {:noreply, put_flash(socket, :error, "You can't change account security settings while impersonating.")}

        {:error, _reason} ->
          {:noreply, put_flash(socket, :error, "Could not save passkey name. Please try again.")}
      end
    end
  end

  def handle_event("confirm_passkey_delete", %{"id" => credential_id}, socket) do
    {:noreply,
     assign(socket,
       deleting_passkey_id: credential_id,
       renaming_passkey_id: nil,
       rename_form: to_form(%{"nickname" => ""}, as: "passkey")
     )}
  end

  def handle_event("cancel_passkey_delete", _params, socket) do
    {:noreply, assign(socket, deleting_passkey_id: nil)}
  end

  def handle_event("show_disable", _params, socket) do
    {:noreply, assign(socket, show_disable: true)}
  end

  def handle_event("cancel_disable", _params, socket) do
    {:noreply, assign(socket, show_disable: false, disable_form: to_form(%{"code" => ""}, as: "disable"))}
  end

  def handle_event("disable_mfa", %{"disable" => %{"code" => code}}, socket) do
    user = socket.assigns.current_scope.user

    if impersonating?(socket) do
      {:noreply, put_flash(socket, :error, "You can't change account security settings while impersonating.")}
    else
      case Auth.mfa_disable(user, code, scope: socket.assigns.current_scope) do
      {:ok, :disabled} ->
        {:noreply,
         socket
         |> put_flash(:info, "Two-factor authentication has been disabled.")
         |> put_flash(:warning, "Consider changing your password for additional security.")
         |> assign(
           mfa_enabled: false,
           show_disable: false,
           enrollment_step: nil,
           backup_remaining: 0,
           disable_form: to_form(%{"code" => ""}, as: "disable")
         )}

      {:error, :invalid_code, _remaining} ->
        {:noreply,
         socket
         |> put_flash(:error, "Invalid verification code. Please try again.")
         |> assign(disable_form: to_form(%{"code" => ""}, as: "disable"))}

      {:error, :invalid_backup_code, _remaining} ->
        {:noreply,
         socket
         |> put_flash(:error, "Invalid verification code. Please try again.")
         |> assign(disable_form: to_form(%{"code" => ""}, as: "disable"))}

      {:error, :lockout, seconds} ->
        minutes = div(seconds + 59, 60)

        {:noreply,
         socket
         |> put_flash(:error, "Too many failed attempts. Try again in #{minutes} minutes.")}

        {:error, :impersonation_forbidden} ->
          {:noreply, put_flash(socket, :error, "You can't change account security settings while impersonating.")}

        {:error, _reason} ->
          {:noreply,
           socket
           |> put_flash(:error, "Could not disable two-factor authentication. Please try again.")}
      end
    end
  end

  def handle_event("show_regenerate", _params, socket) do
    {:noreply, assign(socket, show_regenerate: true)}
  end

  def handle_event("cancel_regenerate", _params, socket) do
    {:noreply, assign(socket, show_regenerate: false, regenerate_form: to_form(%{"code" => ""}, as: "regenerate"))}
  end

  def handle_event("regenerate_codes", %{"regenerate" => %{"code" => code}}, socket) do
    user = socket.assigns.current_scope.user

    # First verify TOTP code, then regenerate
    case Auth.mfa_verify(user, code) do
      {:ok, _} ->
        # TODO: Wire to Auth.mfa_regenerate_backup_codes/2 when available
        # For now, show success and refresh status
        mfa_status = Auth.mfa_status(user)

        {:noreply,
         socket
         |> put_flash(:info, "Backup codes have been regenerated.")
         |> assign(
           show_regenerate: false,
           backup_remaining: mfa_status.backup_codes_remaining,
           regenerate_form: to_form(%{"code" => ""}, as: "regenerate")
         )}

      {:error, :invalid_code, _remaining} ->
        {:noreply,
         socket
         |> put_flash(:error, "Invalid verification code. Please try again.")
         |> assign(regenerate_form: to_form(%{"code" => ""}, as: "regenerate"))}

      {:error, :lockout, seconds} ->
        minutes = div(seconds + 59, 60)

        {:noreply,
         socket
         |> put_flash(:error, "Too many failed attempts. Try again in #{minutes} minutes.")}
    end
  end

  def handle_event("revoke_trust", _params, socket) do
    user = socket.assigns.current_scope.user
    config = Auth.sigra_config()
    Sigra.MFA.Trust.revoke_all(config.repo, config.user_schema, user.id)

    {:noreply,
     socket
     |> put_flash(:info, "All trusted browsers have been revoked.")}
  end

  defp passkey_error_bucket(payload) when is_map(payload) do
    payload
    |> Map.take(["code", "name", "message"])
    |> Map.values()
    |> Enum.map(&to_string/1)
    |> Enum.join(" ")
    |> String.downcase()
    |> classify_passkey_error()
  end

  defp passkey_error_bucket(_payload), do: :generic

  defp classify_passkey_error(text) do
    cond do
      String.contains?(text, "timeout") ->
        :timeout

      String.contains?(text, "unsupported") or String.contains?(text, "not_supported") or
          String.contains?(text, "notallowed") ->
        :unsupported

      true ->
        :generic
    end
  end

  defp refresh_passkey_assigns(socket) do
    user = socket.assigns.current_scope.user

    assign(socket,
      passkeys: Auth.passkeys_for_user(user),
      passkey_count: Auth.passkey_count_for_user(user)
    )
  end

  defp impersonating?(socket) do
    match?(%{impersonating_from: impersonator} when not is_nil(impersonator), socket.assigns.current_scope)
  end

  defp find_passkey(socket, credential_id) do
    Enum.find(socket.assigns.passkeys, &(to_string(&1.credential_id) == to_string(credential_id)))
  end
<% end %>

<%= if passkeys? do %>
  defp relative_time(nil), do: "Never"

  defp relative_time(%DateTime{} = dt) do
    diff = DateTime.diff(DateTime.utc_now(), dt, :second)
    format_relative_seconds(diff)
  end

  defp relative_time(%NaiveDateTime{} = ndt) do
    ndt
    |> DateTime.from_naive!("Etc/UTC")
    |> relative_time()
  end

  defp format_relative_seconds(seconds) when seconds < 60, do: "just now"
  defp format_relative_seconds(seconds) when seconds < 3600, do: "#{div(seconds, 60)}m ago"
  defp format_relative_seconds(seconds) when seconds < 86_400, do: "#{div(seconds, 3600)}h ago"
  defp format_relative_seconds(seconds), do: "#{div(seconds, 86_400)}d ago"
<% end %>
end
