defmodule <%= web_module %>.MFASettingsHTML do
  @moduledoc """
  Controller-mode MFA settings and enrollment templates.

  Provides the MFA enrollment, backup code display, settings card,
  and disable confirmation for non-LiveView installs.

  Generated by `mix sigra.install --no-live`. Customize freely -- this module
  is owned by your application.
  """
  use <%= web_module %>, :html
  import <%= web_module %>.SigraAuthComponents

  @doc """
  Renders the MFA settings section.

  Assigns expected:
  - `@mfa_enabled` - boolean
  - `@backup_remaining` - integer
  - `@enrollment_step` - nil | :qr | :backup_codes
  - `@svg` - QR code SVG string (when enrolling)
  - `@base32_secret` - base32 TOTP secret (when enrolling)
  - `@backup_codes` - list of backup code strings
  - `@show_disable` - boolean
  """
  def mfa_settings(assigns) do
    ~H"""
    <.sigra_auth_page>
      <div class="sigra-auth-flow sigra-auth-flow--wide sigra-auth-stack sigra-auth-stack--6">
      <%%= if @mfa_enabled do %>
        <%% # Surface 3: MFA Settings Card %>
        <section class="sigra-auth-section">
          <div class="sigra-auth-split">
            <div>
              <h2>Two-factor authentication</h2>
              <span class="sigra-auth-status sigra-auth-status--success">
                Enabled
              </span>
            </div>
            <.link
              href={~p"/users/settings/mfa/disable"}
              class="sigra-auth-action sigra-auth-action--danger sigra-auth-action--small"
            >
              Disable
            </.link>
          </div>

          <%% # Backup code status (D-15) %>
          <div class="sigra-auth-stack sigra-auth-stack--2">
            <%%= cond do %>
              <%% @backup_remaining == 0 -> %>
                <div class="sigra-auth-notice sigra-auth-notice--danger">
                  All backup codes used. Generate new ones now.
                </div>
              <%% @backup_remaining <= 2 -> %>
                <div class="sigra-auth-notice sigra-auth-notice--warning">
                  <%= "{@backup_remaining}" %> of 8 backup codes remaining
                </div>
              <%% true -> %>
                <p class="sigra-auth-copy sigra-auth-copy--muted">
                  <%= "{@backup_remaining}" %> of 8 backup codes remaining
                </p>
            <%% end %>

            <p>
              <.link
                href={~p"/users/settings/mfa/regenerate"}
              >
                Regenerate codes
              </.link>
            </p>
          </div>

          <%% # Trust section %>
          <div>
            <.link
              href={~p"/users/settings/mfa/revoke-trust"}
              method="post"
              data-confirm="This will require two-factor authentication on all your browsers. Continue?"
              class="sigra-auth-action sigra-auth-action--ghost sigra-auth-action--small"
            >
              Revoke all trusted browsers
            </.link>
          </div>
        </section>

        <%% # Surface 4: Disable Confirmation %>
        <%%= if @show_disable do %>
          <section class="sigra-auth-notice sigra-auth-notice--danger sigra-auth-stack sigra-auth-stack--4">
            <h2>Disable two-factor authentication</h2>
            <p>
              This will remove the extra security on your account.
              You'll need to set it up again to re-enable.
            </p>

            <.form for={%{}} action={~p"/users/settings/mfa/disable"} method="post" class="sigra-auth-stack sigra-auth-stack--3">
              <div class="sigra-auth-stack sigra-auth-stack--3">
                <div>
                  <label for="disable_code">
                    Enter your current 6-digit code or a backup code to confirm:
                  </label>
                  <input
                    type="text"
                    id="disable_code"
                    name="code"
                    inputmode="numeric"
                    class="sigra-auth-code-input"
                    required
                  />
                </div>

                <div class="sigra-auth-cluster">
                  <button
                    type="submit"
                    class="sigra-auth-action sigra-auth-action--danger"
                  >
                    Disable two-factor authentication
                  </button>
                  <.link href={~p"/users/settings"} class="sigra-auth-action sigra-auth-action--ghost">
                    Cancel
                  </.link>
                </div>
              </div>
            </.form>
          </section>
        <%% end %>

      <%% else %>
        <%% # Enrollment UI %>
        <%%= case @enrollment_step do %>
          <%% nil -> %>
            <.header>
              Two-Factor Authentication
              <:subtitle>Add an extra layer of security to your account.</:subtitle>
            </.header>

            <div>
              <.link href={~p"/users/settings/mfa/enroll"} class="sigra-auth-action sigra-auth-action--primary">
                Set up two-factor authentication
              </.link>
            </div>

          <%% :qr -> %>
            <.header>
              Two-Factor Authentication
              <:subtitle>Add an extra layer of security to your account.</:subtitle>
            </.header>

            <div class="sigra-auth-stack sigra-auth-stack--6">
              <div class="sigra-auth-stack sigra-auth-stack--4 sigra-auth-copy--center">
                <p class="sigra-auth-copy sigra-auth-copy--muted">
                  Scan this QR code with your authenticator app
                </p>
                <div
                  role="img"
                  aria-label="QR code for TOTP setup"
                >
                  <%= "{raw(@svg)}" %>
                </div>
              </div>

              <div>
                <p class="sigra-auth-copy sigra-auth-copy--muted">
                  Can't scan? Enter this key manually:
                </p>
                <div
                  class="sigra-auth-section sigra-auth-copy--center"
                  style="user-select: all"
                >
                  <code class="sigra-auth-code">
                    <%= "{@base32_secret}" %>
                  </code>
                </div>
              </div>

              <div>
                <p>
                  Enter the 6-digit code from your app to verify setup:
                </p>

                <.form for={%{}} action={~p"/users/settings/mfa/confirm"} method="post" class="sigra-auth-stack sigra-auth-stack--4">
                  <div class="sigra-auth-stack sigra-auth-stack--4">
                    <input
                      type="text"
                      name="code"
                      inputmode="numeric"
                      pattern="[0-9]*"
                      maxlength="6"
                      autocomplete="one-time-code"
                      autofocus
                      required
                      class="sigra-auth-code-input"
                      aria-label="6-digit verification code"
                    />

                    <.sigra_auth_button class="sigra-auth-action sigra-auth-action--primary sigra-auth-action--block">
                      Enable two-factor authentication
                    </.sigra_auth_button>
                  </div>
                </.form>
              </div>
            </div>

          <%% :backup_codes -> %>
            <.header>
              Save your backup codes
              <:subtitle>
                Store these one-time codes somewhere safe. You will not be able to see them again after leaving this step.
              </:subtitle>
            </.header>

            <div id="panel-backup-codes" class="sigra-auth-section">
              <ol class="sigra-auth-code-list" aria-label="One-time backup codes">
                <%%= for code <- @backup_codes do %>
                  <li>
                    <code><%= "{code}" %></code>
                  </li>
                <%% end %>
              </ol>
            </div>

            <div class="sigra-auth-cluster">
              <button
                type="button"
                id="copy-backup-codes"
                onclick="copyBackupCodes()"
                class="sigra-auth-action sigra-auth-action--secondary"
              >
                <span id="copy-btn-text">Copy all</span>
              </button>
              <button
                type="button"
                id="download-backup-codes"
                onclick="downloadBackupCodes()"
                class="sigra-auth-action sigra-auth-action--secondary"
              >
                Download .txt
              </button>
            </div>
            <p id="backup-code-copy-status" class="sigra-auth-copy sigra-auth-copy--muted" aria-live="polite"></p>

            <.form for={%{}} action={~p"/users/settings/mfa/complete"} method="post" class="sigra-auth-stack sigra-auth-stack--4">
              <label class="sigra-auth-check-row">
                <input
                  type="checkbox"
                  name="acknowledged"
                  value="true"
                  required
                  class="sigra-auth-check"
                />
                I have saved these backup codes in a safe place
              </label>

              <.sigra_auth_button class="sigra-auth-action sigra-auth-action--primary sigra-auth-action--block">
                I saved these codes
              </.sigra_auth_button>
            </.form>

            <script>
              function copyBackupCodes() {
                var codes = document.querySelectorAll('#panel-backup-codes code');
                var text = Array.from(codes).map(function(el) { return el.textContent.trim(); }).join('\n');
                var status = document.getElementById('backup-code-copy-status');
                navigator.clipboard.writeText(text).then(function() {
                  var btn = document.getElementById('copy-btn-text');
                  btn.textContent = 'Copied!';
                  status.textContent = 'Backup codes copied.';
                  setTimeout(function() { btn.textContent = 'Copy all'; }, 2000);
                }).catch(function() {
                  status.textContent = 'Copy is unavailable. Select and copy the codes above.';
                });
              }

              function downloadBackupCodes() {
                var codes = document.querySelectorAll('#panel-backup-codes code');
                var text = Array.from(codes).map(function(el) { return el.textContent.trim(); }).join('\n');
                var blob = new Blob([text], { type: 'text/plain' });
                var url = URL.createObjectURL(blob);
                var a = document.createElement('a');
                a.href = url;
                a.download = 'backup-codes.txt';
                a.click();
                URL.revokeObjectURL(url);
              }
            </script>
        <%% end %>
      <%% end %>
      </div>
    </.sigra_auth_page>
    """
  end
end
