defmodule <%= web_module %>.OAuthTokenController do
  @moduledoc """
  RFC 6749 token endpoint for service-account `client_credentials` exchange.

  Generated by Sigra when both `--jwt` and `--organizations` are enabled.
  """

  use <%= web_module %>, :controller

  alias <%= context_module %>, as: Auth

  def create(conn, params) do
    config = Auth.sigra_config()

    with {:ok, client_id, client_secret} <- extract_client_credentials(conn, params),
         "client_credentials" <- params["grant_type"] do
      case Sigra.OAuth.Token.client_credentials(
             config,
             client_id: client_id,
             client_secret: client_secret,
             scope: params["scope"],
             ip_address: format_ip(conn.remote_ip)
           ) do
        {:ok, %{access_token: jwt, expires_in: ttl, scope: scope}} ->
          conn
          |> put_resp_header("cache-control", "no-store")
          |> put_resp_header("pragma", "no-cache")
          |> json(%{
            access_token: jwt,
            token_type: "Bearer",
            expires_in: ttl,
            scope: scope
          })

        {:error, :invalid_client} ->
          send_error(conn, 401, "invalid_client", "Client authentication failed.")

        {:error, :invalid_scope} ->
          send_error(conn, 400, "invalid_scope", "Requested scope is not granted to this client.")

        {:error, :service_account_token_issuance_aborted} ->
          send_error(conn, 500, "server_error", "Token issuance could not complete atomically.")
      end
    else
      {:error, :missing_credentials} ->
        send_error(conn, 401, "invalid_client", "Client credentials required.")

      grant when is_binary(grant) ->
        send_error(
          conn,
          400,
          "unsupported_grant_type",
          "Grant type \"#{grant}\" is not supported. Use \"client_credentials\"."
        )

      _ ->
        send_error(conn, 400, "invalid_request", "Missing or invalid request parameters.")
    end
  end

  defp extract_client_credentials(conn, params) do
    case Plug.Conn.get_req_header(conn, "authorization") do
      ["Basic " <> encoded] ->
        with {:ok, decoded} <- Base.decode64(encoded),
             [client_id, client_secret] <- String.split(decoded, ":", parts: 2),
             true <- client_id != "" and client_secret != "" do
          {:ok, client_id, client_secret}
        else
          _ -> {:error, :missing_credentials}
        end

      _ ->
        case {params["client_id"], params["client_secret"]} do
          {client_id, client_secret} when is_binary(client_id) and is_binary(client_secret) ->
            {:ok, client_id, client_secret}

          _ ->
            {:error, :missing_credentials}
        end
    end
  end

  defp send_error(conn, status, error, description) do
    conn
    |> put_status(status)
    |> json(%{error: error, error_description: description})
  end

  defp format_ip(nil), do: nil
  defp format_ip(ip), do: ip |> :inet.ntoa() |> to_string()
end
