defmodule <%= web_module %>.Auth.SessionLive do
  @moduledoc """
  LiveView for session listing and management.

  Displays all active sessions for the current user with device info,
  IP address, location, and last active time. Supports revoking individual
  sessions and logging out of all devices.

  Current session is identified from the server-side Plug session token
  (hashed for comparison) and tagged with a "This device" badge.

  Generated by `mix sigra.install --live`. Customize freely -- this module
  is owned by your application.
  """
  use <%= web_module %>, :live_view
  import <%= web_module %>.SigraAuthComponents

  alias <%= context_module %>, as: Auth

  def mount(_params, session, socket) do
    user = socket.assigns.current_scope.user
    sessions = Auth.list_sessions(user)

    {:ok, assign(socket,
      sessions: sessions,
      current_hashed_token: current_hashed_token(session),
      page_title: "Active Sessions"
    )}
  end

  def render(assigns) do
    ~H"""
    <.sigra_auth_page>
      <div class="mx-auto max-w-2xl">
      <.header>
        Active Sessions
        <:subtitle>These devices are currently signed in to your account.</:subtitle>
      </.header>

      <div class="mt-8 space-y-4">
        <div
          :for={session <- @sessions}
          class="flex items-start justify-between p-4 bg-gray-50 rounded-lg border border-gray-200"
        >
          <div class="flex-1">
            <div class="flex items-center gap-2">
              <span class="text-sm font-semibold">
                <%%= device_name(session) %>
              </span>
              <span
                :if={current_session?(session, @current_hashed_token)}
                class="inline-flex items-center rounded-md bg-brand/10 px-2 py-1 text-xs font-semibold text-brand"
              >
                This device
              </span>
            </div>
            <div class="mt-1 text-sm text-gray-500">
              <span><%%= session.ip || "Unknown IP" %></span>
              <span class="mx-1">&middot;</span>
              <span><%%= location(session) %></span>
            </div>
            <div class="mt-1 text-sm text-gray-500">
              <%%= relative_time(session.last_active_at) %>
            </div>
          </div>
          <div>
            <%%= if current_session?(session, @current_hashed_token) do %>
              <.button
                phx-click="revoke_current"
                phx-value-token={Base.url_encode64(session.hashed_token)}
                data-confirm="This is your current session. Revoking it will log you out. Continue?"
                class="text-sm text-red-600 bg-red-50 hover:bg-red-100"
              >
                Revoke session
              </.button>
            <%% else %>
              <.button
                phx-click="revoke"
                phx-value-token={Base.url_encode64(session.hashed_token)}
                class="text-sm text-red-600 bg-red-50 hover:bg-red-100"
              >
                Revoke session
              </.button>
            <%% end %>
          </div>
        </div>
      </div>

      <div :if={length(@sessions) > 1} class="mt-8 border-t border-gray-200 pt-6">
        <.button
          phx-click="revoke_all"
          data-confirm="This will end all sessions including your current one. You will be logged out."
          class="text-red-600 bg-red-50 hover:bg-red-100"
        >
          Log out of all devices
        </.button>
      </div>
      </div>
    </.sigra_auth_page>
    """
  end

  def handle_event("revoke", %{"token" => encoded_token}, socket) do
    hashed_token = Base.url_decode64!(encoded_token)
    Auth.revoke_session(hashed_token)

    sessions = Auth.list_sessions(socket.assigns.current_scope.user)
    {:noreply, socket |> put_flash(:info, "Session revoked.") |> assign(sessions: sessions)}
  end

  def handle_event("revoke_current", %{"token" => encoded_token}, socket) do
    hashed_token = Base.url_decode64!(encoded_token)
    Auth.revoke_session(hashed_token)

    {:noreply, redirect(socket, to: ~p"/users/log_in")}
  end

  def handle_event("revoke_all", _params, socket) do
    user = socket.assigns.current_scope.user
    Auth.revoke_all_sessions(user)

    {:noreply, redirect(socket, to: ~p"/users/log_in")}
  end

  defp device_name(%{parsed_ua: %{browser: browser, browser_version: version, os: os}})
       when browser != "Unknown" do
    if version, do: "#{browser} #{version} on #{os}", else: "#{browser} on #{os}"
  end

  defp device_name(_), do: "Unknown device"

  defp location(%{geo_city: city, geo_country_code: country}) when is_binary(city),
    do: "#{city}, #{country}"

  defp location(_), do: "Unknown location"

  defp relative_time(nil), do: "Never"

  defp relative_time(datetime) do
    seconds = DateTime.diff(DateTime.utc_now(), datetime, :second)

    cond do
      seconds < 60 -> "Active just now"
      seconds < 3600 -> "Active #{div(seconds, 60)} minutes ago"
      seconds < 86400 -> "Active #{div(seconds, 3600)} hours ago"
      true -> "Active #{div(seconds, 86400)} days ago"
    end
  end

  defp current_hashed_token(%{"user_token" => raw}) when is_binary(raw),
    do: Sigra.Token.hash_token(raw)

  defp current_hashed_token(_), do: nil

  defp current_session?(%{hashed_token: token}, current) when is_binary(current),
    do: token == current

  defp current_session?(_, _), do: false
end
