defmodule <%= web_module %>.TokenController do
  @moduledoc """
  JSON API controller for JWT authentication endpoints.

  Provides token-based authentication for API clients:

    - `POST /api/auth/token` -- authenticate with email/password, returns JWT
    - `POST /api/auth/token/refresh` -- refresh an access token
    - `POST /api/auth/token/mfa` -- complete MFA challenge for JWT auth
    - `DELETE /api/auth/token` -- revoke a refresh token

  When MFA is enabled for the user, the initial authentication returns
  `mfa_required: true` with a short-lived MFA token. The client must
  complete the MFA challenge via `/api/auth/token/mfa` to receive JWTs.

  Generated by `mix sigra.install --jwt`. Customize freely -- this
  module is owned by your application.
  """

  use <%= web_module %>, :controller

  alias <%= context_module %>, as: Auth

  @doc """
  Authenticates a user with email and password.

  Returns JWT access/refresh tokens on success, or `mfa_required: true`
  if the user has MFA enabled (D-47).
  """
  def create(conn, %{"email" => email, "password" => password} = params) do
    scopes = params["scopes"] || []

    case Auth.get_user_by_email_and_password(email, password) do
      nil ->
        conn |> put_status(401) |> json(%{error: "invalid_credentials"})

      user ->
        if Auth.mfa_enabled?(user) do
          # D-47: MFA required for JWT login
          config = Auth.sigra_config()
          mfa_token = Sigra.Token.generate_short_lived(config, user, "jwt_mfa", ttl: 300)

          conn
          |> put_status(403)
          |> json(%{
            mfa_required: true,
            mfa_token: mfa_token,
            mfa_methods: mfa_methods_for(user)
          })
        else
          issue_jwt_tokens(conn, user, scopes)
        end
    end
  end

  @doc """
  Refreshes JWT tokens using a refresh token.

  Implements refresh token rotation with family-based reuse detection.
  If reuse is detected, all tokens in the family are revoked (D-41).
  """
  def refresh(conn, %{"refresh_token" => refresh_token}) do
    config = Auth.sigra_config()

    case Sigra.Auth.refresh_jwt(config, refresh_token) do
      {:ok, tokens} ->
        json(conn, %{data: tokens})

      {:error, :reuse_detected} ->
        conn
        |> put_status(401)
        |> json(%{
          error: "token_revoked",
          detail: "Possible token theft detected. All tokens in this family have been revoked."
        })

      {:error, reason} ->
        conn |> put_status(401) |> json(%{error: to_string(reason)})
    end
  end

  @doc """
  Completes MFA challenge for JWT authentication.

  Verifies the MFA token and TOTP/backup code, then issues JWTs.
  """
  def mfa(conn, %{"mfa_token" => mfa_token, "code" => code} = params) do
    scopes = params["scopes"] || []
    config = Auth.sigra_config()

    with {:ok, user} <- Sigra.Token.verify_short_lived(config, mfa_token, "jwt_mfa"),
         {:ok, _} <- verify_mfa_code(user, code) do
      issue_jwt_tokens(conn, user, scopes)
    else
      {:error, :invalid_token} ->
        conn |> put_status(401) |> json(%{error: "invalid_mfa_token"})

      {:error, :expired} ->
        conn |> put_status(401) |> json(%{error: "mfa_token_expired"})

      {:error, :invalid_code} ->
        conn |> put_status(401) |> json(%{error: "invalid_mfa_code"})

      {:error, :locked} ->
        conn |> put_status(429) |> json(%{error: "mfa_locked", detail: "Too many failed attempts."})

      {:error, reason} ->
        conn |> put_status(401) |> json(%{error: to_string(reason)})
    end
  end

  @doc """
  Revokes a refresh token.

  Always returns success (even for invalid tokens) to prevent
  information leakage.
  """
  def revoke(conn, %{"refresh_token" => refresh_token}) do
    config = Auth.sigra_config()
    Sigra.Auth.revoke_jwt_refresh(config, refresh_token)
    json(conn, %{ok: true})
  end

  # -- Private helpers --

  defp issue_jwt_tokens(conn, user, scopes) do
    config = Auth.sigra_config()

    case Sigra.Auth.generate_jwt_tokens(config, user, scopes) do
      {:ok, tokens} ->
        json(conn, %{data: tokens})

      {:error, reason} ->
        conn |> put_status(422) |> json(%{error: to_string(reason)})
    end
  end

  defp verify_mfa_code(user, code) do
    case Auth.mfa_verify(user, code) do
      {:ok, _} -> {:ok, :verified}
      {:error, :invalid_code} -> {:error, :invalid_code}
      {:error, :locked} -> {:error, :locked}
      {:error, reason} ->
        # Try backup code as fallback
        case Auth.mfa_verify_backup(user, code) do
          {:ok, _} -> {:ok, :verified}
          _ -> {:error, reason}
        end
    end
  end

  defp mfa_methods_for(user) do
    methods = ["totp"]

    case Auth.mfa_status(user) do
      %{backup_codes_remaining: n} when n > 0 -> methods ++ ["backup_code"]
      _ -> methods
    end
  end
end
