<% auth_prefix = Keyword.get(binding(), :auth_prefix) %>
defmodule <%= context_module %>.UserMFACredential do
  @moduledoc """
  Ecto schema for MFA credentials (e.g., TOTP enrollment).

  Stores encrypted TOTP secrets, lockout tracking, and replay prevention.
  Maps to and from `Sigra.MFA.Credential` library struct.

  Generated by `mix sigra.install`. Customize freely -- this module
  is owned by your application.
  """

  use Ecto.Schema
  import Ecto.Changeset
<%= if binary_id do %>
  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
<% end %>
<%= if auth_prefix do %>  @schema_prefix "<%= auth_prefix %>"
<% end %>

  schema "user_mfa_credentials" do
    belongs_to :user, <%= context_module %>.<%= schema_alias %>
    field :type, :string
    field :encrypted_secret, <%= context_module %>.Encrypted.Binary
    field :last_used_at, :utc_datetime_usec
    field :last_verified_step, :integer
    field :failed_attempts, :integer, default: 0
    field :locked_until, :utc_datetime_usec
    field :enabled_at, :utc_datetime_usec

    timestamps(type: :utc_datetime_usec)
  end

  @doc "Changeset for creating a new MFA credential."
  def create_changeset(credential \\ %__MODULE__{}, attrs) do
    credential
    |> cast(attrs, [:user_id, :type, :encrypted_secret, :enabled_at])
    |> validate_required([:user_id, :type, :encrypted_secret])
    |> unique_constraint([:user_id, :type])
    |> foreign_key_constraint(:user_id)
  end

  @doc "Changeset for updating MFA credential fields (lockout, verification tracking)."
  def update_changeset(credential, attrs) do
    credential
    |> cast(attrs, [
      :last_used_at,
      :last_verified_step,
      :failed_attempts,
      :locked_until,
      :enabled_at
    ])
  end
end
