defmodule SigraInstallGoldenTmp.Accounts.Encrypted.Binary do
  @moduledoc """
  Ecto type for transparently encrypting binary fields via Cloak.

  Used by Sigra-managed MFA, passkey, and OAuth schemas that store secrets or
  cryptographic material at rest.

  Generated by `mix sigra.install`. Customize freely; this module is owned by
  your application.
  """

  use Cloak.Ecto.Binary, vault: SigraInstallGoldenTmp.Vault

  def __sigra_encryption_mode__, do: :vault
end
