defmodule SigraInstallGoldenTmp.Accounts.OrganizationMembership do
  @moduledoc """
  Schema for the `organization_memberships` table.

  Represents the join between users and organizations with a host-defined
  role atom. The last-owner guard in `Sigra.Organizations` prevents
  removing or demoting the sole owner via the role configured as
  `:owner_role` in your `use Sigra.Organizations` block.

  ## Role storage (Phase 92 / B2B-02)

  As of Phase 92 / Plan 92-02, the generator no longer hard-codes
  `:owner / :admin / :member` as the role taxonomy. The `:role` column
  is nullable host-owned data — your `use Sigra.Organizations` config
  declares the role universe (`:roles`), the owner role (`:owner_role`),
  and the invitation-admin roles (`:invitation_admin_roles`). If your
  app needs strict role validation, edit the changeset below to pin the
  role atom against your host taxonomy (or add an `Ecto.Enum` cast).

  This schema is generated by `mix sigra.install` and is owned by your
  application.
  """
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  schema "organization_memberships" do
    # Phase 92 / Plan 92-02: role is host-owned. The column is a plain
    # atom-as-string so hosts can use any role taxonomy declared in
    # `use Sigra.Organizations` `:roles`. Add an `Ecto.Enum` cast here
    # if you want strict schema-level validation.
    field :role, :string

    belongs_to :organization, SigraInstallGoldenTmp.Accounts.Organization
    belongs_to :user, SigraInstallGoldenTmp.Accounts.User

    timestamps(type: :utc_datetime)
  end

  @doc """
  A changeset for creating or updating a membership.

  Casts `:role`, `:user_id`, and `:organization_id`. Only foreign-key
  fields are required; `:role` is nullable so flows like accept-invite-
  then-pick-role work without fighting the changeset. Add
  `validate_required(:role)` here if your app requires a role at
  membership creation.
  """
  def changeset(membership, attrs) do
    membership
    |> cast(attrs, [:role, :user_id, :organization_id])
    |> validate_required([:user_id, :organization_id])
    |> assoc_constraint(:user)
    |> assoc_constraint(:organization)
    |> unique_constraint([:user_id, :organization_id])
  end
end
