defmodule SigraInstallGoldenTmp.Accounts.Organization do
  @moduledoc """
  Schema for the `organizations` table.

  Organizations are the primary multi-tenant unit. Each organization has
  a unique slug (used in URLs) and supports soft-delete via `deleted_at`.

  This schema is generated by `mix sigra.install` and is owned by your
  application. Security-critical operations (create, delete, membership
  management) are handled by the `Sigra.Organizations` library module.
  """
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  schema "organizations" do
    field :name, :string
    field :slug, :string
    field :deleted_at, :utc_datetime
    # D-01: personal-workspace flag (Phase 18). Library-managed, NOT exposed via cast/3.
    field :personal, :boolean, default: false
    # Phase 91 B2B-01: org-level MFA enforcement. Library-managed, NOT exposed via cast/3.
    field :enforce_mfa_for_members, :boolean, default: false

    # D-00: sticky origin owner (Phase 18). Library sets via put_change/3 in
    # Sigra.Organizations.create_organization/3; NEVER exposed via cast/3.
    belongs_to :owner, SigraInstallGoldenTmp.Accounts.User, foreign_key: :owner_user_id

    has_many :memberships, SigraInstallGoldenTmp.Accounts.OrganizationMembership
    has_many :invitations, SigraInstallGoldenTmp.Accounts.OrganizationInvitation

    timestamps(type: :utc_datetime)
  end

  @doc """
  A changeset for creating or updating an organization.

  Validates required fields and slug format. The slug must be lowercase
  alphanumeric with hyphens, 3-63 characters, starting with a letter.
  """
  def changeset(organization, attrs) do
    organization
    |> cast(attrs, [:name, :slug, :deleted_at])
    |> validate_required([:name, :slug])
    |> validate_length(:name, min: 1, max: 255)
    |> validate_length(:slug, min: 3, max: 63)
    |> validate_format(:slug, ~r/^[a-z][a-z0-9-]*[a-z0-9]$/, message: "must be lowercase alphanumeric with hyphens")
    |> unique_constraint(:slug, name: :organizations_slug_active_index)
  end
end
