
defmodule SigraInstallGoldenTmp.Accounts.OrganizationMembership do
  @moduledoc """
  Schema for the `organization_memberships` table.

  Represents the join between users and organizations with a role.
  Roles are constrained to `:owner`, `:admin`, and `:member` via
  `Ecto.Enum`. The last-owner guard in `Sigra.Organizations` prevents
  removing or demoting the sole owner.

  This schema is generated by `mix sigra.install` and is owned by your
  application.
  """
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  @schema_prefix "auth"


  schema "organization_memberships" do
    field :role, Ecto.Enum, values: [:owner, :admin, :member]

    belongs_to :organization, SigraInstallGoldenTmp.Accounts.Organization
    belongs_to :user, SigraInstallGoldenTmp.Accounts.User

    timestamps(type: :utc_datetime)
  end

  @doc """
  A changeset for creating or updating a membership.

  Validates the required `role` field and the uniqueness constraint
  on the `[:user_id, :organization_id]` pair.
  """
  def changeset(membership, attrs) do
    membership
    |> cast(attrs, [:role, :user_id, :organization_id])
    |> validate_required([:role, :user_id, :organization_id])
    |> assoc_constraint(:user)
    |> assoc_constraint(:organization)
    |> unique_constraint([:user_id, :organization_id])
  end
end
