
defmodule SigraInstallGoldenTmp.Accounts.OrganizationSlugAlias do
  @moduledoc """
  Schema for the `organization_slug_aliases` table.

  When an organization's slug is changed via `update_slug/4`, the previous
  slug is inserted into this table with `expires_at = now + 7 days`. The
  `Sigra.Plug.LoadOrganizationFromSlug` plug follows these alias rows to
  redirect old URLs to the canonical slug for the 7-day grace period.

  After the `expires_at` timestamp passes, the alias becomes dormant and
  the old slug is eligible for reclamation by another organization (the
  partial unique index is scoped to `expires_at > now()` on PostgreSQL).

  This schema is generated by `mix sigra.install` and is owned by your
  application. Validation + lifecycle lives in `Sigra.Organizations`.
  """
  use Ecto.Schema

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  @schema_prefix "auth"


  schema "organization_slug_aliases" do
    field :old_slug, :string
    field :expires_at, :utc_datetime

    belongs_to :organization, SigraInstallGoldenTmp.Accounts.Organization

    timestamps(type: :utc_datetime, updated_at: false)
  end
end
