
defmodule SigraInstallGoldenTmp.Accounts.UserPasskey do
  @moduledoc """
  Ecto schema for WebAuthn passkey credentials.

  Stores the credential id, encrypted COSE public key, authenticator
  metadata, and usage tracking. Maps to and from `Sigra.Passkeys.Credential`.

  Generated by `mix sigra.install`. Customize freely -- this module
  is owned by your application.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id


  @schema_prefix "auth"


  schema "user_passkeys" do
    belongs_to :user, SigraInstallGoldenTmp.Accounts.User
    field :credential_id, :binary
    field :public_key, SigraInstallGoldenTmp.Accounts.Encrypted.Binary
    field :sign_count, :integer, default: 0
    field :aaguid, Ecto.UUID
    field :nickname, :string
    field :device_hint, :string
    field :transports, {:array, :string}, default: []
    field :rp_id, :string
    field :last_used_at, :utc_datetime_usec

    timestamps(type: :utc_datetime_usec)
  end

  @doc "Changeset for creating a new passkey credential."
  def create_changeset(passkey \\ %__MODULE__{}, attrs) do
    passkey
    |> cast(attrs, [
      :user_id,
      :credential_id,
      :public_key,
      :sign_count,
      :aaguid,
      :nickname,
      :device_hint,
      :transports,
      :rp_id,
      :last_used_at
    ])
    |> validate_required([:user_id, :credential_id, :public_key])
    |> validate_number(:sign_count, greater_than_or_equal_to: 0)
    |> validate_length(:transports, max: 8)
    |> update_change(:transports, &Enum.uniq/1)
    |> unique_constraint(:credential_id)
    |> foreign_key_constraint(:user_id)
  end

  @doc "Changeset for updating passkey usage and display fields."
  def update_changeset(passkey, attrs) do
    passkey
    |> cast(attrs, [
      :sign_count,
      :nickname,
      :device_hint,
      :transports,
      :rp_id,
      :last_used_at
    ])
    |> validate_number(:sign_count, greater_than_or_equal_to: 0)
    |> validate_length(:transports, max: 8)
    |> update_change(:transports, &Enum.uniq/1)
  end
end
