defmodule SigraInstallGoldenTmpWeb.ConfirmationHTML do
  @moduledoc """
  Controller-mode confirmation templates for non-LiveView installs.

  Provides code entry, already-confirmed, and expired token pages.

  Generated by `mix sigra.install --no-live`. Customize freely -- this module
  is owned by your application.
  """
  use SigraInstallGoldenTmpWeb, :html
  import SigraInstallGoldenTmpWeb.SigraAuthComponents

  use Gettext, backend: SigraInstallGoldenTmpWeb.Gettext

  def new(assigns) do
    ~H"""
    <.sigra_auth_page>
      <div class="sigra-auth-flow sigra-auth-stack sigra-auth-stack--6">
      <.header>
        {dgettext("sigra", "Confirm your email")}
        <:subtitle>
          {dgettext("sigra", "Enter the 6-digit code we sent to your email, or check your inbox for a confirmation link.")}
        </:subtitle>
      </.header>

      <.form for={%{}} id="confirmation_form" action={~p"/users/confirm"} method="post" class="sigra-auth-stack sigra-auth-stack--4">
        <.input
          name="code"
          type="text"
          label={dgettext("sigra", "Confirmation code")}
          inputmode="numeric"
          autocomplete="one-time-code"
          maxlength="6"
          pattern="[0-9]{6}"
          aria-label={dgettext("sigra", "Confirmation code")}
          class="sigra-auth-code-input"
          required
        />

        <.sigra_auth_button class="sigra-auth-action sigra-auth-action--primary sigra-auth-action--block">
          {dgettext("sigra", "Confirm email")} <span aria-hidden="true">&rarr;</span>
        </.sigra_auth_button>
      </.form>

      <.form for={%{}} action={~p"/users/confirm/resend"} method="post">
        <button type="submit" class="sigra-auth-action sigra-auth-action--ghost sigra-auth-action--block">
          {dgettext("sigra", "Didn't receive a code?")}
        </button>
      </.form>
      </div>
    </.sigra_auth_page>
    """
  end

  def already_confirmed(assigns) do
    ~H"""
    <.sigra_auth_page>
      <div class="sigra-auth-flow sigra-auth-stack sigra-auth-stack--6">
      <.header>
        {dgettext("sigra", "Email already confirmed")}
        <:subtitle>
          {dgettext("sigra", "Your email was already confirmed. You can log in below.")}
        </:subtitle>
      </.header>

      <p class="sigra-auth-copy sigra-auth-copy--center">
        <.link navigate={~p"/users/log_in"}>
          {dgettext("sigra", "Log in")}
        </.link>
      </p>
      </div>
    </.sigra_auth_page>
    """
  end

  def expired(assigns) do
    ~H"""
    <.sigra_auth_page>
      <div class="sigra-auth-flow sigra-auth-stack sigra-auth-stack--6">
      <.header>
        {dgettext("sigra", "Confirmation link expired")}
        <:subtitle>
          {dgettext("sigra", "This confirmation link has expired or was already used.")}
        </:subtitle>
      </.header>

      <.form for={%{}} action={~p"/users/confirm/resend"} method="post">
        <.sigra_auth_button class="sigra-auth-action sigra-auth-action--primary sigra-auth-action--block">
          {dgettext("sigra", "Send new confirmation email")} <span aria-hidden="true">&rarr;</span>
        </.sigra_auth_button>
      </.form>
      </div>
    </.sigra_auth_page>
    """
  end
end
