defmodule SigraInstallGoldenTmpWeb.MFAChallengeHTML do
  @moduledoc """
  Controller-mode MFA challenge templates for non-LiveView installs.

  Provides the two-factor authentication verification page with
  TOTP authenticator code and backup code tabs.

  Generated by `mix sigra.install --no-live`. Customize freely -- this module
  is owned by your application.
  """
  use SigraInstallGoldenTmpWeb, :html
  import SigraInstallGoldenTmpWeb.SigraAuthComponents

  def mfa_challenge(assigns) do
    ~H"""
    <.sigra_auth_page>
      <div class="sigra-auth-flow sigra-auth-stack sigra-auth-stack--6">
      <.header>
        Two-factor authentication
        <:subtitle>
          Enter the code for {@masked_email}
        </:subtitle>
      </.header>

      <% # Tab bar (D-21) %>
      <div role="tablist" aria-label="Verification method">
        <div class="sigra-auth-tabs">
          <button
            type="button"
            role="tab"
            id="tab-totp"
            aria-selected={@tab == "totp"}
            aria-controls="panel-totp"
            class="sigra-auth-tab"
            onclick="switchTab('totp')"
          >
            Authenticator code
          </button>
          <button
            type="button"
            role="tab"
            id="tab-backup"
            aria-selected={@tab == "backup"}
            aria-controls="panel-backup"
            class="sigra-auth-tab"
            onclick="switchTab('backup')"
          >
            Backup code
          </button>
        </div>
      </div>

      <% # TOTP Tab Content %>
      <div
        id="panel-totp"
        role="tabpanel"
        aria-labelledby="tab-totp"
        class={if @tab != "totp", do: "sigra-auth-hidden", else: "sigra-auth-stack sigra-auth-stack--4"}
      >
        <.form for={%{}} id="mfa_totp_form" action={~p"/users/mfa"} method="post" class="sigra-auth-stack sigra-auth-stack--4">
          <input type="hidden" name="mfa[method]" value="totp" />

          <div class="sigra-auth-stack sigra-auth-stack--4">
            <div>
              <label for="mfa_totp_code">
                Authenticator code
              </label>
              <input
                type="text"
                id="mfa_totp_code"
                name="mfa[code]"
                inputmode="numeric"
                pattern="[0-9]*"
                maxlength="6"
                autocomplete="one-time-code"
                autofocus
                required
                class="sigra-auth-code-input"
                aria-label="6-digit authenticator code"
              />
            </div>

            <label class="sigra-auth-check-row">
              <input type="checkbox" name="mfa[trust]" value="true" class="sigra-auth-check" />
              Trust this browser for 30 days
            </label>

            <.sigra_auth_button class="sigra-auth-action sigra-auth-action--primary sigra-auth-action--block">
              Verify
            </.sigra_auth_button>
          </div>
        </.form>
      </div>

      <% # Backup Code Tab Content %>
      <div
        id="panel-backup"
        role="tabpanel"
        aria-labelledby="tab-backup"
        class={if @tab != "backup", do: "sigra-auth-hidden", else: "sigra-auth-stack sigra-auth-stack--4"}
      >
        <.form for={%{}} id="mfa_backup_form" action={~p"/users/mfa"} method="post" class="sigra-auth-stack sigra-auth-stack--4">
          <input type="hidden" name="mfa[method]" value="backup" />

          <div class="sigra-auth-stack sigra-auth-stack--4">
            <div>
              <label for="mfa_backup_code">
                Backup code
              </label>
              <input
                type="text"
                id="mfa_backup_code"
                name="mfa[code]"
                placeholder="XXXX-XXXX"
                required
                class="sigra-auth-code-input"
                aria-label="Backup code"
              />
            </div>

            <.sigra_auth_button class="sigra-auth-action sigra-auth-action--primary sigra-auth-action--block">
              Verify
            </.sigra_auth_button>
          </div>
        </.form>
      </div>

      <% # Remaining attempts hint (D-38) %>
      <div aria-live="polite">
        <p class="sigra-auth-copy sigra-auth-copy--muted sigra-auth-copy--center">
          Enter the code from your authenticator app to continue.
        </p>
      </div>

      <% # Cancel link (D-34) %>
      <p class="sigra-auth-copy sigra-auth-copy--center">
        <.link href={~p"/users/log_out"} method="delete">
          Cancel and sign out
        </.link>
      </p>
      </div>

      <% # Tab switching JS %>
      <script>
      function switchTab(tab) {
        // Update tab buttons
        document.querySelectorAll('[role="tab"]').forEach(function(btn) {
          var isActive = btn.id === 'tab-' + tab;
          btn.setAttribute('aria-selected', isActive);
        });
        // Update tab panels
        document.querySelectorAll('[role="tabpanel"]').forEach(function(panel) {
          if (panel.id === 'panel-' + tab) {
            panel.classList.remove('sigra-auth-hidden');
            var input = panel.querySelector('input[name="mfa[code]"]');
            if (input) input.focus();
          } else {
            panel.classList.add('sigra-auth-hidden');
          }
        });
      }

      // Auto-submit TOTP when 6 digits entered (D-36)
      document.addEventListener('DOMContentLoaded', function() {
        var totpInput = document.getElementById('mfa_totp_code');
        if (totpInput) {
          totpInput.addEventListener('input', function() {
            if (this.value.length === 6 && /^\d{6}$/.test(this.value)) {
              this.closest('form').requestSubmit();
            }
          });
        }
      });
      </script>
    </.sigra_auth_page>
    """
  end
end
