defmodule SigraInstallGoldenTmpWeb.OrganizationSwitchController do
  @moduledoc """
  Controller for switching the active organization for the current user.

  POST /organizations/switch — sensitive mutation via HTTP POST (D-05 /
  ORG-UX-03). Body: `%{"organization_id" => id, "return_to" => local_path}`.

  Membership-before-write is enforced by looking up the target organization
  through the current user's memberships only. Unknown or cross-tenant
  organization ids return 404 for enumeration prevention (D-04).

  `return_to` is validated as a local path (leading `/`, not `//`) — the
  same pattern used by `SigraInstallGoldenTmpWeb.Auth.SudoController`. External
  URLs fall back to `~p"/"`.

  Generated by `mix sigra.install`. Customize freely -- this module is
  owned by your application.
  """

  use SigraInstallGoldenTmpWeb, :controller

  alias SigraInstallGoldenTmp.Organizations

  def update(conn, %{"organization_id" => org_id} = params) do
    scope = conn.assigns.current_scope
    return_to = safe_return_to(Map.get(params, "return_to"))

    case fetch_member_org(scope, org_id) do
      {:ok, org} ->
        case Organizations.set_active_organization(conn, org) do
          {:ok, conn} ->
            conn
            |> put_flash(:info, "Switched to #{org.name}.")
            |> redirect(to: return_to)

          %Plug.Conn{} = conn ->
            # set_active_organization/2 may return the updated conn directly
            conn
            |> put_flash(:info, "Switched to #{org.name}.")
            |> redirect(to: return_to)

          {:error, _reason} ->
            conn
            |> put_status(:not_found)
            |> put_view(html: SigraInstallGoldenTmpWeb.ErrorHTML)
            |> render(:"404")
            |> halt()
        end

      :error ->
        conn
        |> put_status(:not_found)
        |> put_view(html: SigraInstallGoldenTmpWeb.ErrorHTML)
        |> render(:"404")
        |> halt()
    end
  end

  # Local-path validation — same pattern as SudoController. An external
  # URL or missing value falls back to ~p"/".
  defp safe_return_to(path) when is_binary(path) do
    if String.starts_with?(path, "/") and not String.starts_with?(path, "//") do
      path
    else
      ~p"/"
    end
  end

  defp safe_return_to(_), do: ~p"/"

  # Look up the target organization through the current user's memberships.
  # Returns `{:ok, org}` only when the user is an active member of `org_id`;
  # otherwise returns `:error` so the caller can render 404.
  defp fetch_member_org(scope, org_id) do
    user_orgs = Organizations.list_organizations_for_user(scope.user)

    Enum.find_value(user_orgs, :error, fn
      {%{id: ^org_id} = org, _role} -> {:ok, org}
      %{id: ^org_id} = org -> {:ok, org}
      _ -> nil
    end)
  end
end
