defmodule SigraInstallGoldenTmpWeb.Auth.SessionLive do
  @moduledoc """
  LiveView for session listing and management.

  Displays all active sessions for the current user with device info,
  IP address, location, and last active time. Supports revoking individual
  sessions and logging out of all devices.

  Current session is identified from the server-side Plug session token
  (hashed for comparison) and tagged with a "This device" badge.

  Generated by `mix sigra.install --live`. Customize freely -- this module
  is owned by your application.
  """
  use SigraInstallGoldenTmpWeb, :live_view
  import SigraInstallGoldenTmpWeb.SigraAuthComponents

  alias SigraInstallGoldenTmp.Accounts, as: Auth

  def mount(_params, session, socket) do
    user = socket.assigns.current_scope.user
    sessions = Auth.list_sessions(user)

    {:ok, assign(socket,
      sessions: sessions,
      current_hashed_token: current_hashed_token(session),
      page_title: "Active Sessions"
    )}
  end

  def render(assigns) do
    ~H"""
    <.sigra_auth_page>
      <div class="sigra-auth-flow sigra-auth-flow--wide sigra-auth-stack sigra-auth-stack--6">
      <.header>
        Active Sessions
        <:subtitle>These devices are currently signed in to your account.</:subtitle>
      </.header>

      <div class="sigra-auth-stack sigra-auth-stack--4">
        <div
          :for={session <- @sessions}
          class="sigra-auth-section sigra-auth-split"
        >
          <div class="sigra-auth-grow sigra-auth-stack sigra-auth-stack--2">
            <div class="sigra-auth-cluster">
              <strong>
                <%= device_name(session) %>
              </strong>
              <span
                :if={current_session?(session, @current_hashed_token)}
                class="sigra-auth-status sigra-auth-status--success"
              >
                This device
              </span>
            </div>
            <div class="sigra-auth-copy sigra-auth-copy--muted">
              <span><%= session.ip || "Unknown IP" %></span>
              <span aria-hidden="true">&middot;</span>
              <span><%= location(session) %></span>
            </div>
            <div class="sigra-auth-copy sigra-auth-copy--muted">
              <%= relative_time(session.last_active_at) %>
            </div>
          </div>
          <div>
            <%= if current_session?(session, @current_hashed_token) do %>
              <.sigra_auth_button
                phx-click="revoke_current"
                phx-value-token={Base.url_encode64(session.hashed_token)}
                data-confirm="This is your current session. Revoking it will log you out. Continue?"
                class="sigra-auth-action sigra-auth-action--danger sigra-auth-action--small"
              >
                Revoke session
              </.sigra_auth_button>
            <% else %>
              <.sigra_auth_button
                phx-click="revoke"
                phx-value-token={Base.url_encode64(session.hashed_token)}
                class="sigra-auth-action sigra-auth-action--danger sigra-auth-action--small"
              >
                Revoke session
              </.sigra_auth_button>
            <% end %>
          </div>
        </div>
      </div>

      <div :if={length(@sessions) > 1} class="sigra-auth-disclosure">
        <.sigra_auth_button
          phx-click="revoke_all"
          data-confirm="This will end all sessions including your current one. You will be logged out."
          class="sigra-auth-action sigra-auth-action--danger"
        >
          Log out of all devices
        </.sigra_auth_button>
      </div>
      </div>
    </.sigra_auth_page>
    """
  end

  def handle_event("revoke", %{"token" => encoded_token}, socket) do
    hashed_token = Base.url_decode64!(encoded_token)
    Auth.revoke_session(hashed_token)

    sessions = Auth.list_sessions(socket.assigns.current_scope.user)
    {:noreply, socket |> put_flash(:info, "Session revoked.") |> assign(sessions: sessions)}
  end

  def handle_event("revoke_current", %{"token" => encoded_token}, socket) do
    hashed_token = Base.url_decode64!(encoded_token)
    Auth.revoke_session(hashed_token)

    {:noreply, redirect(socket, to: ~p"/users/log_in")}
  end

  def handle_event("revoke_all", _params, socket) do
    user = socket.assigns.current_scope.user
    Auth.revoke_all_sessions(user)

    {:noreply, redirect(socket, to: ~p"/users/log_in")}
  end

  defp device_name(%{parsed_ua: %{browser: browser, browser_version: version, os: os}})
       when browser != "Unknown" do
    if version, do: "#{browser} #{version} on #{os}", else: "#{browser} on #{os}"
  end

  defp device_name(_), do: "Unknown device"

  defp location(%{geo_city: city, geo_country_code: country}) when is_binary(city),
    do: "#{city}, #{country}"

  defp location(_), do: "Unknown location"

  defp relative_time(nil), do: "Never"

  defp relative_time(datetime) do
    seconds = DateTime.diff(DateTime.utc_now(), datetime, :second)

    cond do
      seconds < 60 -> "Active just now"
      seconds < 3600 -> "Active #{div(seconds, 60)} minutes ago"
      seconds < 86400 -> "Active #{div(seconds, 3600)} hours ago"
      true -> "Active #{div(seconds, 86400)} days ago"
    end
  end

  defp current_hashed_token(%{"user_token" => raw}) when is_binary(raw) do
    case Base.url_decode64(raw, padding: false) do
      {:ok, decoded} -> Sigra.Token.hash_token(decoded)
      :error -> nil
    end
  end

  defp current_hashed_token(_), do: nil

  defp current_session?(%{hashed_token: token}, current) when is_binary(current),
    do: token == current

  defp current_session?(_, _), do: false
end
