defmodule <%= context_module %>.OrganizationMembership do
  @moduledoc """
  Schema for the `organization_memberships` table.

  Represents the join between users and organizations with a role.
  Roles are constrained to `:owner`, `:admin`, and `:member` via
  `Ecto.Enum`. The last-owner guard in `Sigra.Organizations` prevents
  removing or demoting the sole owner.

  This schema is generated by `mix sigra.install` and is owned by your
  application.
  """
  use Ecto.Schema
  import Ecto.Changeset
<%= if binary_id do %>
  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
<% end %>
  schema "organization_memberships" do
    field :role, Ecto.Enum, values: [:owner, :admin, :member]

    belongs_to :organization, <%= context_module %>.Organization
    belongs_to :user, <%= context_module %>.<%= schema_alias %>

    timestamps(type: :utc_datetime)
  end

  @doc """
  A changeset for creating or updating a membership.

  Validates the required `role` field and the uniqueness constraint
  on the `[:user_id, :organization_id]` pair.
  """
  def changeset(membership, attrs) do
    membership
    |> cast(attrs, [:role])
    |> validate_required([:role])
    |> unique_constraint([:user_id, :organization_id])
  end
end
