defmodule <%= context_module %>.OrganizationMembership do
  @moduledoc """
  Schema for the `organization_memberships` table.

  Represents the join between users and organizations with a host-defined
  role atom. The last-owner guard in `Sigra.Organizations` prevents
  removing or demoting the sole owner via the role configured as
  `:owner_role` in your `use Sigra.Organizations` block.

  ## Role storage (Phase 92 / B2B-02)

  As of Phase 92 / Plan 92-02, the generator no longer hard-codes
  `:owner / :admin / :member` as the role taxonomy. The `:role` column
  is nullable host-owned data — your `use Sigra.Organizations` config
  declares the role universe (`:roles`), the owner role (`:owner_role`),
  and the invitation-admin roles (`:invitation_admin_roles`).

  The field uses `Sigra.Ecto.Types.RoleAtom` so role values round-trip
  as atoms (the form Sigra's authorization seams compare against) while
  the DB column stays a plain string the host can edit. Strict
  validation against the configured `:roles` universe is enforced
  centrally by `Sigra.Organizations.add_member/5` and `change_role/4`,
  so even ad-hoc changesets cannot insert a role outside the host's
  declared taxonomy. Add `validate_inclusion(:role, configured_roles)`
  here if you want changeset-level errors in addition to the library
  guard.

  This schema is generated by `mix sigra.install` and is owned by your
  application.
  """
  use Ecto.Schema
  import Ecto.Changeset
<%= if binary_id do %>
  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
<% end %>
  schema "organization_memberships" do
    # Role is host-owned. The DB column is a plain string;
    # `Sigra.Ecto.Types.RoleAtom` round-trips the value as an atom in
    # Elixir code so authorization comparisons (`role in [:owner, :admin]`,
    # `role == config.owner_role`) match without per-callsite conversions.
    # Library-level enforcement of the `:roles` universe lives in
    # `Sigra.Organizations.add_member/5` and `change_role/4`.
    field :role, Sigra.Ecto.Types.RoleAtom

    belongs_to :organization, <%= context_module %>.Organization
    belongs_to :user, <%= context_module %>.<%= schema_alias %>

    timestamps(type: :utc_datetime)
  end

  @doc """
  A changeset for creating or updating a membership.

  Casts `:role`, `:user_id`, and `:organization_id`. Only foreign-key
  fields are required; `:role` is nullable so flows like accept-invite-
  then-pick-role work without fighting the changeset. Add
  `validate_required(:role)` here if your app requires a role at
  membership creation.
  """
  def changeset(membership, attrs) do
    membership
    |> cast(attrs, [:role, :user_id, :organization_id])
    |> validate_required([:user_id, :organization_id])
    |> assoc_constraint(:user)
    |> assoc_constraint(:organization)
    |> unique_constraint([:user_id, :organization_id])
  end
end
