<% auth_prefix = Keyword.get(binding(), :auth_prefix) %>
defmodule <%= context_module %>.OrganizationInvitation do
  @moduledoc """
  Schema for the `organization_invitations` table.

  Invitations track pending, accepted, and revoked states via timestamps
  rather than an explicit status enum — this avoids dual-state bugs.

  - **Pending:** `accepted_at IS NULL AND revoked_at IS NULL`
  - **Accepted:** `accepted_at` is set
  - **Revoked:** `revoked_at` is set

  The `hashed_token` field stores the HMAC-signed invitation token.
  Phase 17 implements the full invitation flow (generation, email
  delivery, accept/reject).

  This schema is generated by `mix sigra.install` and is owned by your
  application.
  """
  use Ecto.Schema
  import Ecto.Changeset
<%= if binary_id do %>
  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
<% end %>
<%= if auth_prefix do %>  @schema_prefix "<%= auth_prefix %>"
<% end %>

  schema "organization_invitations" do
    field :email, :string
    field :role, Ecto.Enum, values: [:owner, :admin, :member]
    field :hashed_token, :binary
    field :accepted_at, :utc_datetime
    field :revoked_at, :utc_datetime
    field :expires_at, :utc_datetime

    belongs_to :organization, <%= context_module %>.Organization
    belongs_to :invited_by, <%= context_module %>.<%= schema_alias %>
    belongs_to :accepted_by, <%= context_module %>.<%= schema_alias %>
    belongs_to :revoked_by, <%= context_module %>.<%= schema_alias %>

    timestamps(type: :utc_datetime)
  end

  @doc """
  A changeset for creating an invitation.

  Validates required fields: `email`, `role`, and `expires_at`.
  Optional fields (`hashed_token`, `accepted_at`, `revoked_at`) are
  managed by the library's invitation flow logic (Phase 17).
  """
  def changeset(invitation, attrs) do
    invitation
    |> cast(attrs, [
      :email,
      :role,
      :expires_at,
      :hashed_token,
      :accepted_at,
      :revoked_at,
      :organization_id,
      :invited_by_id,
      :accepted_by_id,
      :revoked_by_id
    ])
    |> validate_required([:email, :role, :expires_at, :organization_id])
    |> assoc_constraint(:organization)
    |> unique_constraint([:organization_id, :email],
      name: :organization_invitations_pending_index
    )
  end
end
