defmodule ExampleWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :example

  @crosswake_session_secure Application.compile_env!(:example, :crosswake_session_secure)

  # The host session carries continuation-bound Crosswake transport, so it is
  # both signed and encrypted. Secure is fail-closed outside test configuration.
  @session_options [
    store: :cookie,
    key: "_example_key",
    signing_salt: "byPEl4ST",
    encryption_salt: "GJsw9WQP",
    http_only: true,
    secure: @crosswake_session_secure,
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :example,
    gzip: not code_reloading?,
    only: ExampleWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :example
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ExampleWeb.Router
end
